### ISSUE TITLE
How to handle router?

### ISSUE THREAD

**Issue by chuyik** [coryhouse/react-slingshot#10]
I notice that the example only has a single page, how would you handle router to other pages?
I think something should be integrated into this starter kit as a solution.

**Comment by coryhouse** [comment]
I decided not to include React Router for now since many simple apps don't require it.

**Comment by chuyik** [comment]
But only a simple page? I'm just curious. How about routing using webpack?

**Comment by coryhouse** [comment]
I'd recommend using React Router. That said, their API has been changing rapidly over the last few months. It's hopefully settled down now, but that's part of why I chose to leave it out of the starter kit.

**Comment by imranismail** [comment]
Good move cory. I like that you excluded react router

**Comment by coryhouse** [comment]
I'm closing this as a won't fix for now since I have no plans to add a router to the starter kit for now. I may revisit this as React Router further stabilizes.

**Comment by chuyik** [comment]
Yeah good to know that. I'd like be informed if some router is added to this project.

**Comment by barrystaes** [comment]
For reference, this is how i added a router, some pages, and a menu: 

https://github.com/barrystaes/react-slingshot/tree/feature-router

Disclaimer: i'm no expert. I just used `redux-simple-router` and its tutorial was pretty straight forward. (it uses `react-router` which most of us will know)

**Comment by coryhouse** [comment]
Nice! Thanks for sharing!

**Comment by barrystaes** [comment]
I just updated it to `redux-simple-router` v2.0.3 which now is the latest version.

https://github.com/barrystaes/react-slingshot/tree/feature-router

**Comment by barrystaes** [comment]
My branch wont work with PR #27 merged: merge conflict due to `configureStore.js` file being split into prod/dev versions. However i combined both in my `react-trebuchet` fork.

PS. If desired i would be happy to provide a PR today. (but not later)
