### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by corzzo** [coryhouse/react-slingshot#101]
Hi Cory, I'm trying to integrate react-slingshot with some of my previous projects' databases (MySQL/MongoDB). Let me know if you have done this or I should refer to another one of your projects. Thanks.

**Comment by coryhouse** [comment]
Hi @corzzo, that's really orthogonal from this starter kit. I'd expect to interact with the database through a web API, and make those AJAX calls via some client-side library like Axios or isomorphic fetch.
