### ISSUE TITLE
mocha: 'npm start' stops if no .spec.js files in src/

### ISSUE THREAD

**Issue by j5v** [coryhouse/react-slingshot#105]
This might be a **mocha** bug, and therefore outside the scope of this project; feel free to close.

On clearing the `src/` folder, and placing some other non-TDD project there, I find that the `npm start` (more specifically, the `test` script) fails, if there are no `.spec.js` files present.

I've not explored mocha enough to fix this, but a workaround is to create an empty `dummy.spec.js` file anywhere in `src/`

**Comment by coryhouse** [comment]
Yep, this is a known issue/feature, depending on your outlook. :) Haven't found an easy way to suppress it, but certainly open to suggestions.

**Comment by coryhouse** [comment]
Here's the previous discussion: https://github.com/coryhouse/react-slingshot/pull/86/files
