### ISSUE TITLE
Add babel-based code coverage

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#108]
Haven't gotten to try this out yet, but looks promising. http://dev.topheman.com/es6-code-coverage-with-babel-plugin/?utm_source=ESnextNews.com&utm_medium=Weekly%20Newsletter&utm_campaign=Week%2015

**Comment by dwmkerr** [comment]
@coryhouse I did this just recently here, http://www.dwmkerr.com/getting-started-with-react/, not too difficult to set up to be honest. I'd be happy to help!

**Comment by dwmkerr** [comment]
PR #142 raised to resolve this issue. Suggest keeping the discussion in #97, WDYT?
