### ISSUE TITLE
Strange issue with react-slingshot

### ISSUE THREAD

**Issue by namlook** [coryhouse/react-slingshot#112]
Hi guys,

Thank you for this project, it is really helpful ! But for a reason I can't figure out, I can't make the following jsfiddle working with react-slingshot:

https://jsfiddle.net/q3jroknc/

here is the repository that show the issue:

https://github.com/namlook/react-slingshot-semantic-ui-bug

The files to look at are:

 -  ./src/index.html (I added the CDN resources. Gross, I know, but I want to be as close as possible to the fiddle)
 - ./src/index.js (where I added the component)

 `npm start` and go to `http://localhost:3000` to see the issue.

Any ideas of what is going wrong here ?

Thanks !

**Comment by jeremyadavis** [comment]
You need to add the 'type' attribute to your Semantic css and js tags

`<link rel="stylesheet" type="text/css" href="https://rawgit.com/Semantic-Org/Semantic-UI/next/dist/semantic.css" />`

`<script type="text/javascript" src="https://rawgit.com/Semantic-Org/Semantic-UI/next/dist/semantic.js"></script>`

**Comment by namlook** [comment]
Damn ! How could I missed this ? It works perfectly now. Sorry for the noise 😳
