### ISSUE TITLE
Cannot resolve module [that exists]...

### ISSUE THREAD

**Issue by monte-hayward** [coryhouse/react-slingshot#118]
Hi Cory. Just trying out slingshot as an alternate build pattern. I must have something misconfigured? Ideas?

Got it running, then replaced example ./components with mine from a working project. At first it could not resolve index.jsx ( the routes "plus" file). Changed that to `.js`, and now it recognizes `index`. 

However, imports cannot be resolved, either named *.jsx or *.js

```terminal
./src/index.js
Module not found: Error: Cannot resolve module 'components/root' in /path/to/src
// ... repeats for each module
```

fwiw, my project has flux instead of redux. However, both are installed.

**Comment by coryhouse** [comment]
Hi Monty - I'm sorry but I don't have the time at the moment to resolve one-off custom issues. This is a better question for Stackoverflow, complete with a boiled down example.
