### ISSUE TITLE
no open-coverage script in package.json

### ISSUE THREAD

**Issue by abhijeetNmishra** [coryhouse/react-slingshot#12]
As per your README.md, test coverage has been done through Istanbul and should be run using 
```
npm run open-coverage
```
But this doesn't seem to be implemented at all !!!!

**Comment by coryhouse** [comment]
Sorry, that isn't implemented yet since I'm waiting for the new version of Istanbul which is expected to support Babel. I was trying to use Isparta but ran into some other issues with it and decided to remove it for now. Thanks for the heads up!
