### ISSUE TITLE
Consider adding react-router-redux

### ISSUE THREAD

**Issue by zsherman** [coryhouse/react-slingshot#122]
Would be nice to have https://github.com/reactjs/react-router-redux.

**Comment by tsongas** [comment]
@zsherman did you add it and if so do you have a link to a repo you could share so I could check it out?

**Comment by zsherman** [comment]
Yeah sure [here's a link](https://github.com/reactjs/react-router-redux), although according to this tweet the newer version of redux may make it unnecessary https://twitter.com/dan_abramov/status/729766588400939009.

**Comment by coryhouse** [comment]
I just added this in.  https://github.com/coryhouse/react-slingshot/commit/79db0f3a4ad66f35c765959286c3320c8f205ff0

Thanks for the suggestion!
