### ISSUE TITLE
Adding decorator possibilities

### ISSUE THREAD

**Issue by DrkCoater** [coryhouse/react-slingshot#126]
Thanks for providing such a clean and awesome boilerplate for the starting a react redux project. Awesome job!
I just want to know if I want to add ES6 experimental feature for decorator, such that I can put a redux connect as class decorator, what should I modify? Sorry in advance, if this question has been asked before.
eg.

@connect(
    state => ({info: state.info.data}),
    dispatch => bindActionCreators({load}, dispatch))

**Comment by coryhouse** [comment]
Thanks! You'll need to enable Babel stage-1 features in .babelrc. I think you'll also want to install and use eslint-loader since I don't believe native ESLint support experimental javascript features.
