### ISSUE TITLE
How to add favicon to /dist?

### ISSUE THREAD

**Issue by jforaker** [coryhouse/react-slingshot#128]
Seems trivial but is very difficult.  How to add a `favicon.ico` to the `npm run build` task?

**Comment by coryhouse** [comment]
Great question. Follow the same pattern used by tools/buildHTML. Just copy the file from the root of /src to the root of /dist

**Comment by jforaker** [comment]
Ok so I understand how to create the `<link .. >` html element, but how to "copy" the actual file from /src to /dist?

Here's what I have so far...

```
	const $ = cheerio.load(markup);
	const head = $('head');
	head.children().last()
		.after('<link rel="stylesheet" href="styles.css">')
		.after('<link rel="shortcut icon" href="favicon.ico">');
```

**Comment by coryhouse** [comment]
Ah, multiple ways to do that, but here's an easy way with Node: http://stackoverflow.com/questions/11293857/fastest-way-to-copy-file-in-node-js

**Comment by jforaker** [comment]
Hmm that is one way. Here's how I did it in case anyone lands on this thread:

1. require my favicon in my main App.js entry file 
 `require('../assets/images/favicon.ico')`

2. Added a loader configuration that does not scramble the image file names in the `build` task (per this thread https://github.com/webpack/webpack/issues/1336#issuecomment-171363119)
 ```
		{
			test: /\.jpe?g$|\.ico$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/,
			loader: 'file-loader?name=[name].[ext]'  // <-- retain original file name
		}
```

3. Add the standard `<link rel="shortcut icon" href="favicon.ico">` in src/index.html

Now `npm run build` will output the image/assets names as their original name, hence giving you the ability to  `href="favicon.ico"` right in your index.html

**Comment by coryhouse** [comment]
Nice! That solution is clearly better than my idea. :) I just tried adding this to Slingshot, but I'm getting an error. Would you be willing to submit a pull request? The only change I'd suggest from your snippet is to write a specific test for only the .ico file so that other filetypes can continue to be handled separately.

**Comment by jforaker** [comment]
Sure -->  https://github.com/coryhouse/react-slingshot/pull/129 😄 . Added specific test as you mentioned: https://github.com/coryhouse/react-slingshot/pull/129/files#diff-b83f3305d04bb1c8d674be30b5f9e1efR32  Tested and works well.

**Comment by chookie** [comment]
If anyone is having trouble now I followed as per @jforaker but changed slightly for ejs and es6 import.

In index.js
`import './images/favicon.ico';`

Add your favicon.ico to wherever, in my case in `src/images`

In webpack.config.*.js files
```
new HtmlWebpackPlugin({   
    favicon: 'src/images/favicon.ico'
```
and
`{test: /\.(jpe?g|png|gif|ico)$/i, loader: 'file?name=[name].[ext]'},`

**Comment by ryangpts** [comment]
I only needed this:

In webpack.config.*.js files

```
new HtmlWebpackPlugin({   
    favicon: 'src/images/favicon.ico'
```

**Comment by mikedevita** [comment]
@ryangpts thanks, this is what I needed as well...

**Comment by LiamKlyneker** [comment]
@ryangpts legend!!!

**Comment by StamatisDeli** [comment]
my favicon is in png format. it makes sense that it would work, but it's not

**Comment by nickytonline** [comment]
png should be supported. Please see https://www.w3.org/2005/10/howto-favicon @StamatisDeli.

**Comment by StamatisDeli** [comment]
I had to do this in plugins: 
   new HtmlWebPackPlugin({
      template: "./src/index.html",
      filename: "./index.html",
      favicon: './src/images/favicon-16x16.png'
    }),

**Comment by croraf** [comment]
> my favicon is in png format. it makes sense that it would work, but it's not

It does work in png!

**Comment by js2me** [comment]
Works for me
```
   {
        test: /\.html$/,
        loader: 'html-loader',
        options: {
          attrs: [':data-image', ':src', 'link:href'],
        },
      },
      {
        test: /\.(png|jpg|jpeg|svg)$/,
        use: 'file-loader?name=[hash:base64:7].[ext]',
      },
      {
        test: /favicon\.png$/,
        use: 'file-loader?name=[name].[ext]',
      },
```

**Comment by lucassalazar** [comment]
If u are using the hash to name the file, and using the `<link/>` tag to add a static favicon. Here is another solution:

In index.js
`import './images/favicon.png';`

In webpack.config.*.js files

```
            {
                test: /\.(svg|png|jpg|gif)$/,
                use: {
                    loader: "file-loader",
                    options: {
                        name (resourcePath) {
                            if (/favicon/.test(resourcePath)) {
                                return "[name].[ext]";
                            } else {
                                return "[name].[hash].[ext]";
                            }
                        },
                        publicPath: "images",
                        outputPath: "images"
                    }
                }
            },
```

**Comment by PerezCode** [comment]
### Year **2021**, that's how it worked for me:
This is the directory of my app
![Captura de pantalla 2021-06-20 221337](https://user-images.githubusercontent.com/46828714/122702340-d33b7480-d214-11eb-842b-f5c8d7ce6cdf.jpg)
* First I added `<link rel="shortcut icon" href="./favicon.png" type="image/png" />` to my index.html.
* Second, I added the following code line to my webpack.config.js and webpack.config.dev.js
![Captura de pantalla 2021-06-20 221337](https://user-images.githubusercontent.com/46828714/122702591-565cca80-d215-11eb-86dc-3da39a1a1b16.jpg)
