### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by harshmaur** [coryhouse/react-slingshot#131]
Hello, I am trying to achieve server side rendering with react-slingshot. The reason I want to do that is due to Search Engine Optimization. I have a lot of content coming up asynchronously in components which I want to index. 

Any leads would help.

**Comment by coryhouse** [comment]
Hello - I'd suggest reviewing an alternative boilerplate with server-side rendering built in: http://andrewhfarmer.com/starter-project/

**Comment by harshmaur** [comment]
Hi Thanks for the link. I liked your project a lot and easy to understand. I wanted to integrate server side render in react-slingshot as we have already started building on your boilerplate. 
Can you help me out with that?

**Comment by coryhouse** [comment]
Thanks! Unfortunately, doing server side well isn't trivial. That's why I suggest checking out alternatives to see how much is involved. You can then pull their patterns into Slingshot if desired, but there's no clear easy path I can provide to do so.
