### ISSUE TITLE
npm run build !error

### ISSUE THREAD

**Issue by joodies** [coryhouse/react-slingshot#133]
npm start is working, but i cant build it...

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@3.0.1 lint: `esw webpack.config.* src tools`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@3.0.1 lint script 'esw webpack.config.* src tools'.
npm ERR! This is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\..\react-slingshot\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_mod
ules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@3.0.1 prebuild: `npm run clean-dist && npm run build:html && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@3.0.1 prebuild script 'npm run clean-dist && npm run build:ht
ml && npm run lint'.
npm ERR! This is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean-dist && npm run build:html && npm run lint
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\..\npm-debug.log

**Comment by coryhouse** [comment]
Questions:
1. Does this work? `npm run prebuild`
2. If 1 doesn't work, try changing the lint script to look like this: `"lint": "node_modules/.bin/esw webpack.config.* src tools",` and change the remove-dist script to: `"remove-dist": "node_modules/.bin/rimraf ./dist",`
3. What OS?
4. What command line?
5. What Node and npm version?

**Comment by joodies** [comment]
Turns out to be webpack setting errors.

**Comment by coryhouse** [comment]
@joodies I'm confused. Are you saying you had to change the Slingshot webpack configuration? What did you have to change?

**Comment by joodies** [comment]
The reason is:
  `import avatar from './images/avatar.jpg';`
load image file failed in this way,  have to change to 
   `const avatar = require('./images/avatar.jpg');`
and use url-loader.
