### ISSUE TITLE
Add npm script to remove demo

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#134]
Deleting the files/folders to make starter from scratch is too hassle, deleting again and again for different project is troublesome, and it creates errors, when handling incorrectly. It should provided some command script ex. npm start scratch or something to clean files not needed. businessLogic, component files, router files, action files, etc... Especially, all files related to the example app.

**Comment by coryhouse** [comment]
I totally agree. I'm working on this.

**Comment by gitlovenotwar** [comment]
Thank you chief.

**Comment by coryhouse** [comment]
Committed! Get latest and give it a shot. Love to hear suggestions for improvement.

**Comment by gitlovenotwar** [comment]
npm remove-demo <- does not work

**Comment by coryhouse** [comment]
Where did I say that?  The command is:

npm run remove-demo

**Comment by gitlovenotwar** [comment]
boom! cool, working perfectly ;) Thanks. Awesome.

**Comment by dhana-abracontrols** [comment]
npm run remove-demo - not working
