### ISSUE TITLE
getInitialState

### ISSUE THREAD

**Issue by joodies** [coryhouse/react-slingshot#135]
Can i get any hint on writing getInitialState? Thanks

state = {}  , get wrong msg

**Comment by kwelch** [comment]
here is a link to the React docs directed to the ES6 Components. If you view the second example, initial state is now set in the `constructor`. 

https://facebook.github.io/react/docs/reusable-components.html#es6-classes

**Comment by joodies** [comment]
Thanks! :+1:  @kwelch
