### ISSUE TITLE
Importing images?

### ISSUE THREAD

**Issue by arjandha** [coryhouse/react-slingshot#138]
This may be a simple question but the `npm run build` command does not seem to grab the images I've added into a new directory called `src/images`. As a result, a broken image link is displayed.

I see in the webpack configs a loader for .jpegs, .pngs, and .gifs. 

I assume that the react way is to add these in a component via an `import image from '[location name here]'` invocation at the top of the component, but that doesn't seem to work either...

**Comment by kwelch** [comment]
Why did you close? How did you handle it? I wrote a new section into my buildHtml.js that does the copy from src to dist. Did the import work? If so I may make the same adjustments, it sounds cleaner.
