### ISSUE TITLE
Create Project Logo

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#147]
I'd love to see proposals for a project logo.

**Comment by vdclouis** [comment]
![https://cldup.com/oA_J0jZ0eH.png](https://cldup.com/oA_J0jZ0eH.png)

some ideas

**Comment by coryhouse** [comment]
@vdclouis Thanks for the proposals! I like the logo on the bottom right best.

**Comment by vdclouis** [comment]
another idea:
![](https://cldup.com/i-r63250t8.png)

**Comment by kwelch** [comment]
I like custom text with a logo, but would put focusing color on Slingshot instead of React. (this is just my preference the slingshot part is the uniqueness)

Also, have to agree on the bottom right of the first set.

**Comment by simsketch** [comment]
![image](https://cloud.githubusercontent.com/assets/3129129/21354211/217a931c-c697-11e6-8bca-5cb7428d56cc.png)

**Comment by simsketch** [comment]
![image](https://cloud.githubusercontent.com/assets/3129129/21354744/42afc578-c699-11e6-91bb-48258055e6f8.png)

**Comment by coryhouse** [comment]
Thanks for the proposals @simsketch! I like both, but I think my favorite so far remains the one above by @vdclouis.

**Comment by simsketch** [comment]
ok how about this one?

![image](https://cloud.githubusercontent.com/assets/3129129/22800217/9f620168-eed6-11e6-987b-61b3ac441e94.png)

**Comment by kwelch** [comment]
I like that one. I think the work "react" should be in it. Putting in that last one in the react blue was look really good IMO.

**Comment by simsketch** [comment]
thanks @kwelch 

![image](https://cloud.githubusercontent.com/assets/3129129/22804870/072b2718-eee9-11e6-93c1-2797a548c159.png)

and

![image](https://cloud.githubusercontent.com/assets/3129129/22804912/34987462-eee9-11e6-8b29-f85511c8e125.png)

or maybe just

![image](https://cloud.githubusercontent.com/assets/3129129/22804940/50c1f5dc-eee9-11e6-97e3-ce0764e53f63.png)

**Comment by kwelch** [comment]
I like the last but only react in the blue, rest in the graphite. 

This and @vdclouis's are my favorites at this point.

**Comment by coryhouse** [comment]
Great work @simsketch! Agree with @kwelch that yours and @vdclouis are my favs

**Comment by simsketch** [comment]
thanks @coryhouse, glad you like it!

> I like the last but only react in the blue, rest in the graphite.

nice idea.

![image](https://cloud.githubusercontent.com/assets/3129129/22811426/bb69dc06-ef0c-11e6-8092-a0bea9060b35.png)

**Comment by kwelch** [comment]
Yeah with that coloring that has gone to the top spot on my list 😍

**Comment by coryhouse** [comment]
Agreed, looks great with the color change! I've added it to the Readme.md.

Whatta ya think @nickytonline?

**Comment by coryhouse** [comment]
One thought @simsketch - The little dot/ball might look cool in the same blue to help draw it out.

**Comment by simsketch** [comment]
![image](https://cloud.githubusercontent.com/assets/3129129/22830970/87852f02-ef76-11e6-8a38-a5f41ba8fc94.png)

**Comment by coryhouse** [comment]
Thanks @simsketch. Everyone, please vote on the change above with thumbs. Better or worse?

**Comment by mikedevita** [comment]
the circle bugs me

**Comment by coryhouse** [comment]
@mikedevita Without the circle it'd be too generic. I think of it like a reference to a stone sitting in a slingshot.

**Comment by kwelch** [comment]
Now we must animate it 😈 

In seriousness, I want cannot wait for t-shirts and stickers of this 😍

**Comment by mikedevita** [comment]
Thanks, the explanation now makes sense.

[logo_326x100]
Mike DeVita
E: mike@relative.media<mailto:mike@relative.media> | C: [602] 541-4137 | W: https://relative.media<https://relative.media/>

**Comment by nickytonline** [comment]
@coryhouse, I definitely like the one with just the word react in blue. Added my thumb to it.

**Comment by coryhouse** [comment]
Logo selected! Thanks so much to @simsketch! 🎉 💯

**Comment by coryhouse** [comment]
And thanks to all others who contributed proposals too!
