### ISSUE TITLE
Changed port

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#159]
How to change the port on dev mode?

**Comment by coryhouse** [comment]
[Here](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.dev.js#L20).

**Comment by gitlovenotwar** [comment]
Already done that, but still not working, still at :3000. 

P.S. I've hosted the files on cloud9

**Comment by gitlovenotwar** [comment]
Fixed it by adding port on srcServer.js

**Comment by coryhouse** [comment]
Yep, just committed an explicit port there to clarify. It was using the default. https://github.com/coryhouse/react-slingshot/blob/master/tools/srcServer.js#L18
