### ISSUE TITLE
Test coverage includes `spec` files in its report

### ISSUE THREAD

**Issue by FarhadG** [coryhouse/react-slingshot#162]
I've noticed that the test coverage includes the `spec.js` files in its report, which, I assume, is not intended behavior as it conflates the overall report.

Node version: 5^
npm version: 3^
Operating system: OSX
Command line used: npm run test:cover

**Comment by coryhouse** [comment]
@FarhadG - Great point. Do you happen to know an easy way to exclude them?

**Comment by FarhadG** [comment]
Not at the moment, @coryhouse. I'll take a look, though.

**Comment by coryhouse** [comment]
I haven't figured out a way to exclude them from the report yet, but would welcome insight from anyone willing.

**Comment by peel3r** [comment]
how about moving all tests to "test" directory?

**Comment by peel3r** [comment]
To fix this  create a .istanbul.yml file in the root of react-slingshot with:
`instrumentation:
  excludes: ['*.spec.js']
  extensions: ['.js']`

**Comment by coryhouse** [comment]
Awesome! That was easy. Thanks for the tip! 👍 

Commit: https://github.com/coryhouse/react-slingshot/commit/492e5b7e92740b1e80dd07ed65a18d7d07ab0fd9
