### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by nmganesh** [coryhouse/react-slingshot#167]
Node version:6.2.1

npm version:3.9.3

Operating system:Windows

Command line used:npm start

Steps to reproduce:

[BS] Serving files from: src

[npm-debug.txt](https://github.com/coryhouse/react-slingshot/files/319451/npm-debug.txt)
[BS] Watching files...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by coryhouse** [comment]
Node 6 has issues on Windows. I suggest installing 5.11.1

**Comment by nmganesh** [comment]
Thanks for immediate response. I was able to use the startup kit you had for Pluralsight course fine without any issues though. 


Thanks,

Ganesh

**Comment by coryhouse** [comment]
Hrmm. Interesting. Perhaps this would help? http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

**Comment by tfak** [comment]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'F:\tf\android\app\build\generated\source\r\debug\android\arch\core\R.java'
Emitted 'error' event at:
    at NodeWatcher.<anonymous> (F:\tf\node_modules\sane\src\node_watcher.js:306:14)
    at F:\tf\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:154:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Tf@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Tf@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tf\AppData\Roaming\npm-cache\_logs\2019-01-04T07_43_17_428Z-debug.log

F:\tf>npm -v
6.5.0

F:\tf>node -v
v10.15.0

**Comment by faraz08** [comment]
did you found the solution i am also facing the same issue
