### ISSUE TITLE
Port in use error

### ISSUE THREAD

**Issue by mrberggg** [coryhouse/react-slingshot#17]
I'm getting an error intermittently when running `npm run start`: `Error: listen EADDRINUSE :::3002`. It appears it's an error caused by that port being currently in use. If I rerun the command it usually works. Not a biggie, just an annoyance. If I knew what was going on I'd be happy to submit a PR. Thanks for your work, love this!

**Comment by coryhouse** [comment]
Yep, the most common scenario this happens is when you already have the starter kit running on another command line. Or, if the default port is conflicting with some other process on your machine, you can specify a different port. Add the following to the browserSync call in /tools/server.js:

browserSync({
  port: 9080,
  ui: {
    port: 9081
  },

**Comment by mrberggg** [comment]
I can't find any other processes running on that port which is what was confusing me. But I'll try changing the port, see if that fixes it. Thanks!

Oh and do you take feature requests? It'd be great to have connect-history-api-fallback or some HTML History config (i.e. support for SPA routing).

**Comment by nickytonline** [comment]
@mrberggg for routing, see issue #10.

**Comment by mrberggg** [comment]
Yeah, I saw that. Including it in the build step doesn't seem opinionated though (doesn't add any weight to final bundle) and it would save a lot of headache in setup. Anyhow, thanks for your work
