### ISSUE TITLE
Hash bundle name

### ISSUE THREAD

**Issue by vangelov** [coryhouse/react-slingshot#171]
Will it be better if the react and react-dom libraries are vendored into a separate bundle? There will be one more request, but they could be cached the first time and then only the app specific code will need to be re-downloaded when changed.

Also, why not add [hash] to the bundle name in order to easily invalidate cached code on changes?

**Comment by coryhouse** [comment]
Yep, both a good points. I'm not sure the former is worth the extra complexity, but I'd accept a pull request on adding a hash to the bundle name.

**Comment by vangelov** [comment]
Thanks for the fast response! I'll see what I can do.

**Comment by coryhouse** [comment]
I added this here: https://github.com/coryhouse/react-slingshot/commit/fdb0c42d84100b3f9419a9bb5d083934605e9f4a
