### ISSUE TITLE
Eslint issue

### ISSUE THREAD

**Issue by Akhil-Chauhan** [coryhouse/react-slingshot#175]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\All Projects\Z_Projects\MSEeLearning>npm run lint

> MSEeLearning@1.0.0 lint c:\All Projects\Z_Projects\MSEeLearning
> esw webpack.config.* src tools

'c:\All' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! MSEeLearning@1.0.0 lint: `esw webpack.config.* src tools`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MSEeLearning@1.0.0 lint script 'esw webpack.config.* src
tools'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the MSEeLearning package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs MSEeLearning
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls MSEeLearning
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\All Projects\Z_Projects\MSEeLearning\npm-debug.log

Node version:  6.2

npm version: 

Operating system: Window 7 64 bit

Command line used: 

Steps to reproduce: npm run lint 

Here is node.debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@3.9.3
3 info using node@v6.2.1
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle MSEeLearning@1.0.0~prelint: MSEeLearning@1.0.0
6 silly lifecycle MSEeLearning@1.0.0~prelint: no script for prelint, continuing
7 info lifecycle MSEeLearning@1.0.0~lint: MSEeLearning@1.0.0
8 verbose lifecycle MSEeLearning@1.0.0~lint: unsafe-perm in lifecycle true
9 verbose lifecycle MSEeLearning@1.0.0~lint: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\All Projects\Z_Projects\MSEeLearning\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Akhil\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Akhil\AppData\Roaming\npm
10 verbose lifecycle MSEeLearning@1.0.0~lint: CWD: c:\All Projects\Z_Projects\MSEeLearning
11 silly lifecycle MSEeLearning@1.0.0~lint: Args: [ '/d /s /c', 'esw webpack.config.* src tools' ]
12 silly lifecycle MSEeLearning@1.0.0~lint: Returned: code: 1  signal: null
13 info lifecycle MSEeLearning@1.0.0~lint: Failed to exec lint script
14 verbose stack Error: MSEeLearning@1.0.0 lint: `esw webpack.config.* src tools`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid MSEeLearning@1.0.0
16 verbose cwd c:\All Projects\Z_Projects\MSEeLearning
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
19 error node v6.2.1
20 error npm  v3.9.3
21 error code ELIFECYCLE
22 error MSEeLearning@1.0.0 lint: `esw webpack.config.* src tools`
22 error Exit status 1
23 error Failed at the MSEeLearning@1.0.0 lint script 'esw webpack.config.* src tools'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the MSEeLearning package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     esw webpack.config.* src tools
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs MSEeLearning
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls MSEeLearning
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by coryhouse** [comment]
Move your project to a path that doesn't contain spaces.
