### ISSUE TITLE
Does the webpack prod build exclude all spec.js files from bundle.js?

### ISSUE THREAD

**Issue by alikor** [coryhouse/react-slingshot#176]
Does the webpack prod build exclude all spec.js files from bundle.js?

**Comment by kwelch** [comment]
I believe it does because webpack only compile the files that are references via `require` or `import`. You can test this by creating a new file without referencing it and you should not see it in the list of source mapped files in your browser.

**Comment by coryhouse** [comment]
Well said @kwelch. Thanks!
