### ISSUE TITLE
Stage1/2

### ISSUE THREAD

**Issue by jondot** [coryhouse/react-slingshot#177]
Hi,
This commit:
https://github.com/coryhouse/react-slingshot/commit/94e49bcb45f2539191d8d58a2af8c1a3103a1d2c
Still relevant after this?
https://github.com/babel/babel-eslint/commit/5c1fd5a304349945306a0f89fe088607ea32ec01

Looks like a week of difference between these. I'm using `stage-2` on top of master, and not feeling anything broken.

**Comment by coryhouse** [comment]
Yes, that commit is still relevant. Moving to eslint-watch was about adding watch functionality to eslint. It's using plain eslint behind the scenes.
