### ISSUE TITLE
Add webpack-isomorphic-tools ?

### ISSUE THREAD

**Issue by chungchiehlun** [coryhouse/react-slingshot#18]
When implementing  server side rendering , I found [webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools) supplied a nice "template" component for server side rendering.

Some projects like [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) also adopted it. How about adding this ?

**Comment by coryhouse** [comment]
Since many people behind a login have no need for isomorphic rendering, I chose not to go isomorphic for this starter kit. But thanks for the suggestion!
