### ISSUE TITLE
npm start wants bundle.js on port 3000, while website started on first free port

### ISSUE THREAD

**Issue by svdoever** [coryhouse/react-slingshot#181]
Node version: 6.2.1

npm version: 3.9.3

Operating system: OSX

Command line used: npm start

Steps to reproduce: **npm start** seems to do everything, but when site starts up gives error in browser console window **Failed to load resource: the server responded with a status of 404 (Not Found) **http://localhost:3000/bundle.js**, but the site started at port 3004! Seems like link to **bundle.js** is hard-coded on port **3000**, while site starts up on next free port. I had another programming running that took up port 3000...

**Comment by coryhouse** [comment]
You can change the port by updating srcServer.js, distServer.js, and webpack.config.dev.js.

I haven't found a way to run at a dynamic port, but would love to see a pull request that handles it.

**Comment by svdoever** [comment]
Hi Cory, no problem... now I know I have to kill other apps taking port 3000. Might be good to take a completely different port i.e. 3918 or something like that, because most apps take port 3000:-) 

By the way: my compliments on your course on PluralSight!

**Comment by coryhouse** [comment]
Resolved with https://github.com/coryhouse/react-slingshot/commit/092151e6489b1d2c03bf0420fb3c84c5de50dc41
