### ISSUE TITLE
bundle.js returning HTML?

### ISSUE THREAD

**Issue by HoraceShmorace** [coryhouse/react-slingshot#190]
Node version: 4.2.1

npm version: 2.14.7

Operating system: OSX El Capitan v10.11

Command line used: npm start -s

Steps to reproduce: npm start -s

When I just run `npm start -s` and the demo opens in the browser, I get a page with a script tag that loads `http://localhost:3000/bundle.js`, which returns the main html document for the app. Huh? This, of course, gives me the console error: "bundle.js:1 Uncaught SyntaxError: Unexpected token <".

What simple and undoubtedly obvious thing am I missing?

**Comment by coryhouse** [comment]
Sorry, I don't understand your issue. When you type npm start, it should open this URL in your browser: localhost:3000.

That should therefore open index.html. 

Are you saying it's opening localhost:3000/bundle.js when you type npm start?

**Comment by HoraceShmorace** [comment]
No, bundle.js is returning an HTML doc.

**Comment by coryhouse** [comment]
Sorry, I'm not following. Can you please share your code so I can try to reproduce?

**Comment by HoraceShmorace** [comment]
Ugh. Never mind. I totally had another app already running on that port. I know... I'm the worst. :-P
