### ISSUE TITLE
image map require error

### ISSUE THREAD

**Issue by Hazantip** [coryhouse/react-slingshot#191]
Node version:
6.2.2
npm version:
3.9.0
Operating system:
win10
Command line used:
npm run start
Steps to reproduce:
map list with images. probplem with **image src={require(image)}**

`
const images = props.postcardImages.map((image, i) => {
		return (
			<li className="postcards-list-item"
				onClick={() => {props.setPostcardActiveImage(image);}}
				key={image + i}>
				<Link to="/postcard-edit">
					<img src={require(image)} alt=""/>
				</Link>
			</li>
		);
	});
`
image - string with image path. if i put just string(not variable) it works fine, but i need to map it. when i try to do this staff i get the error:
`
Uncaught Error: Cannot find module '../images/postcard.jpg'.(anonymous function) @ 
Uncaught TypeError: Cannot read property '__reactInternalInstance$f26nyhc5w3kdfida23zph9f6r' of null
`

**Comment by coryhouse** [comment]
Your syntax looks right to me, so I suspect the path you're referencing is invalid. That said, since this isn't an issue with React Slingshot working out of the box, I'm going to close and suggest using StackOverflow instead.

**Comment by Hazantip** [comment]
Path is correct. cause if i put it directly everything ok. just prolem if put variable to require =(

**Comment by coryhouse** [comment]
Try this: http://stackoverflow.com/questions/30485183/webpack-require-relative-image

**Comment by Hazantip** [comment]
Thaks, but unfortunately, it doesn't solve the problem..

**Comment by Hazantip** [comment]
Thats a really big problem, cause i can't create a production build without generated images.
