### ISSUE TITLE
Webpack development task not compiling

### ISSUE THREAD

**Issue by mckernanin** [coryhouse/react-slingshot#193]
Node version: v5.11.1

npm version: 3.10.6

Operating system: macOS Sierra Public Beta

Command line used: iTerm / zsh

Steps to reproduce:

- Clone project
- 'npm run setup'
- 'npm run remove-demo'
- Add simple code to index.js, here's what i'm using:

```
import React from 'react';
import {render} from 'react-dom';

render(
  <h1>Testing React Slingshot</h1>, document.getElementById('app')
);
```

If I run any of the production tasks, everything compiles correctly and works. Just running 'npm start' for development doesn't live reload any changes I make to the JS, and it doesn't compile on first run either.

**Comment by mckernanin** [comment]
I put my code in a repository here: https://github.com/mckernanin/reactzee

**Comment by mckernanin** [comment]
Odd. I cloned a copy from the repo I setup, and now hot reloading is working properly. I'm not sure what happened with my initial copy.

**Comment by coryhouse** [comment]
Very strange. Closing since it sounds like you're rolling.
