### ISSUE TITLE
The first test of the fuelSavingsReducer.spec.js does not test the setting of initial state

### ISSUE THREAD

**Issue by grotiusc** [coryhouse/react-slingshot#199]
The test states that the reducer "should set initial state by default" but state is passed into the reducer as part of the test. The result of this is that the default value in the reducer of `initialstate.fuelSavings` will not be used. If I remove the default value for initial state it will still pass.

If you remove the default value for the reducer, the build will break but the test still pass:

> Reducers::FuelSavings
>     √ should set initial state by default

Two options to make the test valid:
- The test wording should be changed to something like "should not alter the state if an action of unknown is used", or
- the value of `getInitialState()` should not be passed in

**Comment by coryhouse** [comment]
Good point. Fix committed: https://github.com/coryhouse/react-slingshot/commit/8c5a1736d3aa78c59025ddab49a21a53fff05547

Thanks!
