### ISSUE TITLE
Wrap this project inside a Yeoman Generator

### ISSUE THREAD

**Issue by arcseldon** [coryhouse/react-slingshot#20]
Hi Cory, 

Great starter project. Have you considered putting this inside a yeoman generator, and making options like whether you want a sample app included controllable from the yeoman command line?  You could also auto-populate other values like custom name of project etc etc.

Just a lot cleaner than git fork / clone and then hacking the codebase / removing redundant git remotes etc  :D  Like the use of package.json scripts - I was considering doing something very similar.

**Comment by coryhouse** [comment]
I totally agree. A friend of mine got a good running start going while at Codemash: https://github.com/dennisburton/generator-slingshot

I just haven't had a chance to do look it over in detail yet.

**Comment by arcseldon** [comment]
Thanks for the reply. Well, rapidly approaching 1500 stars so the evidence suggests people out there also like the github availability :+1: 

Mind you, for those familiar with yeoman, a quick addition to the readme pointing off at a yeoman generator alternative would be pretty slick.

Had your friend not already got this underway, I would have been happy to volunteer!  

Massive fan of avoiding all the repetitious boilerplate of getting started with project structure and builds.
In fact, I see opportunities everywhere for generators that just do away with it once and for all (on basis folks are happy with convention over configuration starting points).

Think more and more of the activities we train in today (technology) will go the way of commoditisation over time. Makes a lot of sense.  

Again thanks for a great slingshot - just what I was looking for. 

Suggestion only - Have you done a PR for [awesome-react(https://github.com/enaqx/awesome-react) - perhaps you should add this to the list of boilerplates / demos etc (if not already there).

**Comment by coryhouse** [comment]
I totally agree. The better our abstractions, the more we can focus on solving real problems. 

And yep, it was added to awesome-react yesterday. :)

**Comment by coryhouse** [comment]
I'm unclear about the best way to keep a Yeoman repo and this repo in sync. I obviously want to avoid having to push changes to both. Anyone have a link to share on how best to do this?

**Comment by kwelch** [comment]
So far this sounds like the only option. http://stackoverflow.com/a/18500003
Re-scaffold and verify diffs. Not overly safest and would be ideal if more simplistic. 

Also I would imagine a lot of the work will in this repo and ported to the generator. 

I do want to chime in that the generator will help specifically when you want to question what parts they want (ie. router, redux, ect.)

**Comment by coryhouse** [comment]
I totally agree that giving people an easy way to toggle on/off features is the big win. Here's the things I think would benefit from configuration:

1. Include Redux?
2. Include Router?
3. Include Mocha and Chai for tests?
4. Include the example app? <-this wouldn't be an option if 1 or 2 were false
5. Others I'm missing?

I've considered simply using Node to manipulate the source. A few scripts under tools could do the trick without requiring Yeoman.

**Comment by vrunjeti** [comment]
One of the features I liked from the Angular Yeoman generator was the ability to add new controllers and views from the terminal, which would create the new files in the appropriate directories and produce all the boilerplate code. It would be awesome if you could do the same with components with enough boilerplate to render `hello world` and an option to create its test file as well.

**Comment by kwelch** [comment]
One way I was thinking a Yeoman could be added and maintained would be to only update the generator as part of a release. Updates would stay have to take place in both, but would be minimized to stable points in the slingshot's history.

**Comment by coryhouse** [comment]
Good point and agreed.

**Comment by kwelch** [comment]
As an update to this, I believe we are more likely to use a `create-react-app` pattern and create a new package(`react-slingshot-scripts`).

**Comment by coryhouse** [comment]
Agreed @kwelch. That's the pattern I'm using at work now. Took awhile to get things wrapped, but now all our projects can be easily upgraded over time because they reference only a single npm package, which my team created and maintains. The package basically contains everything you see here in Slingshot, plus all our in-house components, plus a mock API, plus opinionated styling. Works well because we don't need to allow anyone to eject at work. I just add features/flexibility as needed. 

Thing is, when I created Slingshot it was unique. CRA came along and is quite similar, so not sure another wrapped-style starter would be sufficiently unique. Have to think about what we'd do differently to set it apart.

**Comment by nickytonline** [comment]
Since we're not going to pursue this I imagine this is OK to close? If we go the `react-slingshot-scripts` route, I would just create another issue.

**Comment by coryhouse** [comment]
Agreed. I prefer wrapping deps in an npm package like create-react-app does.
