### ISSUE TITLE
New flag "quiet: true" in tools/srcServer supress breaking errors

### ISSUE THREAD

**Issue by goncy** [coryhouse/react-slingshot#208]
Node version: v5.4.1

npm version: v3.3.12

Operating system: OSX El Capitan

Command line used: iTerm 2

Steps to reproduce: Use html-loader to point to a non existent file, run webpack, got Cannot get / and no errors on console, remove quiet flag, see error.

**Comment by coryhouse** [comment]
Can you share your code or a specific example I can reproduce?

**Comment by goncy** [comment]
Yes sure, if you use for example, html-loader, or some loader that breaks in case of a not found file, you could try: `src="../path/to/non/existent/file.jpg"` on a `img` tag. When you run npm start, you will get the `Cannot GET /` and no errors will show up on the terminal, remove the quiet flag and you will see the error.

PD: This also happened to me in several projects until y found the quiet flag was the problem

**Comment by goncy** [comment]
Error
<img width="301" alt="screen shot 2016-07-25 at 9 23 44 am" src="https://cloud.githubusercontent.com/assets/6494462/17101187/87d6c864-5249-11e6-9233-7f4385a938c4.png">

Quiet false
<img width="1313" alt="screen shot 2016-07-25 at 9 23 12 am" src="https://cloud.githubusercontent.com/assets/6494462/17101171/748dc122-5249-11e6-8f56-dc72b28f5d6b.png">

Quiet true
<img width="687" alt="screen shot 2016-07-25 at 9 24 47 am" src="https://cloud.githubusercontent.com/assets/6494462/17101228/c0be2d48-5249-11e6-8342-4be6f2286a51.png">

**Comment by coryhouse** [comment]
Ah! You're absolutely right. Great catch. I've just committed a change to set quiet to false so such errors display. Thanks! 👍 

Fix: https://github.com/coryhouse/react-slingshot/commit/97988d4c0669ca8304bee8e86ee69b32e6b931bf

**Comment by goncy** [comment]
I'm glad it helps, thanks for this repo, it's really helpful not only to start a project faster but to learn new things in each update.

PD: Love your courses on Pluralsight!
