### ISSUE TITLE
dist folder won't load unless served with distServer.js

### ISSUE THREAD

**Issue by jeongl** [coryhouse/react-slingshot#209]
I'm using express to serve this directory, but it fails for some reason. Intermittently it will flag an error reading the source maps. The three files (index.html, .js, and .css) load fine, but nothing is rendered on the page and DOM is empty.

What is different about the webpack server that allows it to load the site?

**Comment by coryhouse** [comment]
If it's not rendering, then you should see an error in your browsers console. What is the error?

**Comment by jeongl** [comment]
Failed to parse SourceMap: http://my-site/home/main.5d691417e8c237f32fd10b9a28ffb2f2.css.map

**Comment by coryhouse** [comment]
Can you share your solution on Github?

**Comment by jeongl** [comment]
I got it served with express - just my own error. Thanks for offering help.. and of course this repo.
