### ISSUE TITLE
Adding the Redux dev tools?

### ISSUE THREAD

**Issue by barrystaes** [coryhouse/react-slingshot#21]
I was wondering if there are plans to add [redux-devtools](https://github.com/gaearon/redux-devtools) because it looks useful. Or should i be fine without? Not sure if its bloat or not..

I'm no expert on redux, just giving it a spin.

**Comment by coryhouse** [comment]
I'm considering it but haven't had a chance to try them myself yet. If someone submits a PR I'd likely merge it.

**Comment by barrystaes** [comment]
I'm nowhere yet, but since you're interested: I followed their tutorial and made a (extremely minimalistic) start at https://github.com/barrystaes/react-slingshot/tree/feature-devtools

My next step would be "Exclude DevTools from Production Builds" but i'm not sure how to do that in react-slingshot without seperating the `webpack.config.js` and `configureStore.js` files into prod/dev versions. I'd be happy to hear your take on this.

**Comment by cuzzo** [comment]
@barrystaes,

Off the top of my head, you could look at webpack.hotModuleReplacementPlugin(). Then in `src/store/configureStore.js`, if module.reduxDevtools (or however you specify it) is defined, you could import the Devtool container, and then compose the reducers with Devtools.instrument(). Otherwise, do nothing.

Similarly, in  `src/containers/App.js`, you could check if module.reduxDevtools is set before adding it to the App.

Does that make sense?

**Comment by coryhouse** [comment]
@barrystaes The webpack.config.js in this project is actually a factory for a webpack config. You pass it an environment and it returns a config. So no separate file is necessary. 

Anyway, thanks Barry. I want to spend some time getting comfortable with the Redux devtools. Looks like you've got a great start.

**Comment by barrystaes** [comment]
Ok thanks! With your suggestions i completed my [feature-devtools](https://github.com/barrystaes/react-slingshot/tree/feature-devtools) branch. I kept the code minimal. 

Choices i made;
- A popup window instead of `redux-devtools-dock-monitor`. Less code, and stays out of the way of your UI.
- No `persistState()` added. Its usefull to reproduce bugs with `?debug_session=reproducing_weird_bug` but [thats easily added](https://github.com/gaearon/redux-devtools/blob/f53f660df2dd5af5e11aa40de176947cc187d140/README.md#use-devtoolsinstrument-store-enhancer).
- A prod/dev version for `configureStore.js` so that the debug module/component code is not included in production builds. Same goes for the window code in `src\index.js`.

Just clone and build, it works. Things i could improve on, before its ready for a PR?

**Comment by barrystaes** [comment]
I like to make this easy on you, so i just rebased it on your latest commit. 

And a screenshot for good measure: ![image](https://cloud.githubusercontent.com/assets/1420588/12418902/da66ba7e-beb2-11e5-9f99-17c7c0ae4c57.png)

**Comment by coryhouse** [comment]
Wow, this looks great! I'm eager to try it out! And yes, a PR would be great. :+1:

**Comment by barrystaes** [comment]
For posterity: PR #27 was not merged but i'll leave https://github.com/barrystaes/react-slingshot/tree/feature-devtools available for now.
