### ISSUE TITLE
404 on localhost:3000

### ISSUE THREAD

**Issue by mgavaudan** [coryhouse/react-slingshot#210]
Node version: 6.2.2

npm version: 3.9.5

Operating system: OS X El Capitan

Command line used: terminal

Steps to reproduce: removed demo and changed structure of files, project here: https://github.com/mgavaudan/react-hack

Problem: I'm getting a 404 when I run npm start and go to localhost:3000

This is the terminal output:

$ npm start -s
Starting app in dev mode...

  0 passing (1ms)

/Users/matthieugavaudan/Desktop/react-hack/webpack.config.dev.js (2/0)
  ✖  17:12  '__dirname' is not defined  no-undef
  ✖  38:39  '__dirname' is not defined  no-undef

/Users/matthieugavaudan/Desktop/react-hack/webpack.config.prod.js (2/0)
  ✖  21:12  '__dirname' is not defined  no-undef
  ✖  67:39  '__dirname' is not defined  no-undef

/Users/matthieugavaudan/Desktop/react-hack/src/components/Home.js (2/0)
  ✖  1:8   'React' is defined but never used      no-unused-vars
  ✖  1:28  'PropTypes' is defined but never used  no-unused-vars

/Users/matthieugavaudan/Desktop/react-hack/src/components/Patients.js (2/0)
  ✖  1:8   'React' is defined but never used      no-unused-vars
  ✖  1:28  'PropTypes' is defined but never used  no-unused-vars

/Users/matthieugavaudan/Desktop/react-hack/src/containers/App.js (7/0)
  ✖  1:8   'React' is defined but never used             no-unused-vars
  ✖  1:28  'PropTypes' is defined but never used         no-unused-vars
  ✖  2:8   'MuiThemeProvider' is defined but never used  no-unused-vars
  ✖  3:1   'injectTapEventPlugin' is not defined         no-undef
  ✖  3:24  'require' is not defined                      no-undef
  ✖  3:32  Strings must use singlequote                  quotes
  ✖  4:1   'injectTapEventPlugin' is not defined         no-undef

/Users/matthieugavaudan/Desktop/react-hack/src/containers/Home.js (5/0)
  ✖  1:8   'React' is defined but never used      no-unused-vars
  ✖  1:28  'PropTypes' is defined but never used  no-unused-vars
  ✖  2:8   'Home' is defined but never used       no-unused-vars
  ✖  2:33  Missing semicolon                      semi
  ✖  4:22  'Home' is already defined              no-redeclare

/Users/matthieugavaudan/Desktop/react-hack/src/containers/index.js (1/0)
  ✖  1:8  Parsing error: Unexpected token App

/Users/matthieugavaudan/Desktop/react-hack/src/containers/patients/PatientContainer.js (1/0)
  ✖  9:19  Parsing error: Unexpected token =

/Users/matthieugavaudan/Desktop/react-hack/src/containers/patients/patientReducers.js (1/0)
  ✖  2:3  Expected indentation of 1 tab character but found 0  indent

/Users/matthieugavaudan/Desktop/react-hack/src/index.js (4/0)
  ✖  3:8   'React' is defined but never used     no-unused-vars
  ✖  5:10  'Provider' is defined but never used  no-unused-vars
  ✖  6:10  'Router' is defined but never used    no-unused-vars
  ✖  9:1   'require' is not defined              no-undef

/Users/matthieugavaudan/Desktop/react-hack/src/reducers/index.js (2/0)
  ✖  6:3  Expected indentation of 1 tab character but found 0  indent
  ✖  7:3  Expected indentation of 1 tab character but found 0  indent

/Users/matthieugavaudan/Desktop/react-hack/src/routes.js (3/0)
  ✖  1:8   'React' is defined but never used       no-unused-vars
  ✖  2:10  'Route' is defined but never used       no-unused-vars
  ✖  2:17  'IndexRoute' is defined but never used  no-unused-vars

/Users/matthieugavaudan/Desktop/react-hack/src/store/configureStore.dev.js (9/0)
  ✖   9:3   Expected indentation of 1 tab character but found 0  indent
  ✖  15:3   Expected indentation of 1 tab character but found 0  indent
  ✖  15:7   'module' is not defined                              no-undef
  ✖  17:5   Expected indentation of 1 tab character but found 0  indent
  ✖  17:5   'module' is not defined                              no-undef
  ✖  18:7   Expected indentation of 1 tab character but found 0  indent
  ✖  18:27  'require' is not defined                             no-undef
  ✖  19:7   Expected indentation of 1 tab character but found 0  indent
  ✖  23:3   Expected indentation of 1 tab character but found 0  indent

/Users/matthieugavaudan/Desktop/react-hack/src/store/configureStore.js (7/0)
  ✖  1:5   'process' is not defined                             no-undef
  ✖  2:3   Expected indentation of 1 tab character but found 0  indent
  ✖  2:3   'module' is not defined                              no-undef
  ✖  2:20  'require' is not defined                             no-undef
  ✖  4:3   Expected indentation of 1 tab character but found 0  indent
  ✖  4:3   'module' is not defined                              no-undef
  ✖  4:20  'require' is not defined                             no-undef

/Users/matthieugavaudan/Desktop/react-hack/src/store/configureStore.prod.js (1/0)
  ✖  5:3  Expected indentation of 1 tab character but found 0  indent

/Users/matthieugavaudan/Desktop/react-hack/tools/build.js (1/0)
  ✖  8:1  'process' is not defined  no-undef

/Users/matthieugavaudan/Desktop/react-hack/tools/testSetup.js (4/0)
  ✖  12:1  'process' is not defined                             no-undef
  ✖  17:3  Expected indentation of 1 tab character but found 0  indent
  ✖  17:3  'require' is not defined                             no-undef
  ✖  22:1  'require' is not defined                             no-undef

✖ 54 errors (9:24:22 PM)
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.3:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.3:3001
 ------------------------------------
[BS] Serving files from: src
[BS] Watching files...
webpack built 8b4c7cf561c8bb127f85 in 3211ms
ERROR: "lint:watch" exited with 1.

Thanks for your help!!

**Comment by coryhouse** [comment]
You need to fix all the linting errors. That's killing the build.

**Comment by mgavaudan** [comment]
Hello @coryhouse , thanks for the fast reply! How am I supposed to fix this error though?

/Users/matthieugavaudan/Desktop/react-hack/webpack.config.dev.js (2/0)
✖ 17:12 '__dirname' is not defined no-undef
✖ 38:39 '__dirname' is not defined no-undef

In your webpack.config you don't define it either :/

**Comment by coryhouse** [comment]
You have dozens of linting errors so you've clearly changed the project. I'd suggest diffing with Slingshot. Sorry, I don't have time to step through at this time.
