### ISSUE TITLE
Moving the index.js file from the reducers folder to the store folder causes a 404

### ISSUE THREAD

**Issue by mgavaudan** [coryhouse/react-slingshot#211]
Node version: 6.2.2

npm version: 3.9.5

Operating system: OS X El Capitan

Command line used: terminal

Steps to reproduce: Moving the index.js file from the reducers folder to the store folder causes a 404 when getting localhost:3000. This is of course after changing all the imports to match the new structure. No errors appear in the console either (lint or otherwise)

**Comment by coryhouse** [comment]
To clarify, index.js belongs in the reducers folder because it's the root reducer. That said, since this isn't an issue with Slingshot working out of the box, it's a better question for StackOverflow.
