### ISSUE TITLE
Why BrowserSync in production distServer.js?

### ISSUE THREAD

**Issue by ruler88** [coryhouse/react-slingshot#215]
Is there any benefit to using BrowserSync in production? 
Seems like distServer.js is wrapping the app in BrowserSync. I thought BrowserSync is only good for development testing.

**Comment by coryhouse** [comment]
Ah, good question. I can appreciate the confusion. 

distServer isn't for use in production. It's for serving up the production build on your local machine so you can confirm it looks good before deployment. 

For production, you'd use a real webserver to serve the static files. NGINX, Apache, IIS, etc.

**Comment by ruler88** [comment]
Ah that makes perfect sense, thanks!
