### ISSUE TITLE
Deploy to github pages

### ISSUE THREAD

**Issue by nbrohee** [coryhouse/react-slingshot#218]
Rather than deploying to a cloud vendor website, I tried to deploy to github pages.
[Here](https://github.com/nbrohee/react-slingshot/commit/3a42ea0da8d4645e39070212b2f9cc5a9acf9d4a) are my changes to do so with a live version accessible [here](https://nbrohee.github.io/react-slingshot/)
I had to remove the publicPath in webpack.config.prod.js as github pages serves the site in a subdomain.

Almost everything works as intended except for the rooting (I think) behaving weirdly.
As you can see [here](https://nbrohee.github.io/react-slingshot/) :

- the app lands on the 404 page instead of the default one
- navigation replaces the subdomain instead of appending the route path to it.

I know React-slingshot is meant to be served from the website root but any help would be appreciated.

Could be a similar issue to #214

**Comment by kwelch** [comment]
The 404 page is due to gh-pages not the slingshot. See https://github.com/facebookincubator/create-react-app/pull/162#issuecomment-236222029 for notes on SPA in GitHub pages. This also causes issues with `browserHistory` from `react-router` which we have enable by default.

**Comment by nbrohee** [comment]
Thanks you for your quick answer !
Your link pointed me in the right direction to [spa-github-pages](https://github.com/rafrex/spa-github-pages/) repository.
Everything is explained in his [readme usage section](https://github.com/rafrex/spa-github-pages/#usage-instructions).

**Comment by coryhouse** [comment]
Thanks for the help on this @kwelch ! :+1:
