### ISSUE TITLE
Npm security warnings

### ISSUE THREAD

**Issue by mattdufeu** [coryhouse/react-slingshot#219]
Node version:
6.2.1

npm version:
3.9.3

Operating system:
Windows Server 2012 R2

Command line used:
npm run setup

Steps to reproduce:
Clone the repo
npm run setup.

I get the following security warnings:

npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

And the following non-security related warnings:

npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

Are they anything to be particularly worried about?

**Comment by coryhouse** [comment]
Like any security warning, you'll have to read the fine print and consider how you're using the dependency to determine if it applies to you. And of course, the cookie warning would only apply if you're using the related package to parse cookies.

To find the related package, open node_modules/tough-cookie and view this:

  "_requiredBy": [
    "/jsdom",
    "/request"
  ],

That said, I just updated all packages to the latest version, so I believe this warning is now spurious. If you get latest, you should be running the newer patched version. Running node security check on the latest release produces no warnings.

More info: https://nodesecurity.io
