### ISSUE TITLE
Question: deep-linking without a server in distributed app?

### ISSUE THREAD

**Issue by mattdufeu** [coryhouse/react-slingshot#225]
Not sure if I have the terminology correct. I read a few related issues and it sounded like this should work. Maybe I'm wrong?

I ran "npm run build" and deployed the dist folder to a webserver. The demo app works fine if I browse to http://<domain>.

However, I can't go to http://<domain>/about. I get a HTTP 500 error.

Is there a way to get deep linking to work without deploying an express (or equivalent) server?

**Comment by kwelch** [comment]
You need to ensure that all pages redirect to index.html, that way the bundle.js is handling the routing. This can be done a few different ways depending on the webserver. 

What is the server type?

**Comment by mattdufeu** [comment]
I don't know exactly as it's my hosts server, but it appears to be an apache server.

It's deployed to a sub-domain, so could I drop a .htaccess file in there with a redirect to index.html?

**Comment by kwelch** [comment]
Yes that is exactly what I was going to recommend. Closing, I can reopen if it persists.
