### ISSUE TITLE
[Enhancement] Add a config option to toggle hot reloading

### ISSUE THREAD

**Issue by ericgrosse** [coryhouse/react-slingshot#228]
One of the major issues with hot reloading is that it doesn't relaunch the actions from componentDidMount and other lifecycle methods. If you often load data through AJAX requests in componentDidMount as the official React docs recommend, then hot reloading becomes basically useless since you're forced to manually reload the page to properly initialize it.

Obviously hot reloading still has its uses. If you mostly edit decorator components or are making CSS styling changes, hot reloading is clearly superior to full reloads.

So why not have the best of both worlds and make hot reloading toggle-able? All it would require is a config file with a boolean you can set to true or false, and in one line of code you can change the reloading setup to suit your needs.

I would be happy to make a pull request for this if there's enough interest, it's rather trivial to implement honestly. Aside from adding a few

`if (config.hotReloadingEnabled) {...}`

conditionals to wrap code blocks related to hot reloading, you just need to make browserSync watch for js files.

**Comment by coryhouse** [comment]
What is the downside to hot reloading always being enabled? If it is enabled and doesn't work, you hit refresh. If it's not enabled, you hit refresh. So in either case, you simply hit refresh as necessary. But by disabling it, you're choosing to **always** have to hit refresh. Is that a win?

Bottom line, it doesn't always work, so people have to understand to refresh manually when that occurs. 

One other thought  - React Hot Loader 3 is in beta. I wonder if it will resolve these issues.

**Comment by ericgrosse** [comment]
> But by disabling it, you're choosing to always have to hit refresh.

It seems I forgot to mention, the idea is when hot reloading is disabled, you enable **full reloading**. At that point, any change you make to your component causes an entire page refresh.

**Comment by kwelch** [comment]
I am using hot loader beta 4 and hrme, and it is quite stable. It works on stateless/functional and CssModules.

**Comment by coryhouse** [comment]
Given that it's trivial to disable if not desired, I'd like to just leave it as is. We can discuss again when React Hot Loader comes out of beta.
