### ISSUE TITLE
warnings and unsupported packages when installing

### ISSUE THREAD

**Issue by dancinglone** [coryhouse/react-slingshot#229]
Node version: v4.4.7

npm version: cnpm v4.3.7

Operating system:windows

Command line used: cmd

Steps to reproduce: cnpm i

1.
[tough-cookie@2.2.2](.\node_modules\.2.65.0@request\node_modules\tough-cookie) deprecate: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

2.
[has-color@0.1.7](.\node_modules\.0.4.0@chalk\node_modules\has-color) deprecate: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color

3.
[fsevents@1.0.14](.\node_modules\.1.6.0@chokidar\node_modules\fsevents) unsupported: Package require os(darwin) not compatible with your platform(win32)

4.
[minimatch@2.0.10](.\node_modules\.0.2.1@fileset\node_modules\minimatch) deprecate: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

5.
[minimatch@0.2.14](.\node_modules\.0.3.0@replace\node_modules\minimatch) deprecate: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue.

**Comment by kwelch** [comment]
Have you pulled latest? This was addressed in the discussion thread for #219

**Comment by dancinglone** [comment]
the author updated the package.json five days ago, and i download the zip here yesterday, so it's already the latest version.

**Comment by kwelch** [comment]
Agreed, I am getting 1,4,5. I am not getting 3 because I am not on windows, and I am unsure on 2. 

That being said these are not warning that are coming from direct dependancies and I defer to the discussion in the issue mention above.

**Comment by coryhouse** [comment]
Since these aren't direct dependencies, the only thing we can do is update when our dependencies are updated. So I just did that again for good measure. That said, these sorts of warnings are to be expected when working with many npm packages, so closing.
