### ISSUE TITLE
Suggestion: Update non-pure components to pure components

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#23]
@coryhouse There are two components in your sample app that are not pure components that could be. I'll create a PR and let me know what you think.

**Comment by nickytonline** [comment]
@coryhouse, if you don't like the [route I took to build the functions](https://github.com/nickytonline/react-slingshot/commit/e409c6180506b2480050467ec54903c0d217c590#diff-0d94ee5cbbd68ec796ce79a1f8a331f7R24), I can put them inline in the pure component as they will have access to ```props```, e.g.
```
const FuelSavingsCalculatorForm = (props) => {
...
	function fuelSavingsKeypress(name, value) {
		props.actions.calculateFuelSavings(props, name, value);
	}
...
}
```

**Comment by coryhouse** [comment]
Already merged so we're all set. Thanks again!
