### ISSUE TITLE
Include redux-sagas

### ISSUE THREAD

**Issue by iLeonelPerea** [coryhouse/react-slingshot#234]
Hi, I implemented redux-sagas on my own project and mock server using drackov.. 

I can help with a pr with redux-sagas, may be ok to implement it? 

what do you think?

**Comment by coryhouse** [comment]
There are many options in this space so I'm not sold having an opinion on this makes much sense. There's a separate thread where people are arguing for adding redux thunk, but I lean toward just letting people pick what they like. That said, thanks for the offer! 👍
