### ISSUE TITLE
Removing connect-history-api-fallback breaks npm start

### ISSUE THREAD

**Issue by jboxman** [coryhouse/react-slingshot#235]
(Restoring the modules fixes the issue.)

After running

`npm uninstall --save react-router connect-history-api-fallback`

I throw a stack trace on `npm start`

`
$ npm start

> react-slingshot@5.0.0 prestart /Users/jasonb/projects/lb-take-2
> npm-run-all --parallel start-message remove-dist

> react-slingshot@5.0.0 start-message /Users/jasonb/projects/lb-take-2
> babel-node tools/startMessage.js

> react-slingshot@5.0.0 remove-dist /Users/jasonb/projects/lb-take-2
> rimraf ./dist

Starting app in dev mode...

> react-slingshot@5.0.0 start /Users/jasonb/projects/lb-take-2
> npm-run-all --parallel test:watch open:src lint:watch

> react-slingshot@5.0.0 lint:watch /Users/jasonb/projects/lb-take-2
> npm run lint -- --watch

> react-slingshot@5.0.0 test:watch /Users/jasonb/projects/lb-take-2
> npm run test -- --watch

> react-slingshot@5.0.0 open:src /Users/jasonb/projects/lb-take-2
> babel-node tools/srcServer.js

> react-slingshot@5.0.0 lint /Users/jasonb/projects/lb-take-2
> esw webpack.config.* src tools --color "--watch"

> react-slingshot@5.0.0 test /Users/jasonb/projects/lb-take-2
> mocha tools/testSetup.js "src/**/*.spec.js" --reporter progress "--watch"

  0 passing (1ms)

module.js:442
    throw err;
    ^

Error: Cannot find module 'connect-history-api-fallback'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at startServer (/Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/server.js:70:13)
    at Object.module.exports.startServer [as fn] (/Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/async.js:91:41)
    at /Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/UI.js:184:14
    at iterate (/Users/jasonb/projects/lb-take-2/node_modules/async-each-series/index.js:8:5)
    at /Users/jasonb/projects/lb-take-2/node_modules/async-each-series/index.js:16:16
    at /Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/UI.js:192:13
    at Object.module.exports.setUrlOptions [as fn] (/Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/async.js:72:9)
    at /Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/UI.js:184:14
    at iterate (/Users/jasonb/projects/lb-take-2/node_modules/async-each-series/index.js:8:5)
    at /Users/jasonb/projects/lb-take-2/node_modules/async-each-series/index.js:16:16
    at /Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/UI.js:192:13
    at Object.module.exports.setBsOptions [as fn] (/Users/jasonb/projects/lb-take-2/node_modules/browser-sync-ui/lib/async.js:47:9)

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "run-script" "open:src"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@5.0.0 open:src: `babel-node tools/srcServer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 open:src script 'babel-node tools/srcServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node tools/srcServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jasonb/projects/lb-take-2/npm-debug.log
ERROR: "open:src" exited with 1.

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@5.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-slingshot@5.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel test:watch open:src lint:watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jasonb/projects/lb-take-2/npm-debug.log
`

**Comment by coryhouse** [comment]
I'm confused. You uninstalled something that's still referenced in code, which of course causes a bug. Are you proposing a change of some sort?

**Comment by jboxman** [comment]
It's been that kind of week. I actually executed the commands below:

```
git clone https://github.com/coryhouse/react-slingshot.git blah
cd blah/
npm i
npm run
npm run remove-demo
```

And then added a hello world.

```
cat src/index.js

import React from 'react';
import { render } from 'react-dom';

render(
<h1>Hi</h1>,
document.getElementById('app')
)

```

And `npm run` works.

```
npm uninstall --save react-router connect-history-api-fallback
```

Now it does not.

The FAQ suggested react-router can be removed by following the above step and then removing any reference to react-router, which removing the sample app takes care of automatically.

connect-history-api-fallback is also referenced in srcServer.js, but removing those references has no effect.

Additional modules in node_modules seem to use connect-history-api-fallback though.

I'm not at all familiar with connect-history-api-fallback, but maybe

https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md

should only suggest removing react-router by itself? That fixes my issue. So this is a documentation change request, then.

**Comment by kwelch** [comment]
You mentioned you removed it from `srcServer.js` did you also remove from `distServer.js`

**Comment by jboxman** [comment]
No, but `npm start` never calls distServer.js.

If I `npm i --save connect-history-api-fallback` all is well again.

I can update the FAQ and submit a PR.

**Comment by kwelch** [comment]
Yeah, I agree it does seem odd that you can't remove that. I am going to
take a look because nothing should be that attached.

**Comment by kwelch** [comment]
@jboxman 

I ran your exact steps and was able to repro. However, after clearing the `node_modules` directory and then doing a new `npm install` I was able to fix the issue. 

I agree an update to the FAQ would be valid is this case, not sure why browsersync is holding on to that package.
