### ISSUE TITLE
Linter returns "No default export found in module" for configureStore.js

### ISSUE THREAD

**Issue by nowinskp** [coryhouse/react-slingshot#237]
Node version: 6.3.1
npm version: 3.10.3
Operating system: Ubuntu 16.04 LTS
Command line used: Terminal

Steps to reproduce:
The default config returns an error while linting, pointing to file configureStore,js. The error is:
`✖  12:8  No default export found in module  import/default`
pointing to line:
`12: import configureStore from './store/configureStore';`

I guess the problem is the `if` statement in said file:
```
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./configureStore.prod');
} else {
  module.exports = require('./configureStore.dev');
}
```
and the fact that there's no `default` statement placed in it directly.

Any idea how to fix it?

**Comment by coryhouse** [comment]
It sounds like you have altered the kit. This rule is disabled in index.js to supress this error.

https://github.com/coryhouse/react-slingshot/blob/master/src/index.js#L1

**Comment by nowinskp** [comment]
Thanks Cory, you're right - I accidentally removed that line when I was pasting initial config from a separate file. All's working fine now.
