### ISSUE TITLE
Integrate ReduxForms

### ISSUE THREAD

**Issue by tutuca** [coryhouse/react-slingshot#239]
Seems like all it needs to properly integrate [ReduxForms](http://redux-form.com/) is:

    import { reduxForm } from 'redux-form'
    ....
    export default reduxForm({
      form: 'simple',
      fields
    })(FuelSavingsForm)

Is there some ongoing discussion on which library to use for form validation? Will there be interest in some PR for this?

**Comment by coryhouse** [comment]
Hi @tutuca - Thanks for the idea, but I'd rather not take a dependency on doing forms. React with Redux handle it quite nicely as is, and as you've shown, it's trivial to add if desired.
