### ISSUE TITLE
Reducers should be pure functions

### ISSUE THREAD

**Issue by samit4me** [coryhouse/react-slingshot#240]
In the example reducer *fuelSavingsReducer.js*, it is updating the property **dateModified** with a `new Date()`. 

This does not prevent it from working, but it will give some strange results when using the time travelling feature of Redux (e.g dateModified will be different).

> Things you should never do inside a reducer:
> * Mutate its arguments;
> * Perform side effects like API calls and routing transitions;
> * Call non-pure functions, e.g. Date.now() or Math.random().

http://redux.js.org/docs/basics/Reducers.html#handling-actions

A possible solution would be to pass the **dateModified** as an argument from the action creator `saveFuelSavings()` something like this:

```Javascript
dispatch({
  type: types.SAVE_FUEL_SAVINGS,
  dateModified: dateHelper.getFormattedDateTime(new Date()),
  settings,
})
```

**Comment by coryhouse** [comment]
Excellent point! Would you be willing to submit a pull request?

**Comment by samit4me** [comment]
Sure no problems

**Comment by coryhouse** [comment]
Nothing formal required - branch and then submit the PR. Thanks in advance!
