### ISSUE TITLE
Inspect Element Sources shows webpack:// and all the files inside on "dist" build

### ISSUE THREAD

**Issue by harshmaur** [coryhouse/react-slingshot#242]
Hello, 

I am not sure if it is supposed to be like this or not, but after deploying the dist folder to my nginx server, I can see all my files in the webpack:// directory in my chrome browser source tab. 

Please have a look at the screenshot. 
<img width="1237" alt="screen shot 2016-08-20 at 9 34 53 pm" src="https://cloud.githubusercontent.com/assets/12210058/17832340/00172722-671e-11e6-8a66-17970fcb138f.png">

**Comment by coryhouse** [comment]
That's the beauty of sourcemaps. Chrome is parsing the sourcemaps so you can debug your original source code.

**Comment by harshmaur** [comment]
Got it. I will use hidden-source-map devtool to hide when I dont want to show it. 

Thanks!
