### ISSUE TITLE
Anyone using webpack-dashboard?

### ISSUE THREAD

**Issue by AlexEscalante** [coryhouse/react-slingshot#247]
I just found this project, [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) and it looks very appealing, but integrating it into a react-slingshot project doesn't seem straightforward:

[compatibility with babel --watch #70](https://github.com/FormidableLabs/webpack-dashboard/issues/70)

Is anyone here using this succesfully?

**Comment by kwelch** [comment]
My team has this working on a forked version of slingshot. We have it setup using the ["old way"](https://github.com/FormidableLabs/webpack-dashboard#use-the-old-way) instructions, through webpack config.

**Comment by AlexEscalante** [comment]
@kwelch, thanks for the pointer! I'll look into this…
