### ISSUE TITLE
Browsersync really needed in production?

### ISSUE THREAD

**Issue by iLeonelPerea** [coryhouse/react-slingshot#253]
Hii everyone. 

I wan to deploy to production and use nginx, but have some questions:

I think that is not a good idea use browsersync which other tool i can use? i saw an implementation of WebpackDevServer but i don't know if is the better.

Tnks

**Comment by coryhouse** [comment]
nginx (or some other prod webserver like Apache, IIS, etc) is all you need in prod. You're right, browsersync isn't intended for prod.

**Comment by iLeonelPerea** [comment]
So, is not necessary to use something like express to serve the dist folder?

because in the code generated into dist doesnot works the historyApiFallback.. I tried add this to the webpack.config.prod.

`devServer: {
    historyApiFallback: true
  }`

**Comment by kwelch** [comment]
If you are using Apache or IIS you need to configure the server to only server the `index.html`, thus not needing an express server.
