### ISSUE TITLE
Debugging is broken in development mode when using cheap-module-eval-source-map

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#255]
In Chrome, I'm seeing nothing but this when trying to hit a breakpoint when using cheap-module-eval-source-map:

/*\* WEBPACK FOOTER **
 *\* 
 **/

Changing the devtool setting from cheap-module-eval-source-map to eval-source-map fixes this (which I just committed for now), but I'd like to switch back to the former since it's faster.

This issue seems related: https://github.com/webpack/webpack/issues/2145

**Comment by cds-amal** [comment]
Hi Cory,

This one kicked my butt as I was trying to follow along with your PS course. Just adding eval-source-map didn't work for me, I had to add new webpack.EvalSourceMapDevToolPlugin() to move along with the course. BTW, LOVE the course, Thank you so much for putting out great content, along with this react-slingshot

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
    ,new webpack.EvalSourceMapDevToolPlugin()
  ],

 (great course btw! 5 stars).

**Comment by hcngo** [comment]
Hi Cory,
I got the same issue with the cheap-module-eval-source-map when following react-redux course on Pluralsight. Changing the devtool to eval-source-map and adding new webpack.EvalSourceMapDevToolPlugin() make the debugger work. 

Thanks cds-amal for the plugin suggestion.

**Comment by ericgrosse** [comment]
I'm getting this issue too, and only very recently.

console logs are showing up at `?d41d:6` instead of the relevant source file

Switching to `eval-source-map` as Cory House suggested worked for me, slight bummer that rebundles probably take slightly longer as a result until this gets resolved

**Comment by Inlesco** [comment]
^ I've just encoutered this issue, too. I cloned the newest version of Slingshot and compared the webpack config to my version and found the solution. All works now.

**Comment by dancinglone** [comment]
I come across this issue too. Thanks for your ideas.

**Comment by kwelch** [comment]
There have been some updates on the parent ticket. This may be resolved and available for re-testing.

**Comment by nickytonline** [comment]
Looks like this is supposed to be fixed, but from the Chrome side, not webpack, https://github.com/webpack/webpack/issues/2145#issuecomment-325441145

**Comment by coryhouse** [comment]
Good point - Just pulled down and confirmed it works. Closing!
