### ISSUE TITLE
react-router Link rendering in production build

### ISSUE THREAD

**Issue by raythree** [coryhouse/react-slingshot#256]
This is not likely a slingshot issue, but I figured I'd ask here in case anyone else encountered it. I just encountered an issue only with the production build. My routes look like this, the only difference is that the production path will be different:

```javascript
let rootPath;
if (process.env.NODE_ENV === 'production') {
  rootPath = "/ui/app/";
}
else {
  rootPath = "/";
}

let routes = (
  <Route path={rootPath} component={App}>
    <IndexRoute component={HomeContainer}/>
      <Route path="home" component={HomeContainer}/>
      <Route path="uploads" component={UploadsContainer}/>
      <Route path="downloads" component={DownloadsContainer}/>
      <Route path="*" component={NotFound}/>
   </Route>
);
```
The App render is like:
```javascript
    return (
      <div>
        <AppHeader logo={logo} name={this.props.user.name} logout={this.props.logout}/>
        <div className="container-fluid">
          <Navbar>
            <NavbarItem name="home" link="boxes">Home</NavbarItem>
            <NavbarItem name="uploads" link="uploads">Uploads</NavbarItem>
            <NavbarItem name="downloads" link="downloads">Downloads</NavbarItem>
          </Navbar>
          {this.props.children}
        </div>
      </div>
    );
```
The NavbarItems just render Links like ```<Link to="uploads">```.  Everything works fine in the dev build from the dev server.

For production the distribution is served behind an nginx server at the public path above. Clicking on the links there *does* change the address in the browser, but no rendering occurs. For example, if I was on "/ui/app/home" and the downloads link is clicked, the URL address properly changes to "/ui/app/downloads" but the HomeContainer is still shown. However, If I then do a full-page refresh nginx will serve up the whole page again, and react-router checks the location and then properly displays the DownloadContainer, so I know the URLs are correct. 

I should also note that the publicPath is also set correctly in webpack.config.prod.js.

Thanks.

**Comment by raythree** [comment]
I should also note that the publicPath is also set correctly in ```webpack.config.prod.js```.

**Comment by sgehrig** [comment]
@raythree Just hit the same problem. Did you solve your issue? If so, how?

**Comment by scotartt** [comment]
yes please supply the solution when you close the ticket!
