### ISSUE TITLE
Question regarding HMR for reducers

### ISSUE THREAD

**Issue by nowinskp** [coryhouse/react-slingshot#257]
I'm changing file structure of my app so I have a question regarding hot module replacement for redux reducers.

If I decide to move my rootReducer outside of `src/reducers/` and rename it, so it's placed in `src/modules/` as `rootReducer.js`, how should I update the configureStore.dev.js part regarding HMR?

Right now it's:
```
module.hot.accept('../reducers', () => {
	const nextReducer = require('../reducers').default;
	store.replaceReducer(nextReducer);
});
```
So is this correct:
```
module.hot.accept('../modules/rootReducer', () => {
	const nextReducer = require('../modules/rootReducer').default;
	store.replaceReducer(nextReducer);
});
```
how it should look like now?

I made a quick test and it looks like it's working fine - I just want a confirmation that I'm not missing something here - thanks. :)

**Comment by kwelch** [comment]
Yes, that would be the correct change. 

To explain it further, `module.hot.accept`based on changes in the module imported as the first param. The second is a callback of what to do once that change has been made. 

It functions similar(if not exactly) to webpack code splitting which is done through `require.ensure`

[Here are the docs](https://webpack.github.io/docs/code-splitting.html) on that.

**Comment by nowinskp** [comment]
Thank you, @kwelch!
