### ISSUE TITLE
Debugging with VSCode

### ISSUE THREAD

**Issue by cristian-eriomenco** [coryhouse/react-slingshot#259]
First of all I want to give many respects to the authors and contributors, the setup is simply amazing and what a real world requires.

Taking a step further I know we can use chrome dev tools for debugging, but IMHO would be very nice to have the debugger setup to be working on VSCode (although people might be using other editor). 

There are already some attempts out there:
1. https://github.com/skolmer/react-hot-boilerplate-vscode
2. https://github.com/Microsoft/vscode-chrome-debug
3. http://stackoverflow.com/questions/31711286/vscode-debug-es6-application
4. https://gist.github.com/dchowitz/83bdd807b5fa016775f98065b381ca4e

Still they feel tied to the specifics of their own setup. 
I've tried to get it working but seems that my knowlegde is not good enough. 

So if this request seems sensible for the community please upvote it, or at least express your thoughts upon.

Thanks!

**Comment by nickytonline** [comment]
@cristian-eriomenco, have you tried following the steps outline here? https://code.visualstudio.com/blogs/2016/02/23/introducing-chrome-debugger-for-vs-code

**Comment by nickytonline** [comment]
@cristian-eriomenco, are you still having issues with debugging in VS Code?

**Comment by kwelch** [comment]
If there were any changes made that were needed to get it working, it would be awesome to see a PR that add it is or adds documentation on the steps necessary.

**Comment by nickytonline** [comment]
@kwelch, I'll take a look at this this weekend.

**Comment by nickytonline** [comment]
@cristian-eriomenco, I can confirm that with the Chrome Debugger for VS Code which I suggested using above, you cannot  debug react-slingshot in VS Code. Just investigating why.

**Comment by nickytonline** [comment]
@cristian-eriomenco, cancel that. It does work. I had the wrong port configured. Here's is a sample launch.json file for debugging in VS Code.

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}"
    },
    {
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}"
    }
  ]
}
```

and just ensure to launch Chrome as explained in the Chrome Debugger extension docs I mentioned above, i.e.

Windows
Right click the Chrome shortcut, and select properties
* In the "target" field, append --remote-debugging-port=9222
* Or in a command prompt, execute <path to chrome>/chrome.exe --remote-debugging-port=9222

OS X
* In a terminal, execute /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

Linux
* In a terminal, launch google-chrome --remote-debugging-port=9222

@kwelch, @coryhouse I can update the read me if you like with the above, or we can just point to the Chrome Debugger extension readme which pretty much explains what I mention in this comment.

**Comment by coryhouse** [comment]
Good stuff. 👍  I suggest just linking to their docs if they're sufficiently thorough.

**Comment by nickytonline** [comment]
@coryhouse, will do.
