### ISSUE TITLE
Production build fails after latest webpack config change

### ISSUE THREAD

**Issue by siggirh** [coryhouse/react-slingshot#261]
Node version: 6.5.0
npm version: 3.10.3
Operating system: Windows 10
Command line used: git bash
Steps to reproduce:
1. npm run setup
2. npm run build

`sr@nsa ~/repo/react-slingshot
$ npm run build

> test@0.0.1 prebuild C:\Users\sr\repo\react-slingshot
> npm run clean-dist && npm run lint && npm run test

> test@0.0.1 clean-dist C:\Users\sr\repo\react-slingshot
> npm run remove-dist && mkdir dist

> test@0.0.1 remove-dist C:\Users\sr\repo\react-slingshot
> rimraf ./dist

> test@0.0.1 lint C:\Users\sr\repo\react-slingshot
> esw webpack.config.* src tools --color

✓ Clean (8:25:24 PM)

> test@0.0.1 test C:\Users\sr\repo\react-slingshot
> mocha tools/testSetup.js "src/**/*.spec.js" --reporter progress

  [▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬]

  54 passing (247ms)

> test@0.0.1 build C:\Users\sr\repo\react-slingshot
> babel-node tools/build.js && npm run open:dist

Generating minified bundle. This will take a moment...
Webpack stats: Hash: 99b1388f3fbce5428ee4
Version: webpack 1.13.2
Time: 707ms
     Asset       Size  Chunks             Chunk Names
index.html  189 bytes          [emitted]

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' C:\src\index in C:\Users\sr\repo\react-slingshot
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  547 kB       0
    chunk    {0} index.html 529 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.ejs 2 kB {0} [built]
        [1] ./~/lodash/lodash.js 527 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
Your app is compiled in production mode in /dist. It's ready to roll!

> test@0.0.1 open:dist C:\Users\sr\repo\react-slingshot
> babel-node tools/distServer.js

Opening production build...
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.231:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.231:3001
 --------------------------------------
[BS] Serving files from: dist
[BS] Watching files...
`
But it's not actually running/working because the bundling failed. Anyone else getting this? Seems to be because of the './src/index' -> '/src/index' change in webpack.config.prod.js

Btw, thank you @coryhouse for this great starter!

**Comment by coryhouse** [comment]
Oops, sorry about that! Fixed.

Thanks for reporting!
