### ISSUE TITLE
Slimmed down version of react-slingshot

### ISSUE THREAD

**Issue by davebro** [coryhouse/react-slingshot#264]
Hey Cory, any chance of you creating, say, a "react-basic-slingshot" repository, something a little more slimmed down with just the bare necessities to start using react and redux? Maybe it already is in its most basic form and this question just doesn't make sense? My thought is that it's a great starter kit, however there is seemingly so much configuration going on, it almost feels like I HAVE to go through everything to understand what's happening with the tools. It's also kind of a question of, "Okay, so where do I just jump in and start writing with react?" Maybe it's just a matter of starring at and going through the code some more. Thank you so much for the project and all the hard work!

**Comment by coryhouse** [comment]
I basically build what you described in my React and Redux Pluralsight course. Also, Slingshot is just one of many starter kits out there. You might check out Create React App or one of many simpler alternatives listed here: http://andrewhfarmer.com/starter-project/

**Comment by davebro** [comment]
Great, I will check out your React/Redux course, I took the Flux/React course, it was very helpful. Thank you!
