### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by hwaterke** [coryhouse/react-slingshot#265]
Hi,

This looks like a nice start kit for a new app.
I have an existing app but I'm considering merging this setup to replace mine.

I'm still puzzled with the way this works.
After cloning this repo and running the setup tool, the whole .git folder is deleted.
I understand this needs to happen as you want your own repo for your app.
But then how to you make sure your slingshot setup is up to date with the latest additions and fixes made to this repo? Are you supposed to go over the commits one by one and apply them on your setup?

**Comment by coryhouse** [comment]
Great question. Yes, that's correct. This is just a starting point. There is no automated way to pull in changes down the road. I'm considering moving much of this to an npm package which would help automate such updates. But updates aren't trivial either way, since you may choose to change the core config in various ways which create conflicts down the road.

Thanks for the question!

**Comment by kwelch** [comment]
@coryhouse I had been thinking about the packaged version of this. How were you thinking of accomplishing that? 

How would you feel about a fork of CRA?

**Comment by coryhouse** [comment]
Here's the idea: 

Put the following dependencies in either separate, or a single npm package:
* .babelrc
* /buildScripts
* webpack configs (store json in build scripts. Reference in srcServer.js and distServer.js)

Eliminate .eslintrc and allow people to declare their own, or utilize rules of their choosing. Alternatively, reference existing preset like AirBnB, or create our own.

Other potentials:
* .editorconfig
* CI Configs
* npm scripts (call buildScripts for all tasks, so package.json becomes just a list of func calls)

Why?
1. Centralize code for easy bug fixes and maintenance
2. Clean up the project structure so it's less intimidating
3. Abstract away config so it's programmatically forced to be consistent. This avoids debugging errors with ad-hoc configs.

CRA is awesome, but their eject model doesn't has a downside: You're either in the ecosystem or out. I think it makes more sense to use npm packages for a baseline config and then use traditional means to override. So, for example, keep the webpack config in slingshot-build-scripts npm package, and then use that json as the baseline which you can override. I'm still working through how to execute that last sentence, but if I get this right I think it'll be a big win over the eject model.

**Comment by kwelch** [comment]
Makes sense. As much as I like eject, you end up having to take on everything for in most cases something small. 

Not sure if this will help with webpack, but there is this package, [webpack-merge](https://www.npmjs.com/package/webpack-merge). 

Let me know if/how I can help.
