### ISSUE TITLE
Question: How to properly add intl-polyfill to support Safari browsers

### ISSUE THREAD

**Issue by nowinskp** [coryhouse/react-slingshot#270]
I'm using react-intl for handling app translation. I know that Safari does not support Intl API and so a polyfill has to be used to make the app load on said browser.

I've found an example of how such Intl polyfill code could look like, here:
https://github.com/andyearnshaw/Intl.js/#intljs-and-browserifywebpack
but I'm not sure how to properly add it to the webpack's config in Slingshot.

So I kindly ask if anyone could explain to me how to use the code above in react-slingshot case? Thanks.

**Comment by kwelch** [comment]
You should be able to put this section below in your `App.js`

```
if (!global.Intl) {
    // line below allows for code splitting
    require.ensure([
        'intl',
        'intl/locale-data/jsonp/en.js'
    ], function (require) {
        // requires like this will just initialize them, and the modules set the globals
        require('intl');
        require('intl/locale-data/jsonp/en.js');
    });
}
```

**Comment by nowinskp** [comment]
I added it the same way `webpack-public-path.js` is added, as suggested.
It's working fine, thank you @kwelch!
