### ISSUE TITLE
HTML5 pushstate urls not working with dist build

### ISSUE THREAD

**Issue by dmurawsky** [coryhouse/react-slingshot#273]
Steps to reproduce:
'npm run build' then open index.html, navigate to a page like '/about' and hit refresh.

I ended up having to implement a hacky little fix that converts the url into a query string like this:
```javascript
app.route('/*').get(function(req, res, next) {
    res.redirect('/?q='+req.url);
});
```

And then interprets the query string in the app like this:
```javascript
const path = getParameterByName('q');
if(path){
  browserHistory.push(path);
}
```

getParameterByName function:
```javascript
function getParameterByName(name, url) {
    if (!url)
      url = window.location.href;
    const localName = name.replace(/[\[\]]/g, "\\$&");
    const regex = new RegExp("[?&]" + localName + "(=([^&#]*)|&|#|$)"),
          results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, " "));
}
```

**Comment by kwelch** [comment]
I believe this may be due to your `/*` redirect on the express server. Could you try the recommendation from [my comment] on the other bug and have all request return `index.html`?

**Comment by jeongl** [comment]
I'm having the same problem. @kwelch can you submit a Pr for your fix?

**Comment by dmurawsky** [comment]
It worked. 

``` javascript
var express = require('express');
// var serveStatic = require('serve-static');
app = express();
app.use(express.static("./"));
app.use(express.static("dist"));

app.get('*', (req, res) => {
    res.sendFile(`${__dirname}/dist/index.html`);
});

var port = process.env.PORT || 5000;
app.listen(port,function(){
  console.log('server started '+ port);
});
```

**Comment by kwelch** [comment]
@jeongl I am not able to PR since this is based on a custom configuration and not the baseline setup in Slingshot. If you have a particular question please open an issue so we can properly address it. 

@dmurawsky Awesome 👍 , I will close this issue. Let me know if there is anything else you need.
