### ISSUE TITLE
Query on webpack

### ISSUE THREAD

**Issue by ryannealmes** [coryhouse/react-slingshot#274]
I am not sure where to ask this, but I wanted to find out why [webpack.dev.conf](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.dev.js#L43) is using `babel` as a loader and not `babel-loader` in webpack. All the tutorials I have watch use `babel-loader`. is the text `-loader` applied automatically? 

```javascript
module: {
    loaders: [
      {test: /\.jsx?$/, exclude: /node_modules/, loaders: ['babel']}, // This line here!!!
      {test: /\.eot(\?v=\d+.\d+.\d+)?$/, loader: 'file'},
      {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url?limit=10000&mimetype=application/font-woff"},
      {test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream'},
      {test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml'},
      {test: /\.(jpe?g|png|gif)$/i, loader: 'file?name=[name].[ext]'},
      {test: /\.ico$/, loader: 'file?name=[name].[ext]'},
      {test: /(\.css|\.scss)$/, loaders: ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap']}
    ]
  },
```

What am I missing? Thanks.

Also thanks to everyone for this awesome repo. I have learnt so much from using it and the pluralsight course that inspired it!

**Comment by coryhouse** [comment]
The two styles are equivalent as outlined in the Webpack docs. :)
