### ISSUE TITLE
Can't get expose-loader to work with react-slingshot

### ISSUE THREAD

**Issue by ryannealmes** [coryhouse/react-slingshot#275]
**Description** 
Struggling to find a way to expose a library on the window object using webpack with the react-slingshot repo. I have managed to get [expose-loader](https://github.com/webpack/expose-loader) in a basic node app, but not this repo. My end goal is to get bootstrap running and this has a dependency on jQuery sitting on the window object.

Any ideas on how to achieve this on this repo would be appreciated.

Node version:
v6.3.0

npm version:
3.10.3

Operating system:
Mac OS X

Command line used:
iterm

Steps to reproduce:

1. `npm install jquery expose-loader --save`
2. Add `{ test: require.resolve('jquery'), loader: 'expose?jQuery!expose?$' },` as a loader to `webpack.dev.config`
3. Run the app and check that you can access `jQuery` in the console.

**Comment by ryannealmes** [comment]
After some more reading, I found a work around. I can add the following code to `src/index.js`
```javascript
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
```
Is this a good way of doing this? I would have prefered to have managed the dependency in webpack. Any ideas?

Thanks.

**Comment by kwelch** [comment]
To get bootstrap working in my solution I used, bootstrap-loader. 

In looking at their docs I [found this](https://github.com/shakacode/bootstrap-loader/blob/a54a1dcc20c31d0289a7b1af60d32ff1fbc05b3b/README.md#bootstrap-4-internal-dependency-solution) which may be helpful. In case his docs change here is the line in particular. 

```
plugins: [
  new webpack.ProvidePlugin({
    $: "jquery",
    jQuery: "jquery",
    "window.jQuery": "jquery",
```

**Comment by ryannealmes** [comment]
Thanks @kwelch, I think I am going to try give bootstrap-loader a try out today.

**Comment by kwelch** [comment]
Closing this out. If something comes up feel free to reach out.
