### ISSUE TITLE
To get CSS Modules working, I have to use ExtractTextPlugin in the dev config

### ISSUE THREAD

**Issue by rstudner** [coryhouse/react-slingshot#276]
loader: ExtractTextPlugin.extract('css?modules&camelCase=dashes&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap'),

Basically that.

So, i'm wondering, what is the downside of using ExtractTextPlugin in the webpack.dev.config

**Comment by kwelch** [comment]
What is causing this in your dev config? I run CSSModules in dev build with no issue. One thing I did have to do different is have 2 loaders one for `src` and one for `node_modules`. I did this by using the `include` and `exclude` params of the loader.

**Comment by rstudner** [comment]
Not sure, basically in AboutPage.js if I put:
import styles from './about-page.scss';

If I don't use ExtractTextPlugin then styles is not well, my styles (its some random function/thing).

If I include ExtractTextPlugin, it is a happy POJO with alt-header in it.

**Comment by rstudner** [comment]
https://github.com/rstudner/react-slingshot-test

That demonstrates it -- just have to comment out/include the 2 different lines int he webpack.config.dev to see the clear change/breakage.

**Comment by kwelch** [comment]
Only thing in that repo is a ReadMe.md. 

[Here is a PR](https://github.com/coryhouse/react-slingshot/pull/236) where I have a working CSSModules in the AboutPage.js. CSSModules are out of scope for this project, but the branch should still be helpful.

**Comment by rstudner** [comment]
Yeah, I didn't click "one more time" hah.  Sorry about that.  All files are present now.

**Comment by rstudner** [comment]
And interestingly - if I cut and paste your stuff, it is working.  I lose the camelCase stuff, just not sure how to get that included as well w/ the JSON.stringify format for providing the options (since it is part of the modules:true sort of statement)

**Comment by kwelch** [comment]
Main difference I saw was you were missing the style loader.

**Comment by rstudner** [comment]
Yep, I think that was it.  Man.  Thanks for that.  Awhile back when I tried the ExtractStyle line, it had 'style', '<and all the rest>' and I must have lost it in my wanderings in the desert.
