### ISSUE TITLE
npm run build also starts up the node server

### ISSUE THREAD

**Issue by rstudner** [coryhouse/react-slingshot#278]
Is this right?

if I do:
```
npm install
npm test #just because
npm run build
```
this starts the server in launches my browser.

So on a CI tool -- how do I NOT have it do this last part (start the server and try to launch a browser)

**Comment by kwelch** [comment]
On this [line](https://github.com/coryhouse/react-slingshot/blob/master/package.json#L22) You just need to remove the `&& npm run open:dist`

**Comment by rstudner** [comment]
Yeah - I had done that.  I was more asking if it made *sense* that the default build command also tried to kickoff the local server etc etc.  (versus like npm run build:view or somesuch)

Thanks!

**Comment by kwelch** [comment]
I don't see a reason for the CI to spin up the local server. 

I would love to see a PR with your recommended approach. 👍 

Closing this.
