### ISSUE TITLE
Problem in the Command npm test

### ISSUE THREAD

**Issue by ashikmahmud1** [coryhouse/react-slingshot#279]
Node version: 0.12.2

npm version:2.7.4

Operating system:Windows 10

Command line used: npm test

Steps to reproduce:
![problempart-1](https://cloud.githubusercontent.com/assets/22362320/19479899/990e3b12-956a-11e6-9b05-6591e8bf408c.PNG)
![problempart-2](https://cloud.githubusercontent.com/assets/22362320/19479900/991c0062-956a-11e6-91f7-898925474f41.PNG)

**Comment by ashikmahmud1** [comment]
Finally I have got my solution. I have uninstalled old node.js version and install version 6.8.1 and it's work Properly.

**Comment by coryhouse** [comment]
Great to hear!
