### ISSUE TITLE
react transform hmr is deprecated. Transfer to react hot loader?

### ISSUE THREAD

**Issue by seanyu4296** [coryhouse/react-slingshot#281]
From research, i found out that https://github.com/gaearon/react-transform-hmr is deprecated, and https://github.com/danmartinez101/babel-preset-react-hmre is not maintained.

Is there a plan on completely switching https://github.com/gaearon/react-hot-loader for hot reloading ?

**Comment by coryhouse** [comment]
Good question. React hot loader is still in beta. When React Hot Loader 3.0 comes out of beta we'll move this project to it.
