### ISSUE TITLE
Running 'npm build' does nothing.

### ISSUE THREAD

**Issue by wil9544** [coryhouse/react-slingshot#287]
Node version: **4.4.7**

npm version: **3.10.3**

Operating system: **Windows 7 Enterprise, Service Pack 1**

Command line used: **Powershell**

Steps to reproduce: 
1) Download project from Github as ZIP
2) Unzip
3) Using powershell, cd to directory of project
4) run `npm install`
5) run `npm build`
6) No dist folder is created, and no command line output is produced from running `npm build`

Output from `npm install` was just this:

**npm WARN Skipping failed optional dependency /chokidar/fsevents:
npm WARN Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN Not compatible with your operating system or architecture: fsevents@1.0.14**

I have an app I'm trying to deploy to production and was running into this issue, so I figured it was a problem with my project.  I tried with the base react-slingshot project from Github as a ZIP file (as stated in the reproduction instructions), and got the same problem.  Any ideas?

**Comment by coryhouse** [comment]
I'm not a powershell user, but I suspect that's the reason. If you run it on the DOS command line, does it work?

**Comment by wil9544** [comment]
I tried using windows cmd program and had the same results.  All the other commands (npm start and everything that it runs as a result) have worked fantastically.

**Comment by wil9544** [comment]
Nevermind, I was using `npm build` instead of `npm run build`...I am embarassed.

**Comment by coryhouse** [comment]
Ha, I've been there. Easy mistake to make. Mystery solved! :)
