### ISSUE TITLE
Ajax from a reducer?

### ISSUE THREAD

**Issue by mvolkmann** [coryhouse/react-slingshot#29]
fuelSavings.js contains this comment:
//in a real app we'd trigger an AJAX call here.

I thought since reducers are pure functions, you are not supposed to make Ajax calls from them.
Instead I think you are supposed to make an Ajax call from an event handling method and then dispatch an action based on the result.

**Comment by coryhouse** [comment]
Sorry, I'm not suggesting actually making the AJAX call there. I'm suggesting merely triggering it. If you're using Redux, that would likely be via a thunk: http://rackt.org/redux/docs/advanced/AsyncActions.html

I'm open to suggestions on how to change the comment to be clearer.

**Comment by coryhouse** [comment]
I updated the comment to better clarify, so closing.
