### ISSUE TITLE
Add the Yarn package manager

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#291]
It would be good to have the Yarn package manager used instead of npm install. The main reason for proposing this is pretty much why Yarn was built, fast and reliable dependency management. For those not aware of Yarn, you can read more about it here, https://yarnpkg.com.

I will put up a PR shortly for this.

**Comment by coryhouse** [comment]
Closed via PR #292

**Comment by nickytonline** [comment]
Thanks for merging @coryhouse. Here's a screen shot of Travis CI for react-slingshot. As you can see there's a big difference in build times now. 

![screenshot_2016-10-30-09-21-37](https://cloud.githubusercontent.com/assets/833231/19836807/7aac98dc-9e82-11e6-8a76-54d91e58d74f.png)

**Comment by coryhouse** [comment]
Great improvement! :)
