### ISSUE TITLE
app reloads after each change, how to disable it and use hot module replacement

### ISSUE THREAD

**Issue by cubbuk** [coryhouse/react-slingshot#296]
Node version:6.9.1

npm version: 3.10.8

Operating system: Ubuntu 16.04

Command line used: npm start -s

Steps to reproduce: Just run the app, change some state, update any file and you have a full refresh rather than hot module replacement. Is there any way to stop this?

**Comment by coryhouse** [comment]
Fixed in https://github.com/coryhouse/react-slingshot/commit/d5e8134aa761c991325296e59db047ea0fb565c9 

Note that the current version of hot reloading isn't perfect and doesn't work in all scenarios, but this change does fix the issue where App.js wasn't hot reloading in the demo.

Thanks! 👍

**Comment by cubbuk** [comment]
Thanks a lot :+1: it started working in my project too.

**Comment by kwelch** [comment]
For the record, I do have plans to update to react-hot-loader once it is officially released. This will allow stateless functions to reload properly. I have been using it from sometime now, but it is in beta.
