### ISSUE TITLE
Yarn install failing on Appveyor

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#297]
Hey @nickytonline - Any ideas?

https://ci.appveyor.com/project/CoryHouse/react-slingshot/build/job/i1hjfocgsxgg7rfo

**Comment by nickytonline** [comment]
@coryhouse, I'll look at this later tonight to see what's up...

**Comment by nickytonline** [comment]
@coryhouse, I know what the issue is. AppVeyor very recently made Yarn preinstalled on their CI images. This is why the build is failing. I will update the AppVeyor CI script later tonight unless you want to tackle it. See https://github.com/yarnpkg/website/pull/233

**Comment by nickytonline** [comment]
@coryhouse, here's the new steps for setting up Appveyor, https://yarnpkg.com/en/docs/install-ci#appveyor-tab

**Comment by coryhouse** [comment]
Ah! Nice. Thanks for the quick reply Nick. I just uploaded the fix.

**Comment by nickytonline** [comment]
Cool beans, glad we're back up.
