### ISSUE TITLE
Thoughts on migrating to Tape?

### ISSUE THREAD

**Issue by oshalygin** [coryhouse/react-slingshot#302]
Trying to get a feeling on converting to Tape from mocha.  Thoughts @coryhouse ?

Some more background.
https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4

**Comment by coryhouse** [comment]
Thanks for the suggestion. Tape is a great option too, but if we migrate anywhere, it will be to Jest since it offers some unique React-specific benefits.
