### ISSUE TITLE
Connecting Backend express-mongo with react-slingshot

### ISSUE THREAD

**Issue by andela-rekemezie** [coryhouse/react-slingshot#303]
I am using react-slingshot for my react/redux application. Now, I want to add and express mongo backend to it. Help on how to approach this would be most appreciated

**Comment by ronstarcool** [comment]
same here! i have no idea

**Comment by coryhouse** [comment]
I suggest keeping the API and UI in completely separate projects. So this question feels presumptuous to me. I discuss the merits of this approach and show an example of getting it done with a starter kit similar to Slingshot in the final module of my new Pluralsight course: [Building a JavaScript Development Environment](https://app.pluralsight.com/library/courses/javascript-development-environment/table-of-contents).
