### ISSUE TITLE
How to change application root from / to /app for both dev and production

### ISSUE THREAD

**Issue by progand** [coryhouse/react-slingshot#304]
I want to open app via http://localhost:3000/app

I've changed __webpack_public_path__ in its file and publicPath in web pack configs.

Everything works fine on production (I placed build in /app folder). But in dev I have no script and style tags in initial html.

Any ideas?

**Comment by progand** [comment]
I want to open app via http://localhost:3000/app

I've changed __webpack_public_path__ in its file and publicPath in web pack configs.

Everything works fine on production (I placed build in /app folder). But in dev I have no script and style tags in initial html.

Any ideas?

**Comment by qborreda** [comment]
Similar to this question, we are fine developing with the provided browsersync server at `/`, but our deploys are going to be in a very different folder such as `/a/b/c/` .. 

So far, we have implemented an environment variable (as that url can change), and set up so our Router takes just `/` when in __DEV__ and `/:lang/:country/:city/` if we are building code for the AWS machines bundle .. 

Something like
```
<Route path={__DEV__ ? '/' : process.env.BO_PUBLIC_PATH} component={App}>
```
(And something similar in any menu, or route redirection ... 

The thing is, obviously, we don't have a `/a/b/c/` folder structure locally so we can't try the production ready bundles locally, just as we upload and build them on the servers .. so things such as static json files, or background images used in our scss can't be imported ..

**Comment by coryhouse** [comment]
@qborreda I'd suggest updating the build process to write the production build to a directory structure that mimics your production folder structure. So I'd add the appropriate subdirectories under /dist.

**Comment by qborreda** [comment]
Well, maybe I didn't explain it correctly, but we now have combinations of 3 languages, several countries, and even more cities .. and those are going to be virtual urls, served through nginx to point to our React app listening for `/:language/:country/:city_name` (kind of), but not physical.

I've tried my best to see if browsersync had some kind of url redirection, but failed at it ..

**Comment by coryhouse** [comment]
Yeah, it sounds like in your case you could benefit from something more flexible than Browsersync. Might consider using Express instead.

**Comment by coryhouse** [comment]
@progand - Sorry, somehow missed your initial question. Did you get your issue resolved?

**Comment by progand** [comment]
@coryhouse I made a bit weird solution.

### webpack.config.dev.js
```
 output: {
    path: path.resolve(__dirname, 'dist'), // Note: Physical files are only output by the production build task `npm run build`.
    filename: 'bundle.js',
    //publicPath: '/'
    publicPath: '/app'
  },
...
```

### tools/srcServer.js
```
...
const publicPath = '/app',
  publicPathNoSlashes = publicPath.replace(/^[\/]+/, '').replace(/[\/]+$/, '');
...
      historyApiFallback({
        // oncomment to debug requests in development mode
        //verbose: true,
        rewrites: [{
          from: new RegExp(`^\/${publicPathNoSlashes}\/.*$`),
          to: function(context) {
            if (context.parsedUrl.pathname.indexOf('.') !== -1) {
              return context.parsedUrl.pathname.slice(publicPath.length - 1);
            }
            return '/index.html';
          }
        }]
      }),
...
```

I think using proper directory structure within `dist` may be better way. But it works!
Thanks!

**Comment by coryhouse** [comment]
@progand Actually, I prefer your approach. Thanks for sharing! 👍
