### ISSUE TITLE
npm ERR! Failed at the react-slingshot@5.0.0 lint script 'esw webpack.config.* src tools --color'.

### ISSUE THREAD

**Issue by nndp** [coryhouse/react-slingshot#307]
(edited formatting)

Node version: 6.9.1

npm version: 3.10.8

Operating system: windows 10, freshly installed 2days ago

Command line used: npm run build

I have been working on this project for a month on a different PC (also windows10) and everything worked out of the box. On this new PC 'npm run start' works fine, but building doesn't work. I checked that I have webpack installed globally, also python 2.7 is installed, and ofcourse the node_modules !

On the error log, this line: 
npm ERR! react-slingshot@5.0.0 lint: `esw webpack.config.* src tools --color`
I am not sure what esw is supposed to do or be. I don't seem to have a bash command that is called esw... perhaps thats the problem ?

This is the entire error message I get:
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@5.0.0 lint: `esw webpack.config.* src tools --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@5.0.0 lint script 'esw webpack.config.* src tools --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NN\Documents\lehrstück\Cockpit\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@5.0.0 prebuild: `npm run clean-dist && npm run lint && npm run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-slingshot@5.0.0 prebuild script 'npm run clean-dist && npm run lint && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-slingshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean-dist && npm run lint && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-slingshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-slingshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\NN\Documents\lehrstück\Cockpit\npm-debug.log

**Comment by coryhouse** [comment]
esw is eslint-watch. 

Please try this:

1. Delete node_modules
2. npm install
3. npm run build

**Comment by nndp** [comment]
this is really weird. reinstalling the modules did not change anything. but i had an unused variable that was being mentioned during compilation not as a warning but as an error. 'npm run start' worked fine but apparently this unnused variable made building not work. i commented it and suddenly building works. 

I just double checked and inserted the unused variable again and it gives an error when running 'build' but not when running 'start'.

thx for your quick reply though ! your slingshot is really great, i enjoy working with it alot ! have a nice day cory !

**Comment by coryhouse** [comment]
Glad you're up and running! 👍
