### ISSUE TITLE
SASS only working in DEV build, not production

### ISSUE THREAD

**Issue by jonstra** [coryhouse/react-slingshot#308]
Node version: 6.9.1 (tried different versions)

npm version: 3.10.8

Operating system: Windows 10

Command line used: npm run build

Steps to reproduce:

Hi.

I used a bootstrap project and rewrote it into components, but kept the *.scss files as is.
When i run "npm start" the page works perfectly. However, when running "npm run build" the page does not display properly when running the production server. I think this is due to the fact that SCSS files are not being packed properly? I have 3 *.scss files in my styles folder.

When building my project there are no error messages and everything looks okay. The scss files are showing up as [built].

Does anybody know what could cause this? Thank you.

**Comment by coryhouse** [comment]
Three questions to investigate:

1. Are you referencing the Sass files in your app? 
2. Are they being generated by the production build? 
3. Are you seeing a 404 in production?

**Comment by falconmick** [comment]
I am having a similar issue, I am including Bulma (kinda like bootstrap) via:

```
import 'bulma';
```

it works fine in dev, but in production I am getting:

```
uncaught Error: Cannot find module "bulma"
```

I'm sure you mentioned somthing about this in your flux course, but 1am me can't remember so I thought I'de comment here so many in the morning you might know what myself and jonstra are going through.

cheers.

**Comment by nickytonline** [comment]
@jonstra and/or @falconmick, do you have a repo I can look at? I'll try and take a peek at this this weekend. Cheers.

**Comment by falconmick** [comment]
https://github.com/falconmick/scratch-list

I'm sure I'm just doing somthing stupid. I'm going to re-watch the flux videos to see if I can find what I'm doing wrong.

**Comment by falconmick** [comment]
Ok I managed to fix mine. Basically in DEV i had added another arg to the regex to search for |\.sass as bulma uses that. So I added that extra rule for the styles to prod and now it works.

**Comment by nickytonline** [comment]
Cool stuff @falconmick. Glad to hear you got it working.

**Comment by nickytonline** [comment]
@jonstra, are you still having issues with this? If you are, do you have a repo I can look at?

**Comment by jonstra** [comment]
Hi @nickytonline . Sorry for the late reply. I fixed the scss issues by importing them into App.js (not sure if this is best practice) like so: import '../styles/scss/variables.scss';

 However, i still have problems with smoothscroll trying to import it the same way. The page wont load at all and i get no errors. I don't have an online repo as it is a personal project. But i could maybe send you if you would take the time to fix some issues that would be great.

**Comment by jonstra** [comment]
Hi.

I can run "npm run build" now without without errors. However, the page does not return anything. With "npm start" the code attached works just fine. Can you please help me explain this behavior?

[gitexample.txt](https://github.com/coryhouse/react-slingshot/files/636790/gitexample.txt)

Thank you!

**Comment by fayimora** [comment]
I have a similar issue. 

Steps I took:
- `yarn install bootstrap`
- Import bootstrap in `index.js` with `import '../node_modules/bootstrap/dist/css/bootstrap.css';`

In dev mode, `yarn start`, bootstrap works fine. `yarn build` I get the error below and in the console I get ![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2016-12-17-23-13-08.png)

```
ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module build failed: Error: ENOENT: no such file or directory, open '/Users/fayimora/Code/author-management/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at module.exports (/Users/fayimora/Code/author-management/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/fayimora/Code/author-management/node_modules/svgo/lib/svgo.js:21:19)
    at /Users/fayimora/Code/author-management/node_modules/postcss-svgo/dist/index.js:91:16
    at Object.creator [as postcssSvgo] (/Users/fayimora/Code/author-management/node_modules/postcss/lib/postcss.es6:111:27)
    at /Users/fayimora/Code/author-management/node_modules/cssnano/dist/index.js:283:40
    at Array.forEach (native)
    at /Users/fayimora/Code/author-management/node_modules/cssnano/dist/index.js:270:29
    at creator (/Users/fayimora/Code/author-management/node_modules/postcss/lib/postcss.es6:111:27)
    at processCss (/Users/fayimora/Code/author-management/node_modules/css-loader/lib/processCss.js:187:16)
    at Object.module.exports (/Users/fayimora/Code/author-management/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/index.js 25:0-59
```

Any ideas @coryhouse ?

**Comment by coryhouse** [comment]
@fayimora Can you share a link to your repo?

**Comment by fayimora** [comment]
@coryhouse https://github.com/fayimora/author-management

I updated the repo to import bootstrap into `styles.app.scss` and then import that file into `index.js` but the effort was futile 😢

**Comment by coryhouse** [comment]
@fayimora I just cloned your repo and both start and build worked great. Bootstrap was included. ??

rm -rf your node_modules and try again. :)

**Comment by fayimora** [comment]
@coryhouse Something very odd is happening here because I just cloned my own repo into another location and it did work fine.

I went back to the original folder and removed the node_modules but still get that error. I have checked and there are no changes #magic 😱 😨

**Comment by mikedevita** [comment]
i have bootstrap-sass working properly with

```
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
$fa-font-path: '~font-awesome/fonts';
@import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import '~font-awesome/scss/font-awesome.scss';
```

**Comment by kwelch** [comment]
This appears to be fixed. Reopen if I judged wrong.

**Comment by vinhtq** [comment]
I have same issue. If we make quite deep nesting folder, the sass files will not be compiled

For example: 
src/components/containers/form/Login.js
src/components/containers/form/login.scss

Only js file will be compiled in production, scss file is ignored. I dont know why
