### ISSUE TITLE
Future-proofing for Webpack 2

### ISSUE THREAD

**Issue by mlwigdahl** [coryhouse/react-slingshot#309]
Node version: 7.0.0+

npm version: 3.10.8

Operating system: Windows Server 2003 [[ 0_o ]]

Command line used: npm run build

Steps to reproduce:  I was having a lot of issues getting the production build to work after upgrading to Webpack 2.0 beta (so I could use tree-shaking).  Development was working fine, but I kept getting "l is not a function" errors when attempting to load the production bundle.

What looks like is happening is that your dynamic inclusion for configureStore() is not playing well with Webpack 2.0 with CommonJS replacement turned off.  

I'm honestly not sure exactly what is going on -- I tried replacing the require() calls with System.import() calls but got the same problem.  What _did_ work was to combine the dev and prod versions of configureStore() into a single file and just use static inclusion.

If it isn't a huge efficiency to have these split up with dynamic inclusion, it would probably be more compatible with Webpack in the long run to just use a single file.

I'd be happy to make up a pull request if you'd like to review, or if you have a better idea I'm all ears. Love Slingshot, by the way!  Thanks so much for making this available to the community!

**Comment by coryhouse** [comment]
Hi Matt - Thanks for the issue. This is good stuff. Yes, the dynamic inclusion is a problem because it's not statically analyzable. I'd welcome a PR with your change since I plan to move us to Webpack 2 as soon as it comes out of Beta. 

I'd also love to see the changes you made to support Webpack 2 if you're willing to share your fork.

Thanks again! 👍

**Comment by mlwigdahl** [comment]
Absolutely!  I'll put it together either tonight or tomorrow and get it to you!

**Comment by kwelch** [comment]
This was merged with #313. Closing.
