### ISSUE TITLE
Execute bit set on .eslintrc

### ISSUE THREAD

**Issue by toddprater** [coryhouse/react-slingshot#318]
Node version: 7.1.0

npm version: 3.10.9

Operating system: Mac OS X 10.10.5

Command line used: N/A

Steps to reproduce:

```
>git clone https://github.com/coryhouse/react-slingshot.git
>ls -l .eslintrc
-rwxr-xr-x  1 toddprater  staff   1.8K Nov 14 14:22 .eslintrc
```

Let me say first, I'm not even sure this is a problem per-se, but as I've been using this repo and (your excellent Pluralsight courses) to get up to speed on React/JS development, I wanted to make sure I understand everything. If I remove the execute bit everything seems to still work just fine. I can do a quick PR on this if it is indeed something that snuck in inadvertently. (Or if it does need to be set as executable for some reason I'd like to know why.)

**Comment by coryhouse** [comment]
You're correct that the permissions are needlessly permissive on this file since it technically only needs to be read. But I'm not too worried it since I see no impact.
