### ISSUE TITLE
Inaccurate Instructions for Removal of Redux

### ISSUE THREAD

**Issue by netpoetica** [coryhouse/react-slingshot#32]
In the README, the section which lays out how to remove redux is inaccurate/incomplete. See: https://github.com/coryhouse/react-slingshot#do-i-have-to-use-redux

- main.js isn't a file, should be index.js
- doesn't make it clear whether you should remove or keep react-redux and Provider
- doesn't make it clear whether you should remove or keep store, configureStore
- "reference your top level component (instead of Redux's root container at ./containers/root)" is not followable. There is nothing left after following the removal steps which actually imports or requires /containers/root

**Comment by coryhouse** [comment]
Great point. I threw these steps in quickly as some general guidance but clearly didn't actually step through this to confirm. I don't have time to do so right now, but I just updated the steps so it's at least much closer.

**Comment by netpoetica** [comment]
No prob, redux is just still very immature right now. I think this boilerplate is very well put together and steps to remove redux should make it more easy to gain wider adoption. The most recent changes already look a lot better! Cheers

**Comment by coryhouse** [comment]
I've updated the Redux removal instructions to provide the exact details and tested the steps myself. Thanks for the heads up!
