### ISSUE TITLE
setting basename with syncHistoryWithStore

### ISSUE THREAD

**Issue by falconmick** [coryhouse/react-slingshot#320]
Just wondering how this is done. I am getting the following warning when I use <base href='/some-url'>

Automatically setting basename using <base href> is deprecated and will be removed in the next major release. The semantics of <base href> are subtly different from basename. Please pass the basename explicitly in the options to createHistory

How is it done through the router setup in this project? Cheers

**Comment by kwelch** [comment]
I apologized that this was missed. Are you still still having this issue?

**Comment by nickytonline** [comment]
@falconmick, checking up one more time to see if you're still having this issue.

**Comment by falconmick** [comment]
I'm not getting it anymore, but perhaps that is because I've been working on other technologies for a bit! I can try and find out how I made it happen and test again if you would like, however if it's been fixed already I'll just trust you!

**Comment by kwelch** [comment]
It has been quite some time since this was opened so it is possible that it works, but if you could validate I believe it would be valuable to ensure it is in a working state.

**Comment by kwelch** [comment]
I am going to go ahead any close this. If this issue does arise again, don't hesitate to re-open or a create a new issue.

**Comment by falconmick** [comment]
Sorry I couldn't help
