### ISSUE TITLE
Code splitting example through react-router and webpack 

### ISSUE THREAD

**Issue by seanyu4296** [coryhouse/react-slingshot#324]
Hi, 
I want to add code splitting and lazy loading to my web app. My current bundle size is getting bigger. Around 3mb and browser needs to load 950kb for things to appear. 

Do you guys have any examples or blogs or steps for code splitting?

**Comment by coryhouse** [comment]
I discuss code splitting in the final module of my new Pluralsight course: Building a JS Dev Environment. Or, just Google for commonsChunkPlugin
