### ISSUE TITLE
installation and npm start fails

### ISSUE THREAD

**Issue by akhatri** [coryhouse/react-slingshot#325]
Node version:
v7.1.0
npm version:
3.8.7
Operating system:
Windows 10 Home
Command line used:
CMD
Steps to reproduce:

All of a sudden my webpack and browserync has stopped working. I removed node_modules and did the following fresh npm install in CMD as admin. 

1. npm install
2. npm run setup
3. npm start

it gave the error below

```
npm ERR!events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)

```

Also, running npm start loads up browsersync but then it cancels out

```
[BS] Serving files from: src
[BS] Watching files...
webpack: wait until bundle finished: /index.html

npm ERR!events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
```

could someone please assist with this? I have no good idea about webpack and it's really frustrating when things do not work. Thanks

**Comment by coryhouse** [comment]
I hate to say this first, but have you tried rebooting? Second, I recommend trying Node 5. I've seen others in my office have issues with Node 7 on Windows 10.

**Comment by akhatri** [comment]
thanks @coryhouse it looked like a NodeJS issue. I've reverted back to 6.9 and it seems stable now.
