### ISSUE TITLE
Issue with serving static files

### ISSUE THREAD

**Issue by jediofthecode** [coryhouse/react-slingshot#326]
Node version: 6.9.1
npm version: 3.10.8
Operating system: Ubuntu 16.10 AMD64

Steps to reproduce: When serving fonts via the file loaders in src/fonts, they are available to download, and if set with an absolute http url (eg: http://localhost:3030/fonts/fontname.woff in sass they are correctly read, but if I set with an absolute base url(eg: /fonts/fontname.woff) it will not load properly. I am wondering if this is an issue or there are special steps for including fonts in sass files for defining custom font-faces.

**Comment by kwelch** [comment]
Is this from the dev server or production? 

If you are intending to use the file loader I recommend referencing the files like the [image example on the FAQ page](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md#how-do-i-handle-images).

**Comment by jediofthecode** [comment]
it is from the dev server, and, can I reference files like this within an scss file ?

**Comment by davidglbr** [comment]
Yes, if I understand what you are asking.
Can you describe the use case so maybe we can be more helpful?
ᐧ

**Comment by jediofthecode** [comment]
Alright, sorry for the delay, if I reference a font like this in my sass:

`@font-face {
    font-family: 'proxima-reg';
    src: url('../fonts/proxima_nova_alt_regular-webfont.woff2') format('woff2'),
         url('../fonts/proxima_nova_alt_regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}`

it will not work at first, it shows no font's loading, i get no errors in webpack or in the console. Then i can modify the file to anything, save, and modify it back to exactly this, save and it hotloads, and the font loads...this makes no sense why it is not loading initially.

**Comment by davidglbr** [comment]
Weird. That worked for me. Maybe it's something with your specific
hot-reloading config? Have you changed it from the one on the repo?
ᐧ

**Comment by kwelch** [comment]
I put in #207 which dynamically set the `publichPath` which should resolve this. 

If I read your last comment it appears you got it working. If not feel free to re-open.
