### ISSUE TITLE
Removing need for custom scripts in tools/ dir?

### ISSUE THREAD

**Issue by ivanistheone** [coryhouse/react-slingshot#33]
Would there be a way to do without the scripts in `tools/`? It seems with a little uglyness in package.js you could call browser-sync as a npm run script? I thought the whole idea of using `npm run` scripts was to have `package.json` be the single configuration file...

I'm guessing it's because you can't [specify middlewares](https://github.com/coryhouse/react-slingshot/blob/master/tools/srcServer.js#L19) on the command line?

Right now I'm trying to get a minimum viable webpack+browser-sync build system and it seems like if I'm going to use custom scripts like those in the `tools/` folder, I might as well use a task runner like `gulp`...

**Comment by coryhouse** [comment]
Even if it were possible to completely configure browsersync on the command line, it would be a very long command.  What do you feel is the downside of calling a separate script in tools?

**Comment by ivanistheone** [comment]
One potential downside is having to maintain the custom scripts as dev-stack and APIs evolve; in general I prefer to "own" as little code as possible and rely on packages maintained by others.

That being said, I think the current state of webpack/react/redux tooling is such that a lot of customization is required, and custom scripts are very flexible.  It seems like this is necessary complexity ;) Closing.

**Comment by coryhouse** [comment]
To clarify, there's nothing more "custom" about the js-based configuration file in /tools than a comparable Gulp config. In fact, if you check browsersync's docs, you'll see that I copy and pasted their recommended config largely verbatim. If I were using Gulp, I'd likely copy/paste from some gulp plugin doc.
