### ISSUE TITLE
How to mock es6 import dependency

### ISSUE THREAD

**Issue by 375683067** [coryhouse/react-slingshot#331]
Actually it's not an issue. But I wander if you can help me.
The question is how to mock es6 imports? 
I've a googled a lot but I didn't find  a way what works for me.

Another "not issue" is how to debugg tests.

**Comment by coryhouse** [comment]
Regarding mocking ES6, here's some info: http://stackoverflow.com/questions/35240469/how-to-mock-the-imports-of-an-es6-module

To debug tests, you can use integrated Node debugging in your editor, or simply use console.log.
