### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by hwaterke** [coryhouse/react-slingshot#334]
Anyone tried migrating an existing project using this boilerplate to use Typescript?

**Comment by coryhouse** [comment]
Here's a fork by @nickytonline with TS support. https://github.com/typescriptcrew/ts-react-slingshot

**Comment by rajivkulkarni** [comment]
That repository looks way old. Wish he kept syncing it up with this one.

**Comment by nickytonline** [comment]
@rajivkulkarni I've been quite busy as of late. I will try to get it back up to date when a big chunk of free time pops up.

**Comment by nickytonline** [comment]
@rajivkulkarni. if you're looking for TS React inspiration, I also have this guy here, https://github.com/nickytonline/ts-react-starter which is with webpack 2 and TS 2.1

**Comment by rajivkulkarni** [comment]
Thanks.

**Comment by nickytonline** [comment]
Oops, it's still webpack 1. It was my Preact repo that is webpack 2

**Comment by Rajiv-Kulkarni** [comment]
Ah. The webpack version is still 1.*. ANyplans to update it to version 2.*? I have posted a couple issues there I guess related to webpack version 1 vs 2. Thanks.

**Comment by nickytonline** [comment]
@rajivkulkarni, it will get upgraded when I update the whole repo with all of react-slingshot's changed. Having said that, if the issues are ts-react-slingshot,  please only open the issues in that repo. Thanks.

**Comment by nickytonline** [comment]
For all typescript related issues in regards to react-slingshot, please use this repo to report issues, https://github.com/typescriptcrew/ts-react-slingshot/issues

**Comment by nickytonline** [comment]
Related #531, #370, #44

**Comment by leogoesger** [comment]
https://github.com/leogoesger/redux-typescript-boilerplate
I recreated a react, redux typescript app following react slingshot file structure. It doesn't have all the bells and whistles, but it does work. It has react, redux, react router, react-route-redux, thunk and material ui. It was created with create-react-app, and can be ejected.
