### ISSUE TITLE
Lint "build" code in addition to "src" code.

### ISSUE THREAD

**Issue by cowboy** [coryhouse/react-slingshot#34]
I'd like to see the root `*.js` and `tools/*.js` files get linted, using ES5 rules.

**Comment by coryhouse** [comment]
Good point. This brings a bigger question: Should the build code be in ES6 for consistency? I lean toward yes. Could use babel-node to compile it.

**Comment by cowboy** [comment]
That would be great. `node -r babel-register ./script` is how I've been doing it with babel 6.

**Comment by coryhouse** [comment]
Build code is now being linted. I'll open a separate issue for tracking upgrading the build scripts to ES6. Thanks for the linting suggestion!
