### ISSUE TITLE
Update to follow all-contributors spec

### ISSUE THREAD

**Issue by kwelch** [coryhouse/react-slingshot#340]
In effort to call out contributors for all that they do.

I recommend we update the repo to follow the all-contributors specification, as [defined here](https://github.com/kentcdodds/all-contributors)

**Comment by coryhouse** [comment]
I like the result, but am hesitant because it's signing up for ongoing, manual work to keep an out of band display like that updated. I like that this is automated: https://github.com/coryhouse/react-slingshot/graphs/contributors

**Comment by kwelch** [comment]
Makes sense I think Kent puts the effort on the contributors also this
graph is only limited to code, but understand the maintenance aspect. Feel
free to close.

**Comment by nickytonline** [comment]
@kwelch, it does seem like a nice idea, but I agree about the upkeep. I actually added a [CONTRIBUTORS.md](https://github.com/coryhouse/react-slingshot/blob/master/CONTRIBUTORS.md) a while back to the project which is more minimal and even that stopped getting maintained.

**Comment by coryhouse** [comment]
Closing since maintenance burden too high.
