### ISSUE TITLE
CSS build by webpack is blocking render html according to google pagespeed insight

### ISSUE THREAD

**Issue by azulkipli** [coryhouse/react-slingshot#349]
Why CSS build by webpack is blocking render html according to google pagespeed insight, how to solve it?

Node version: v7.2.1

npm version: 3.10.9

Operating system: macOS 10.12.2 (16C67)

Command line used: npm run build

Steps to reproduce: do the npm run build

**Comment by coryhouse** [comment]
I'm open to a pull request if you have a concrete suggestion that:
1. Improves performance for all.
2. Isn't too complicated.

But [per the docs](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery), I don't see a concrete change to make that will **universally** improve things for people.
