### ISSUE TITLE
RFC: Add `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [coryhouse/react-slingshot#351]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by nickytonline** [comment]
@amilajack,  this looks interesting. I was about to ask how it works with polyfills, but I waited a little longer and the animated GIF answered that for me ;). I just wonder if this fits into the scope of the starter kit or is it more of a bells and whistles kinda thing.

On a somewhat related note, I feel like this, plus other things people have been asking for brings us back to getting the yeoman generator up and running for the project.

**Comment by amilajack** [comment]
>  I just wonder if this fits into the scope of the starter kit or is it more of a bells and whistles kinda thing.

I think its fitting for any project that runs on the web platform. Native build chains have had this feature for a long time. I thought it was about time that the web platform had these kinds of api checks.

**Comment by coryhouse** [comment]
Nice. This is quite slick, but I don't know that it makes sense to integrate:
1. It's easy to add for those who want it.
2. The configuration will differ per person.
3. It's another thing to learn to understand this starter kit.

Bottom line, I like it, but I lean against adding it in an effort to keep things simple. I agree with Nick that this might be an interesting add if we prompted people for the list of features they'd like via something like Yeoman.

**Comment by amilajack** [comment]
@coryhouse agreed. Lets add this via a yeoman package.

**Comment by nickytonline** [comment]
@amilajack the yeoman part of React Slingshot does not exist yet. There was a bit of work done on it, but not much. (see #20).

**Comment by nickytonline** [comment]
@amilajack, as mentioned in #20, we're no longer pursuing a Yeoman generator as a solution to make react-slingshot customizable (https://github.com/coryhouse/react-slingshot/issues/20#issuecomment-277376274).

Perhaps we could add a section to the documentation on extending tooling like eslint where @amilajack could throw up a PR for documentation and point to how to intergrate the eslint plugin? Thoughts @coryhouse, @kwelch ?

**Comment by coryhouse** [comment]
@nickytonline - Yep, I'm open to that.
