### ISSUE TITLE
App config

### ISSUE THREAD

**Issue by fayimora** [coryhouse/react-slingshot#352]
I may be wrong but it seems react-slingshot doesn't have any sort of app config setup. 

I think it'll be nice to have something like `config/environment.js`  where config variables for the app can be set. This way, I can easily specify different configs for multiple environments, e.g API keys, baseUrls, app feature flags, e.t.c

Thoughts?

**Comment by coryhouse** [comment]
One can easily do such a thing using [process.env](http://stackoverflow.com/questions/4870328/read-environment-variables-in-node-js). 

Thus anything can be forked by env as desired by adding a conditional that checks process.env. 

Did you have something specific in mind for adding to Slingshot?

**Comment by fayimora** [comment]
config file could look like:

```js
module.exports = function() {
  let ENV = {};

  if(environment==='development'){
    // ... add stuff to ENV
  }
  if(environment==='production'){
    // ... add stuff to ENV
  }

  return ENV;
}
```

and somewhere in my app, maybe a component:
```js
import config from './config'
import React from 'react';

class App extends React.Component {
  constructor(props){
    const url = config.apiUrl
  }
}

```

**Comment by fayimora** [comment]
@coryhouse something like the above. Only thing I'm not sure about is how to inject the `environment`.

**Comment by coryhouse** [comment]
Yep, pretty common pattern. I'm not sold adding a few lines of code to the starter makes sense though, since we'd have no practical use case to showcase and the boilerplate we'd be offering is basically a simple switch statement.

**Comment by fayimora** [comment]
Ok fair enough, what way do you recommend I pass the environment to the config?

**Comment by fayimora** [comment]
Also, it'll be cool if I didn't have to specify where the config is, as per `import c from '../config'` but just `import c from 'config'` from any where. Is this something webpack can help with?

**Comment by coryhouse** [comment]
You could create an npm package that creates such an abstraction. I'm sure something like this already exists - I recall seeing it the other day - but I can't find it at the moment. 400k packages makes things hard to find! :)

**Comment by mikedevita** [comment]
@Fayimora do you have an example of what's needed to get the global imports working? I'd love to do this for reducers actions and componets/containers.

**Comment by fayimora** [comment]
@mikedevita I took a stab at a solution using webpack's [resolve.alias](https://webpack.js.org/configuration/resolve/#resolve-alias) but it didn't work. I can create a fresh slingshot project with what I did if you want, maybe you'll find what I was missing. I'll have another go at it sometime this week though. I'm really tired of relative imports

**Comment by fayimora** [comment]
I also found [this article](http://xabikos.com/2015/10/03/Webpack-aliases-and-relative-paths/) but my attempt was the same and didn't work

**Comment by mikedevita** [comment]
I got it working. I'll post code after a bit

Mike DeVita
Relative Media
Mike@relative.media<mailto:Mike@relative.media>
[602] 541-4137

On Jan 9, 2017, at 1:27 PM, Fayi Femi-Balogun <notifications@github.com<mailto:notifications@github.com>> wrote:


I also found this article<http://xabikos.com/2015/10/03/Webpack-aliases-and-relative-paths/> but my attempt was the same and didn't work

-

**Comment by fayimora** [comment]
Yaay @mikedevita! *awaits code eagerly*

**Comment by mikedevita** [comment]
in my **webpack.config.dev.js** i have the following, obviously one alias for each"folder" in `src/` you may or may not need all of them.. im also using `reducers/` to include all my actions, constants, reducers etc..

``` javascript
// ... ommited for brevity
  resolve: {
    root: [path.resolve(__dirname, 'src'), path.resolve(__dirname, 'node_modules')],
    alias: {
      containers: path.resolve(__dirname, 'src', 'containers'),
      components: path.resolve(__dirname, 'src', 'components'),
      reducers: path.resolve(__dirname, 'src', 'reducers'),
      layouts: path.resolve(__dirname, 'src', 'layouts'),
      styles: path.resolve(__dirname, 'src', 'styles'),
      store: path.resolve(__dirname, 'src', 'store'),
      middleware: path.resolve(__dirname, 'src', 'middleware')
    },
// ... ommited for brevity
```

so my reducers folder looks like this

```
reducers/
  auth/
    constants.js - constants
    actions.js - actions/thunks
    index.js - import/export it all, and setup initialState
```

**Comment by fayimora** [comment]
Nice, it works for me. 1 issue - I get an error on the console even though it works

![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2017-01-09-23-50-08.png)
![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2017-01-09-23-50-31.png)

Lint error I get: ![](https://fayidrop.s3-eu-west-1.amazonaws.com/Screen-Shot-2017-01-09-23-48-40.png)
I'm guessing this is just to do with linting sine it actually imports fine, perhaps I need to change the way the `import/no-unresolved` rule works?

Also, from your code: `root: [path.resolve(__dirname, 'src'), ......` I don't think `src` is necessary since you specify it below. Either remove it from here or better still, from the aliases you create to avoid duplication.

**Comment by mikedevita** [comment]
yeah probably not required, what's your config stuff look like  I'm looking at doing something similar for things like doc title and other things.

**Comment by fayimora** [comment]
@mikedevita btw did you get those eslint errors too?

Config currently looks like this:
```js
const setupConfig = (environment) => {
  const ENV = {
    API_URL: 'http://localhost:8090'
  };

  if(environment==='development'){
    ENV.API_URL = 'http://localhost:8090';
  }

  if(environment==='production'){
    // FIXME: Need to load this from the environment. process.env seems useless.. or not?
    ENV.API_URL = 'https://api.prod-url-from-env.com';
  }

  return ENV;
};

// export the resulting config
export default setupConfig(process.env.NODE_ENV);

```
Only thing missing is the ability to read actual environment variables in that config

**Comment by kwelch** [comment]
@fayimora It may be because of where your webpack config is stored. The variable `__dirname` resolves to the directory containing the file you are in. So you will need to use a path relative to that to resolve. 

Additionally, I would recommend making your `path.resolve(__dirname, 'src', ...)` into a function such as: 

```js
const srcResolve = (...args) => {
  return path.resolve(__dirname, 'src', ...args);
};
```

This give you one place to change if the directory structor changes.

**Comment by fayimora** [comment]
@kwelch Were you referring to my lint error? My webpack-config is still in the root directory as-is in slingshot.


> Additionally, I would recommend making your path.resolve(__dirname, 'src', ...) into a function such as:

@mikedevita I think this applies to your alias resolvers

**Comment by kwelch** [comment]
yes, but I did misread it slightly. If it import properly but lint doesn't like it you may be able to use the [lint resolver settings](https://github.com/benmosher/eslint-plugin-import#resolvers).

**Comment by mikedevita** [comment]
@fayimora yeah it applies to me, did you get your `process.env` working in your app config, i want to conditionally enable debug logging depending on the environment... and also conditionally change the api url...

**Comment by fayimora** [comment]
@mikedevita precisely the same thing I wanted to do but no luck yet. I'll have another pass at it today.

**Comment by mikedevita** [comment]
@kwelch i guess im a bit confused as to how i'd use that library to resolve eslint errors with aliased paths like 'reducers...

**Comment by kwelch** [comment]
The lint error you are getting is from a rule in that library. If you are looking to resolve it, you con review that section and use the [webpack resolver.](https://www.npmjs.com/package/eslint-import-resolver-webpack)

**Comment by mikedevita** [comment]
@kwelch @fayimora im still stumped on this... im using the config like this in `webpack.conf.dev.js`


```javascript

// removed for brevity
export default {
  resolve: {
    alias: {
      containers: resolvePaths('containers'),
      components: resolvePaths('components'),
      reducers: resolvePaths('reducers'),
      layouts: resolvePaths('layouts'),
      styles: resolvePaths('styles'),
      store: resolvePaths('store'),
      middleware: resolvePaths('middleware'),
      config: resolvePaths('config'),
    },
    extensions: ['', '.js', '.jsx', '.json']
  },
// removed for brevity
```

![image](https://cloud.githubusercontent.com/assets/2991640/22796452/99b9c76a-eeb7-11e6-8144-a27b13045e8f.png)

**Comment by nickytonline** [comment]
@mikedevita, do you have a repo with this config that we can look at?

**Comment by mikedevita** [comment]
@nickytonline https://github.com/mikedevita/gasloggr-frontend has it, build is a bit old but its essentially the same configs.

**Comment by kwelch** [comment]
Just to confirm you are only seeing lint error not any actual functional errors in the page?

**Comment by mikedevita** [comment]
Correct.

On Feb 9, 2017, at 1:03 PM, Kyle Welch <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to confirm you are only seeing lint error not any actual functional errors in the page?

**Comment by fayimora** [comment]
@mikedevita did you manage to load Env vars in your config file?? Tried a bunch of things but nothing worked.

**Comment by mikedevita** [comment]
i did, https://github.com/mikedevita/gasloggr-frontend/tree/master/src/config has an example of it.

and https://github.com/mikedevita/gasloggr-frontend/blob/master/src/containers/Navigation/index.js has an example of it in use.

**Comment by fayimora** [comment]
What yu have requires you to provide prod details in the config file though! soecifically this line
```js
API_URL: (environment === 'development') ? 'http://localhost:3000/v1' : 'https://api.gaslogger.io/v1',
```

I was trying to make something like:
```js
API_URL: (environment === 'development') ? 'http://localhost:3000/v1' : process.ENV.API_URL,
```

**Comment by mikedevita** [comment]
That will only work if you are running the react app as a nodejs app.

I use nginx to host the frontend which doesn’t have access to process.env.API_URL…


[logo_326x100]
Mike DeVita
E: mike@relative.media<mailto:mike@relative.media> | C: [602] 541-4137 | W: https://relative.media<https://relative.media/>

**Comment by arshdkhn1** [comment]
@fayimora I have been struggling with the same issue of injecting NODE_ENV variable somehow into the code but nothing has worked yet. Did you find any solution ?  

I tried using `cross-env` but that doesnt work.  If I try `cross-env NODE_ENV=production babel-node server.js` then it fails to transpile. I wonder why does it throw error ?

**Comment by arshdkhn1** [comment]
@kwelch Can you tell me why this script fails to run -> `"open:src": "NODE_ENV=production babel-node tools/server.js production",` or `"open:src": "cross-env NODE_ENV=production babel-node tools/server.js production",` 
When open:src runs then I get an error like `import is not valid keyword`, basically it fails to transpile the code of server.js.

**Comment by mikedevita** [comment]
Additionally, jest tests fail when using the global aliases like containers/foo i think because the tests dont load the aliases and dont know how to resolve them...

**Comment by arshdkhn1** [comment]
@fayimora I am facing a similar problem that you are facing. I am trying to add an express server that runs both webpack and some custom api stuff. I am using same file for both `production` and `development`. I loaded all the api keys and other stuff using `dotenv` but somehow I wasnt able to get the NODE_ENV value to decide which config to use for webpack middleware. 

As I told above, I tried to set NODE_ENV using these two options - 
`"open:src": "NODE_ENV=production babel-node tools/server.js"` 
` "open:src": "cross-env NODE_ENV=production babel-node tools/server.js"`
which failed.

So I thought of using `process.argv` to find the node_env.

My script looks like this -
``` js
"start": "npm-run-all --parallel test:watch open:src lint:watch",
    "open:src": "babel-node tools/server.js production",
    "open:dist": "babel-node tools/server.js development",
    "lint": "esw webpack.config.* src tools --color",
    "lint:watch": "npm run lint -- --watch",
    "clean-dist": "npm run remove-dist && mkdir dist",
    "remove-dist": "rimraf ./dist",
    "prebuild": "npm run clean-dist && npm run lint && npm run test",
    "build": "babel-node tools/build.js && npm run open:dist",
```
Now in my server.js file, I can check for environment via process.argv[2]
``` js

let config;
const app = express();
const server = http.createServer(app);

/* eslint-disable no-console */
console.log(chalkSuccess('Starting Express server...'));

if (process.argv[2] !== "production") {
  require('dotenv').load({path: path.resolve(process.cwd() ,".env")});
  config = devConfig;
} else {
  config = prodConfig;
}

const bundler = webpack(config);

```
