### ISSUE TITLE
[QUESTION] - How can I integrate Express into this starter kit?

### ISSUE THREAD

**Issue by mherodev** [coryhouse/react-slingshot#353]
Hey Cory

Coming from your React/Redux PluralSight course, I appreciated the integration with Express as it would allow me to setup `/proxy` routes for private requests that won't exist within our services, e.g. if I wanted to add these sort of auth paths to this sample: 

https://github.com/auth0-blog/nodejs-jwt-authentication-sample/blob/master/user-routes.js

However, I'm not certain how I can control server-side routing with react-slingshot, and I don't love the idea of generating a separate application to deal with the highly coupled proxy requests I'd likely need for performing secure operations.

Or maybe I'm thinking about this wrong. I'm having trouble wrapping my head around the separation between client and server requests, and how the front-end (bundle.js) would handle a request that the server could respond to.

Thanks for any help!

**Comment by kwelch** [comment]
I am using express for my Azure server. I explain the setup I have in [this comment](https://github.com/coryhouse/react-slingshot/issues/263#issuecomment-248697458) and the comments following it. 

I use a middleware for my proxy which I then apply in the `srcServer.js` the same way I would for an express server.

**Comment by mherodev** [comment]
Ah, that's where Express went. Thanks Kwelch.

**Comment by kwelch** [comment]
Closing. Feel free to reach out if there are any other questions.

**Comment by spartan082189** [comment]
I managed to get Express working in my app by using this code:

```javascript
import historyApiFallback from 'connect-history-api-fallback';
import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';
import {chalkSuccess} from './chalkConfig';
import config from '../webpack.config.dev';
import express from 'express';
import http from 'http';

const bundler = webpack(config);
const app = express();
const server = http.createServer(app);
console.log(chalkSuccess('Starting Express server...'));

app.use(express.static('src/*.html'));
app.use(historyApiFallback());
app.use(webpackHotMiddleware(bundler));
app.use(webpackDevMiddleware(bundler, {
    // Dev middleware can't access config, so we provide publicPath
    publicPath: config.output.publicPath,

    // These settings suppress noisy webpack output so only errors are displayed to the console.
    noInfo: false,
    quiet: false,
    stats: {
      assets: false,
      colors: true,
      version: false,
      hash: false,
      timings: false,
      chunks: false,
      chunkModules: false
    },

    // for other settings see
    // http://webpack.github.io/docs/webpack-dev-middleware.html
}));
server.listen(3000);
console.log(chalkSuccess('Express server is listening on port: ' + server.address().port));

```

Hopefully this helps someone out there.

Michael

**Comment by arshdkhn1** [comment]
@spartan082189 Thanks!

**Comment by arshdkhn1** [comment]
@kwelch I have `.env` file which i am trying to load but somehow it is not loading. I have `.env` file in root folder and server file in tools folder. When I tried to put `.env` file in tools folder, even then env file is not loading. Any thoughts how to load custom env vars?

**Comment by iwoork** [comment]
@spartan082189 where did you put that code and how to run it? thanks.
