### ISSUE TITLE
npm run build not working.

### ISSUE THREAD

**Issue by k2glyph** [coryhouse/react-slingshot#354]
Frontend@0.1.0 start-message /home/jenkins/frontend
> babel-node tools/startMessage.js

Starting app in dev mode...

> Frontend@0.1.0 start /home/jenkins/frontend
> npm-run-all --parallel open:src

> Frontend@0.1.0 open:src /home/jenkins/frontend
> babel-node tools/srcServer.js

[BS] Access URLs:
 -----------------------------------
       Local: http://localhost:3000
    External: http://10.128.0.2:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.128.0.2:3001
 -----------------------------------
[BS] Serving files from: src
[BS] Watching files...
[BS] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)
webpack built 6c0f718c64a8c51ad919 in 11902ms

ERROR in ENOENT: no such file or directory, scandir '/home/jenkins/frontend/node_modules/node-sass/vendor'
 @ ./src/styles.scss 4:14-179 13:2-17:4 14:20-185

ERROR in ENOENT: no such file or directory, scandir '/home/jenkins/frontend/node_modules/node-sass/vendor'
 @ ./~/font-awesome/css/font-awesome.css 4:14-154 13:2-17:4 14:20-160

ERROR in ENOENT: no such file or directory, scandir '/home/jenkins/frontend/node_modules/node-sass/vendor'
 @ ./~/flexboxgrid/css/flexboxgrid.css 4:14-153 13:2-17:4 14:20-159

ERROR in ENOENT: no such file or directory, scandir '/home/jenkins/frontend/node_modules/node-sass/vendor'
 @ ./~/bootstrap/dist/css/bootstrap.min.css 4:14-164 13:2-17:4 14:20-170
Child html-webpack-plugin for "index.html":

webpack: bundle is now VALID.

**Comment by nickytonline** [comment]
@k2glyph, can you provide a bit more information?

**Comment by nickytonline** [comment]
@k2glyph, does react-slingshot work fine locally if you build it without CI? This seems like a deployment issue. The error is pretty clear. The `/home/jenkins/frontend` directory does not exist. Check if Jenkins is configured properly. I'm assuming you're using the Git plugin and pulling your repo into that folder?

Also, instead of updating your comment, could you add a new comment when adding new information to issues? Thks.

**Comment by kwelch** [comment]
@k2glyph,

Are you still having issues with this? If so please, provide a more information so we can help provide a solution.

**Comment by k2glyph** [comment]
No have solve that by using express server to run the application in production mode.
Thank you.
