### ISSUE TITLE
Slingshot SEO

### ISSUE THREAD

**Issue by csprance** [coryhouse/react-slingshot#357]
Node version: v6.9.4

npm version:3.10.10

Operating system: Win 10 x64

Using the fetch as google tool I've noticed that any site made with react boilerplate just seems to be showing up as a black box and doesn't render any of the content. Beyond going with the server rendered method or something like prerender.io (but not excluding them, I'd be interested in any methods) is there any other things I can do to get my react content to render? This is partly a search engine issue and partly a developer issue so I'm interested in anything I can do as a developer.

I love the boilerplate, but I may need to add some server side rendering to deal with the SEO issue.

I noticed there wasn't an issue on the topic of SEO here so I figured I'd bring it up as an issue to discuss.

Any suggestions on how to improve the SEO using slingshot? Even if they're tricks/hacks.

**Comment by coryhouse** [comment]
I wouldn't suggest using this boilerplate if you care about SEO. I'd suggest choosing one with universal rendering out of the box. Many great options out there: http://andrewhfarmer.com/starter-project/
