### ISSUE TITLE
How to use gzip compression on the prod build? 

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [coryhouse/react-slingshot#359]
Node version:
v7.3.0
npm version:
3.10.10
Operating system:
WIndows 8 
Command line used:
npm run build
Steps to reproduce:
It is not a bug. I am trying to use gzip compression similar to the way you use it in your pluralsight course in the production build module in the last clip. However, one difference I notice between the starter there vs slingshot is the pluralsight course uses Express server while slingshot uses Browsersync. However, gzip compression can still be used, right? Or am I missing anything here? Thanks.

**Comment by coryhouse** [comment]
There's no need to use gzip compression within slingshot since that's a production webserver configuration. I only showed how to configure Express for gzip locally so we could see how small the size would be in production. 

That said, something like this should work if you want to run gzip on Browsersync: https://github.com/BrowserSync/browser-sync/issues/451

**Comment by Rajiv-Kulkarni** [comment]
Thanks. That reduced the bundled js size from 535kb to 144kb. However, the file size in the dist folder is still 535kb. Sorry if I sound stupid here, but not sure why. Also, I did not understand when you said "There's no need to use gzip compression within slingshot since that's a production webserver configuration."., could you elaborate a little if I am not asking for too much? Thanks.

**Comment by coryhouse** [comment]
Slingshot creates some static files that you'll host elsewhere. So it's the production webserver that really needs to have gzip enabled.

**Comment by Rajiv-Kulkarni** [comment]
I see. Thanks. So in order to deploy my app to production I need to run: npm run build and copy whatever the files created (including the unzipped bundle.js) inside the dist folder to the production server (which could be express, borwsersync or any other kind and enabled for gzip) and it will do the magic? Also the compression happens only during serving a web page to the browser? Please feel free to stop me or stop answering since there is no end to my stupidity. Hopefully my last question on this thread. Thanks.

**Comment by coryhouse** [comment]
correct on both, except browsersync isnt for prod.

**Comment by Rajiv-Kulkarni** [comment]
Ah ok thanks. I also looked at closed issue #215.

**Comment by mikedevita** [comment]
agreed its the actual web server that youre using to host the static content that should be configured for gzip.. i.e. nginx

**Comment by rpkRED** [comment]
Hi, in what way can i do that if i'm deploying my app on azure?

**Comment by nickytonline** [comment]
@rpkRED, I'd suggest looking at the [Azure Web Apps documentation](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-overview).

**Comment by kwelch** [comment]
If you have questions I have deployed a slingshot like boilerplate to Azure with slots and the whole nine.

**Comment by rpkRED** [comment]
@kwelch yes please I would appreciate your help. I have read doc that @nickytonline provided but with no help. I have found part about Troubleshooting CDN file compression https://docs.microsoft.com/en-us/azure/cdn/cdn-troubleshoot-compression. And I check it in my application as shown here: 
![gziprespreq](https://user-images.githubusercontent.com/13489953/38373068-9a3c41fc-38f0-11e8-9b79-c85247647a4d.jpg).
So i'm not sure what is next step for me to do to enable compression as I can see from response header it is not set? Correct me if i'm wrong.
