### ISSUE TITLE
What's the best way to add configuration to this project?

### ISSUE THREAD

**Issue by mherodev** [coryhouse/react-slingshot#360]
I was hoping to add `node-config` as I've used it in other projects, but I'm running into errors:

https://github.com/lorenwest/node-config/issues/380

Is there a recommended library for configuration?

**Comment by kwelch** [comment]
There errors mentioned there are all of dependencies missing. Have you tried running yarn? Are those dependencies of that package?

This does not appear to be related to slingshot.

**Comment by mherodev** [comment]
Those are all of the dev dependencies of that package:

```
"devDependencies": {
    "coffee-script": ">=1.7.0",
    "cson": "^3.0.1",
    "hjson": "^1.2.0",
    "js-yaml": "^3.2.2",
    "properties": "~1.2.1",
    "toml": "^2.0.6",
    "underscore": "^1.8.3",
    "vows": ">=0.8.1",
    "x2js": "^2.0.1"
  }
```

I have tried running `yarn` but it only seems to resolve the non-dev dependencies.

**Comment by mherodev** [comment]
And I agree that this bug isn't related to slingshot, I'm mostly curious if there's a slingshot-friendly alternative for setting up configuration.

**Comment by mherodev** [comment]
Ah, after digging, this looks to be an ES6 issue with `node-config`. Once that's resolved, it'll work for me again :D

**Comment by kwelch** [comment]
Another option might be [dotenv](https://github.com/motdotla/dotenv). Hopefully that helps.
