### ISSUE TITLE
Publish 6.0 release

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#365]
@nickytonline @kwelch - I've drafted the [6.0 release notes](https://github.com/coryhouse/react-slingshot/releases/edit/untagged-8e1da0d0d11d260663bf). Anything big you suggest adding to the list that I've missed. 168 commits to cover! 💯

**Comment by nickytonline** [comment]
Hmm... @coryhouse, I get a 404 when going to the release notes.

**Comment by nickytonline** [comment]
Nevermind. I just found it on the releases page.

**Comment by coryhouse** [comment]
Oops: https://github.com/coryhouse/react-slingshot/releases

**Comment by nickytonline** [comment]
Looks good to me. I can't believe we're at version 6.0 and almost 6K ⭐️!

**Comment by kwelch** [comment]
I agree it looks good. What an amazing list of changes! Nice work, all!

**Comment by coryhouse** [comment]
Excellent, published! Thanks so much gents!
