### ISSUE TITLE
SASS (indented syntax) extension catch not added in webpack config files.

### ISSUE THREAD

**Issue by arshdkhn1** [coryhouse/react-slingshot#369]
I noticed that sass indented version extension is not added in webpack config files.

**Comment by coryhouse** [comment]
Sorry, I'm not familiar. What's that? Have a link?

**Comment by arshdkhn1** [comment]
@coryhouse sass's pug like indented syntax whose file extension is `.sass` - http://sass-lang.com/documentation/file.INDENTED_SYNTAX.html

There is still a large audience who uses/loves this syntax. I would like to make a pr if you like to add it.

**Comment by coryhouse** [comment]
Ah! Yes, i'm open to a PR assuming the change is simple. Thanks!

**Comment by arshdkhn1** [comment]
#372
