### ISSUE TITLE
Typescript support: What happens to index.ejs?

### ISSUE THREAD

**Issue by rajivkulkarni** [coryhouse/react-slingshot#370]
Node version:
Latest
npm version:
latest
Operating system:
Windows 7/8
Command line used:

Steps to reproduce:
Not a bug. Was wondering if I add support for Typescript to react-slingshot, what happens to the index.ejs. Can it stay as it is? I don't see any .ets template available for typescript. Thanks.

**Comment by nickytonline** [comment]
@rajivkulkarni, it doesn't affect TypeScript. It's simply a template file used to generate the index.html. You could call it anything as long as the name is the same in the webpack config.

**Comment by nickytonline** [comment]
i.e. https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.dev.js#L31
