### ISSUE TITLE
Add React Storybook

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#371]
I use [React Storybook]( https://github.com/storybooks/react-storybook) at work and on some personal projects. I find it very handy for building and testing components visually. @coryhouse, @kwelch, do you think this would be a good add to react-slinghot, or would you consider it out of the scope of the project?

**Comment by coryhouse** [comment]
I'm a fan of it as well. Though I'm currently considering moving to [Bluekit](http://bluekit.blueberry.io). Really like how it autogenerates, shows the code, and offers interactivity for free on all props. Super slick.

That said, there's also [react styleguidist](https://github.com/styleguidist/react-styleguidist). And Walmart's [electrode docgen](http://www.electrode.io/docs/generate_docs.html).

My fav of the bunch at the moment is Bluekit. Needless to say, too many options to justify taking a clear opinion at this point. But I'm digging into these in detail in my upcoming course. :)

**Comment by kwelch** [comment]
Agreed, I think these libraries IMO are better used for a component library, than application testing. 

Honestly, I have not used any of them yet, but I am aware of their abilities.

**Comment by nickytonline** [comment]
Cool, thanks for mentioning those alternatives. I'll check them out.

**Comment by nickytonline** [comment]
@coryhouse,  I just looked at Bluekit. It looks amazing.

**Comment by coryhouse** [comment]
Pull it into your existing project. It just magically finds all your components and generates interactive pages that let you toggle props. Super cool. I was building this, then found it and couldn't decide whether to 🎉 or 😢
