### ISSUE TITLE
`async function` and `await` is not supported

### ISSUE THREAD

**Issue by blusewang** [coryhouse/react-slingshot#373]
Node version:
v6.9.5
npm version:
3.10.10
Operating system:
Darwin MacBook-Pro.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64
Command line used:
npm start
Steps to reproduce:

**Comment by coryhouse** [comment]
I'm running the same config and cannot reproduce. Can you provide the exact command line output?

**Comment by blusewang** [comment]
I have fixed it!
code is:
`const test = ()=> new Promise((a,b)=>{
  setTimeout(()=>{
    a('string')
  },1000)
})
async function abc(){
  const a = await test()
  console.log(a)
}
abc()`
exception is:
`Uncaught ReferenceError: regeneratorRuntime is not defined`

just run:
`npm install babel-plugin-transform-runtime --save-dev`
add change babel config like:
`
"presets": [
    "react",
    "es2015",
    "stage-1"
  ],
`

**Comment by blusewang** [comment]
I don't down why,but it worked!  \ -_-/!

**Comment by coryhouse** [comment]
Ah, that's because our config doesn't support async/await out of the box because it requires babel polyfill, which we're not including at the moment. http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await

**Comment by usamamashkoor** [comment]
@coryhouse can you please let us know how we use aysnc and await in react slingshot...?

**Comment by kwelch** [comment]
The `babel-polyfill` packages is required to get it working. See the answer in the link Cory posted for more details.

**Comment by usamamashkoor** [comment]
Thanks @kwelch for replying so we will have to run this npm command 
`npm i -D babel-core babel-polyfill babel-preset-es2015 babel-preset-stage-0 babel-loader`

do i need to add anything in my babel env of production and development presets..?
and where do we add this code...?
```
require("babel-core/register");
require("babel-polyfill");
```
and what about this code to where do i put this.
```module.exports = {
  entry: ['babel-polyfill', './test.js'],

  output: {
    filename: 'bundle.js'       
  },

  module: {
    loaders: [
      { test: /\.jsx?$/, loader: 'babel', }
    ]
  }
};
```
i am new to react so sorry for the trouble.

**Comment by kwelch** [comment]
I prefer to update the entry (second code block). This would be within your [`webpack.config.prod.js`](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.prod.js#L19). 

The first block would be placed inside your [`index.js`](https://github.com/coryhouse/react-slingshot/blob/master/src/index.js) similar to `require('./favicon.ico');`.
