### ISSUE TITLE
Error: react-slingshot@5.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`

### ISSUE THREAD

**Issue by aperritano** [coryhouse/react-slingshot#374]
I'am unable to start the server via npm run start. It was working fine, until i needed to restart it. Any ideas of a work around? 

Node version:
node v7.5.0
npm version:

npm  v4.1.2
Operating system:
osx 12.4 Beta (16E154a)
Command line used:

bash
Steps to reproduce:

npm run start

out: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.5.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-slingshot@5.0.0~prestart: react-slingshot@5.0.0
6 verbose lifecycle react-slingshot@5.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle react-slingshot@5.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/aperritano/Dropbox/dev/uic-phd-dev/research/disseration/parse_json_data/node_modules/.bin:/Users/aperritano/anaconda/bin:/Users/aperritano/.rvm/gems/ruby-2.3.0/bin:/Users/aperritano/.rvm/gems/ruby-2.3.0@global/bin:/Users/aperritano/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aperritano/.rvm/bin:/Users/aperritano/.rvm/bin
8 verbose lifecycle react-slingshot@5.0.0~prestart: CWD: /Users/aperritano/Dropbox/dev/uic-phd-dev/research/disseration/parse_json_data
9 silly lifecycle react-slingshot@5.0.0~prestart: Args: [ '-c', 'npm-run-all --parallel start-message' ]
10 silly lifecycle react-slingshot@5.0.0~prestart: Returned: code: 0  signal: null
11 info lifecycle react-slingshot@5.0.0~start: react-slingshot@5.0.0
12 verbose lifecycle react-slingshot@5.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle react-slingshot@5.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/aperritano/Dropbox/dev/uic-phd-dev/research/disseration/parse_json_data/node_modules/.bin:/Users/aperritano/anaconda/bin:/Users/aperritano/.rvm/gems/ruby-2.3.0/bin:/Users/aperritano/.rvm/gems/ruby-2.3.0@global/bin:/Users/aperritano/.rvm/rubies/ruby-2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aperritano/.rvm/bin:/Users/aperritano/.rvm/bin
14 verbose lifecycle react-slingshot@5.0.0~start: CWD: /Users/aperritano/Dropbox/dev/uic-phd-dev/research/disseration/parse_json_data
15 silly lifecycle react-slingshot@5.0.0~start: Args: [ '-c',
15 silly lifecycle   'npm-run-all --parallel test:watch open:src lint:watch' ]
16 silly lifecycle react-slingshot@5.0.0~start: Returned: code: 1  signal: null
17 info lifecycle react-slingshot@5.0.0~start: Failed to exec start script
18 verbose stack Error: react-slingshot@5.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:192:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:192:7)
19 verbose pkgid react-slingshot@5.0.0
20 verbose cwd /Users/aperritano/Dropbox/dev/uic-phd-dev/research/disseration/parse_json_data
21 error Darwin 16.5.0
22 error argv "/usr/local/Cellar/node/7.5.0/bin/node" "/usr/local/bin/npm" "run" "start"
23 error node v7.5.0
24 error npm  v4.1.2
25 error code ELIFECYCLE
26 error react-slingshot@5.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch`
26 error Exit status 1
27 error Failed at the react-slingshot@5.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the react-slingshot package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     npm-run-all --parallel test:watch open:src lint:watch
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs react-slingshot
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls react-slingshot
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by kwelch** [comment]
Did you make updates to the test script? There are known issues with our out of the box test script and node v7.

**Comment by nickytonline** [comment]
@aperritano, see #366 .

**Comment by aperritano** [comment]
Thanks, I was able to fix this by rolling back  node 6.9 and deleting my node_modules dir, then running setup and run.

**Comment by kwelch** [comment]
Closing as issue is related to v7 and issues with v7 are noted in #366
