### ISSUE TITLE
cannot get values from redux store

### ISSUE THREAD

**Issue by onurhanavci** [coryhouse/react-slingshot#375]
Node version: v7.5

npm version:

Operating system: windows 10

Command line used:

Steps to reproduce:

i can't get userService as a prop to my container component. when i open the redux dev tools ican see that userService is part of my state. any ideas?

also this.props.actions is null too :(

`function mapStateToProps(state) {
    return {
        userService: state.userService      
    };
}

function mapDispatchToProps(dispatch) {
    return {
        actions: bindActionCreators(userActions, dispatch)
    };
}

export default connect(mapStateToProps, mapDispatchToProps)(LoginContainer);`

**Comment by tarim** [comment]
Hi @onurhanavci ,

same problem here, how did you fix it?

Thanks,

**Comment by onurhanavci** [comment]
export class LoginContainer extends React.Component {

just removed the export here.

class LoginContainer extends React.Component {

**Comment by mikedevita** [comment]
couple troubleshooting things to try.

1. in mapStateToProps function `console.log(state);`


## ES5 syntax
```javascript
function mapStateToProps (state) {
  console.log(state);
  return {
    userService: state.userService
  }
};
```

## ES6/2015 Syntax
```javascript
const mapStateToProps = (state) => {
  console.log(state);
  return {
    userService: state.userService
  }
};
```
