### ISSUE TITLE
I have dynamic defined `onForeground` in `appConnector` object,but builder crashed!

### ISSUE THREAD

**Issue by blusewang** [coryhouse/react-slingshot#376]
/Users/bluse/www/project/react-slingshot/src/actions/status.js (3/18)
  !   5:48  Missing semicolon                                               semi
  !   6:58  Missing semicolon                                               semi
  !   9:3   Unexpected console statement                                    no-console
  !   9:41  Missing semicolon                                               semi
  !  10:2   Missing semicolon                                               semi
  !  16:4   Missing semicolon                                               semi
  !  17:2   Missing semicolon                                               semi
  ✖  21:18  'onForeground' not found in imported namespace 'appConnector'   import/namespace
  !  23:59  Missing semicolon                                               semi
  !  24:44  Missing semicolon                                               semi
  !  26:7   Missing semicolon                                               semi
  ✖  27:18  'onBackground' not found in imported namespace 'appConnector'   import/namespace
  !  29:60  Missing semicolon                                               semi
  !  30:45  Missing semicolon                                               semi
  !  32:7   Missing semicolon                                               semi

**Comment by blusewang** [comment]
I known this checker is helpful! 
but I have to define these functions in dynamic. else I will do lot of work in copy and paste!

**Comment by blusewang** [comment]
hope somebody help me soon!

**Comment by blusewang** [comment]
I got it!

**Comment by blusewang** [comment]
but how to delete this issue

**Comment by mikedevita** [comment]
you cant delete it, @coryhouse has to, you can just mark it closed and itll "fall" (filter) off the list.
