### ISSUE TITLE
Using Promises with babel-polyfill

### ISSUE THREAD

**Issue by CoderJoeIO** [coryhouse/react-slingshot#377]
I've been trying to set up babel-polyfill and a few others in order to be able to use Promise in <=IE11, but I haven't been successful, is there a way to set this up with the current configuration?

**Comment by kwelch** [comment]
I am using `babel-polyfill` along with the snippet below to ensure Promise support

```
import Promise from 'promise-polyfill';

// add support for promises in IE
if (!window.Promise) {
  window.Promise = Promise;
}
```
