### ISSUE TITLE
Add links to the top of the FAQ

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#379]
The [FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md) would be more useful if we added a list of questions at the top with links to each question. 

Great first pull request for someone new...

**Comment by tmxyz** [comment]
I'm not sure I understand how it should differ from the current FAQ. There is already a list of questions with links at the top.

**Comment by coryhouse** [comment]
Someone beat ya to it.  :) Thanks though!

**Comment by tmxyz** [comment]
That was fast 😄
