### ISSUE TITLE
undefined function as prop

### ISSUE THREAD

**Issue by onurhanavci** [coryhouse/react-slingshot#382]
i pass two functions to my child component:

<TabHeader
                    key={tab.tabId}
                    tab={tab}
                    index={index}
                    activeTabIndex={activeTabIndex}
                    goToTabf={() => { this.goToTabf }}
                    closeTabf={() => { this.closeTabf }}
                />

and in the child component when i want to call this function:

<a onClick={function() { goToTabf(tab.tabId); }}

i get this error:

Uncaught TypeError: Cannot read property 'closeTabf' of undefined

is it possible that it is related to anchor tag or am i missing something?

**Comment by coryhouse** [comment]
Please direct specific React questions to StackOverflow.
