### ISSUE TITLE
[Question] Whats all involved to move tests to a ./tests/ folder?

### ISSUE THREAD

**Issue by mikedevita** [coryhouse/react-slingshot#383]
this isn't the right place I am assuming to ask this but... right now with react-slingshot tests are bundled with the actual components, reducers, and such in `src/` but I wanted to move them out to something like below...what all is involved to accomplish this?

```
./fooproject/
  - src/
    - components/
      - Component1.jsx
  - tests/
    - components/
      - Component1.test|spec.jsx
```

**Comment by nickytonline** [comment]
Refer to the [Jest documentation](https://facebook.github.io/jest/docs/getting-started.html#additional-configuration) for more explanation, but basically add another property to the jest property in package.json like this, https://github.com/nickytonline/ts-react-starter/blob/master/package.json#L29

**Comment by mikedevita** [comment]
thanks @nickytonline
