### ISSUE TITLE
Bump sass-loader version

### ISSUE THREAD

**Issue by ryannealmes** [coryhouse/react-slingshot#384]
This isn't so much an issue rather than prompting to update a dependency in the package.json file.

Specifically

` "sass-loader": "4.1.0"`

I tried to install bootstrap v4 and was running into an error 

`Module build failed: Error: "../bootstrap/scss/_normalize.scss" is not in the SourceMap.`

After updating to the latest version of sass-loader

`"sass-loader": "6.0.2"`

Things started working.

I know this isn't a problem with this repo, but after seeing the sass-loader was 2 versions behind, I thought I recommend a version bump.

**Comment by coryhouse** [comment]
Thanks for the heads up. Would you be willing to submit a PR?

**Comment by ryannealmes** [comment]
Sure.

**Comment by ryannealmes** [comment]
Pls see PR

https://github.com/coryhouse/react-slingshot/pull/385

Seems like there are conflicts. I haven't done too many PRs from my repo into other peoples repos. Let me know if there is anything else I need to do.

**Comment by kwelch** [comment]
Closing, we can continue conversation in #385
