### ISSUE TITLE
How do I add script and stylesheet to global scope?

### ISSUE THREAD

**Issue by kitgary** [coryhouse/react-slingshot#387]
I just get started and I want to add a script and css styles to global scope, can I just add them to the index.ejs? Or any other better ways to do this?

Ths

**Comment by kwelch** [comment]
You can import css into global scope using the method from [line 10 of index.js](https://github.com/coryhouse/react-slingshot/blob/master/src/index.js#L10)

It will then be bundled in webpack and exported as a separate `.css` using the [`ExtractTextPlugin` in the webpack.prod.config](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.prod.js#L35)

As you state you could also simply add a line in the `index.ejs`. 

😄
