### ISSUE TITLE
How do I add bootstrap.js?

### ISSUE THREAD

**Issue by kitgary** [coryhouse/react-slingshot#388]
I am trying to integrate bootstrap to the project, and I use
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
in the index.js

but I have no idea how to add the bootstrap.min.js to the project, any idea?

Ths

**Comment by kwelch** [comment]
you could use the similar import pattern you have used for the css. 

However, there is also [bootstrap-loader](https://github.com/shakacode/bootstrap-loader) and also [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) which both allow for a more (module|react|customizable) experience. 

I will leave this open, as I know @coryhouse used bootstrap and may have further insight.

**Comment by kwelch** [comment]
I used the loader and it worked well, but did feel a little magical.

**Comment by kwelch** [comment]
@kitgary What this able to help you out? Should we keep this issue open?

**Comment by raythree** [comment]
If you don't want to use the loader all you need to do is make sure jquery is loaded before bootstrap.js, so you can do this in your index.js:
```
window.jQuery = window.$ = require('jquery/dist/jquery.min');
require('bootstrap/dist/js/bootstrap.min.js');
```

**Comment by bernabe9** [comment]
@kitgary If you want to integrate bootstrap with your React app the best appoach it's using [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap)

**Comment by kwelch** [comment]
Closing as they has been adequately answered. @kitgary if you are still having issue feel free to reach out.

**Comment by ryannealmes** [comment]
[Bootstrap-loader](https://github.com/shakacode/bootstrap-loader) works like a charm and the documentation is great. It supports v3 and v4.

**Comment by markjackson02** [comment]
Bootstrap now includes documentation on how to add it to your project using Webpack https://getbootstrap.com/docs/4.0/getting-started/webpack/
