### ISSUE TITLE
Separate configuration and createStore files

### ISSUE THREAD

**Issue by edtoken** [coryhouse/react-slingshot#389]
We use your product react-slingshot in production, thanks.
But, we have problem.

Support two webpack config files - this is the place where at some point necessarily someone forgets to add something. 

Our front-end developer also create two createStore files createStore.dev and createStore.prod

I think, if we have only webpack.config.js and createStore.js (without division into 2 files) It is more comfortable.

What do you think about this?
If you think it's a good idea, I would like to do a pull reguest for its implementation.

I've done it many times and if you are really interested, I would like to share with you and to hear your opinion.

**Comment by kwelch** [comment]
First off, we appreciate your feedback and are glad that is has helped. The slingshot is intended to get up and running quickly. It is completely up to your team to customize it. So if merging it feels better for your team. 

_Here my notes on those files in particular:_
The store we have already merged into one file, this was necessary for the move to webpack 2. 

In my opinion, the webpack files are both very similar but far too different to be able to merge them. I find it necessary to keep them separate for clarity and separation of mindset.

**Comment by coryhouse** [comment]
The webpack files were unified awhile back, but there were many requests to separate them for readability and clarity so we did so. Agreed that there's no right answer, but we'll likely leave as is for now. Thanks for the thoughtful suggestions!
