### ISSUE TITLE
npm run build not working

### ISSUE THREAD

**Issue by JMIsham** [coryhouse/react-slingshot#391]
Node version:

npm version:

Operating system:

Command line used:

Steps to reproduce:

**Comment by JMIsham** [comment]
hi. me too having similar problem.. when i try to run the command "npm run build" there is an error like this.. can any one please help


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\nod
e_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! new-project@0.1.0 lint: `esw webpack.config.* src tools --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-project@0.1.0 lint script 'esw webpack.config.* src tool
s --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the new-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     esw webpack.config.* src tools --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs new-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls new-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xampp\htdocs\AboutgccFront2\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\nod
e_modules\\npm\\bin\\npm-cli.js" "run" "prebuild"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! new-project@0.1.0 prebuild: `npm run clean-dist && npm run lint && npm run
 test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-project@0.1.0 prebuild script 'npm run clean-dist && npm
 run lint && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the new-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean-dist && npm run lint && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs new-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls new-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xampp\htdocs\AboutgccFront2\npm-debug.log

**Comment by coryhouse** [comment]
@JMIsham Please try this list: https://github.com/coryhouse/react-slingshot#having-issues-try-these-things-first

**Comment by JMIsham** [comment]
Hi, thank you very much for the reply. I figured it out.. there were some
warnings about not using the imported items.. after commenting all
unnecessary imports it worked... thank you for replying..

**Comment by kwelch** [comment]
Great, If the issues persists please feel free to submit a new issue. Glad it worked out.
