### ISSUE TITLE
new version of React-Router?

### ISSUE THREAD

**Issue by richardvaldiviesomacias** [coryhouse/react-slingshot#394]
There is a major change with the new version of React-Router. Is any update on the horizon?

Not an issue, just a conversation

Thanks,

Richard

**Comment by mikedevita** [comment]
there is a PR already submitted for it.

**Comment by nickytonline** [comment]
I'm OK with upgrading, but I'll let @coryhouse make the call as a tonne changed in RR4.

**Comment by kwelch** [comment]
I am closing this, any further conversation can continue within the PR #393. 

Thank you. 👍
