### ISSUE TITLE
Can't resolve paths from index.html after npm run build

### ISSUE THREAD

**Issue by IlyaMurashov** [coryhouse/react-slingshot#397]
After building an app into `/dist` folder `index.html` references all resources (minified .css, .js and images) as `/resource_name` instead of `./resources_name`. Manually replacing `/` to `./` in `webpack.config.prod.js:output.publicPath` or in `index.html` fixes the problem.

Am I doing something wrong that I have to do it manually?

P.S. The issue does not affect the dist server.

Node version: 6.9.2

npm version: 3.10.9

Operating system: macOS 10.12.3

Command line used: npm run build (excluded linting and testing)

Steps to reproduce: npm run build

**Comment by mnoleto** [comment]
You should change the public path in webpack.config.prod.js: https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.prod.js#L23

**Comment by kwelch** [comment]
Could you post more of a snippet of the code? It is hard to tell if that is intended or not.

**Comment by IlyaMurashov** [comment]
@kwelch sure!

Here's `index.html` generated by `build`:
```html
<!DOCTYPE html><html lang="en"><head><link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta charset="utf-8"/><title>Twitch viewer</title><link href="/main.bacb06aca645ee7750eca079e5cdd5a2.css" rel="stylesheet"></head><body><div id="app"></div><script type="text/javascript" src="/main.b84f0f779039c8fa6496.js"></script></body></html>
```

`href` for the CSS bundle and `src` for the js bundle start with `/` which results in 404 when I run it "in production" or on the local server.
If the `publicPath` is changed from `/` to `./` (as suggested by @mnoleto and mentioned in the first post) it works properly.

**Comment by kwelch** [comment]
I am glad to hear that, that worked for you. It does seem odd as both slingshot and my configuration I am unable to replicate what you are saying. 

Even further, it is odd that only the css would 404 but the `main.js` would render properly. 

Is this happening on your machine with a clean clone of slingshot?

**Comment by IlyaMurashov** [comment]
@kwelch 
I probably didn't explain myself properly, sorry for that. All of the resources ref'd from `index.html` give 404, including `main.js`, `main.css`, and a png image that is referenced from `main.js` bundle. I've deleted some changes from the original clone, but I cannot think of anything that could affect the path resolution. I'll do more testing on a completely clean clone and post it here.

It was pretty straightforward to fix and thank you guys for helping. However, I wasn't able to find anything in FAQ so I decided to bring it up here.

**Comment by kwelch** [comment]
I would appreciate a PR to update the docs. I am glad it is working. Do you feel this is a direct bug in slingshot? If not is this be available to be closed.

**Comment by IlyaMurashov** [comment]
@kwelch 
I'll try to do some more testing over the weekend to make sure that it's not my fault. Hope it can wait a couple of days.

**Comment by kwelch** [comment]
No rush at all. I only ask to help ensure we are able to help the next user that comes across this. 
Thank you for you time.

**Comment by IlyaMurashov** [comment]
@kwelch 
I figured out what my problem was. When serving `dist` folder to either GitHub Pages or on a local server (I'm using the server provided with WebStorm) I had no control over the location of the served files. E.g. on Github `/repo-name/` was appended and I missed this point. As the result, all minified files were requested from `/main.js(.css)' in the `index.html` instead of `/repo-name/main.js`.

Is there a good reason to use the absolute path (`/`) in this case? I think that a relative path (`./` or `''`) would be more logical since the webpack is configured to bundle everything to one folder anyways. Am I missing something?

P.S. if you find it useful I'd like to make a PR. It'd be my first commit to an open source project ever ;)

**Comment by kwelch** [comment]
I defer to @coryhouse. I think there is value in having a how to deploy section to the docs.

**Comment by coryhouse** [comment]
I agree that a deploy section would be useful, and likely expose us to opportunities for improvement. I'd welcome a related PR.

**Comment by IlyaMurashov** [comment]
I created [a short note](https://github.com/coryhouse/react-slingshot/pull/415) in FAQ on this topic.

**Comment by Zitle-Nancy** [comment]
Hi
