### ISSUE TITLE
Support Aliases for imports relative to root

### ISSUE THREAD

**Issue by mikedevita** [coryhouse/react-slingshot#398]
I have addressed this in #352 but the issue was closed as my question that I posted was somewhat unrelated.

I have the defined the aliases in webpack.config.dev.js and it *mostly* works. I am receiving lint errors, and tests are failing.

Can someone provide a somewhat detailed explanation on how to resolve theses issues and implement aliases relative to the `src/` path? I am completely lost and would prefer to not have to use absolute paths such as `../../../config` lol. 

I would be happy to submit a PR once its working, if @coryhouse feels this is an appropriate direction for the kit.

----

**webpack.config.dev.js**
```javascript
// ...removed for brevity
const resolvePaths = (...args) => {
  return path.resolve(__dirname, 'src', ...args);
};

export default {
  resolve: {
    extensions: ['*', '.js', '.jsx', '.json'],
    alias: {
      containers: resolvePaths('containers'),
      components: resolvePaths('components'),
      reducers: resolvePaths('reducers'),
      layouts: resolvePaths('layouts'),
      styles: resolvePaths('styles'),
      store: resolvePaths('store'),
      middleware: resolvePaths('middleware'),
      config: resolvePaths('config')
    },
  },
// ...removed for brevity
```

**src/components/Home/index.spec.js**
```javascript
import React from "react";
import config from 'config';

console.log(config);
const Home = () => (<div className="HomeComponent">
  <h1>Home Component</h1>
</div>);

Home.propTypes = {};
Home.defaultProps = {};
Home.defaultProps = {};
export default Home;

```

**src/components/Home/index.js**
```javascript
import React from 'react';
import {shallow} from 'enzyme';
import HomeComponent from './index';

describe('<HomeComponent />', () => {
  it('should display the Home Component', () => {
    const wrapper = shallow(<HomeComponent />);
    const actual = wrapper.find('.HomeComponent > h1').text();
    const expected = 'Home Component';
    expect(actual).toEqual(expected);
  });
});

```

the lint errors i get are: 
![image](https://cloud.githubusercontent.com/assets/2991640/24416157/b19acd24-1398-11e7-9d0a-bd73b4f75d0d.png)

and my tests fail because it doesn't know where "config" is located at. So it seems tests are breaking too..
![image](https://cloud.githubusercontent.com/assets/2991640/24416252/fbc8989a-1398-11e7-8d91-a343c3e03e44.png)

**Comment by mikedevita** [comment]
bit of an update, i got tests working by installing the `babel-plugin-module-resolver` and adding in my `.babelrc` this to my development, test, production `env` :

```json
      "plugins":[
        ["module-resolver", {
          "root": ["./src"],
          "alias": {
            "containers": "./src/containers",
            "components": "./src/components",
            "reducers": "./src/reducers",
            "layouts": "./src/layouts",
            "styles": "./src/styles",
            "store": "./src/store",
            "middleware": "./src/middleware",
            "config": "./src/config",
          }
        }]
      ]
```

however, it seems import/no-unresolved is still occuring with esw/linting.

![image](https://cloud.githubusercontent.com/assets/2991640/24417326/db7edb0e-139c-11e7-86a1-799b12e124ba.png)

**Comment by mikedevita** [comment]
Alright last update, I think... I have it working.

I installed `eslint-import-resolver-babel-module` and `babel-plugin-module-resolver` and in my `.eslintrc` I added  the import plugin, and the import/resolver settings.


```json
  "settings": {
    "import/resolver": {
      "babel-module": {}
    }
  },
  "plugins": [
    "react",
    "import"
  ],
```

it resolved my imports/no-unresolved and tests work fine... anyone else see any issues with this process?

**Comment by kwelch** [comment]
I have done aliasing, however my edits were summarized in the webpack config and the jest config. I did not have any lint error, so I am no help there. 

That being said the steps you took appear to be accurate based on my past research of this.

**Comment by mikedevita** [comment]
thanks @kwelch is this something you think would be along the path for the kit to include as a PR? If so I can clean things up and submit a PR for it.

**Comment by coryhouse** [comment]
Your approach makes sense, but I'd like to leave this out since alias isn't
a common use case and it may just create confusion. That said, I'd welcome
a pr that updates the docs to link to this issue so people can see how to
do so.

**Comment by mikedevita** [comment]
@coryhouse ill get a PR submitted shortly. thanks.

**Comment by mikedevita** [comment]
as an FYI there is an article on medium about absolute paths and create-react-app you can see it [here](https://medium.com/@ktruong008/absolute-imports-with-create-react-app-4338fbca7e3d).

**Comment by sag1v** [comment]
Unfortunately this solution not working for me with `react-slingshot`  😞
