### ISSUE TITLE
Error on npm start -s "missing class properties transform" using ES6 style classes

### ISSUE THREAD

**Issue by mikedevita** [coryhouse/react-slingshot#399]
**Node version:** 6.10.1

**npm version:** 3.10.10

**Operating system:** OS X Sierra

**Command line used:**  npm start -s

**Steps to reproduce:**
create an ES6 Class like so, and run npm start -s. An error is produced claiming "missing class properties transform". This happens for both propTypes, defaultProps, contextTypes and any custom methods/properties I have defined (like _updateDocumentTitle).

```javascript
class Navigation extends React.Component {
  static propTypes = {};
  static defaultProps = {};
  static contextTypes = {
    router: object.isRequired
  }

  componentDidMount () {
    this._updateDocumentTitle();
  }

  componentDidUpdate () {
    this._updateDocumentTitle();
  }

  _updateDocumentTitle = () => {
    // .. do some junk
  }

  render () {
    return (<span>Foo</span>);
  }
}
```

![screen shot 2017-03-28 at 11 35 55 am](https://cloud.githubusercontent.com/assets/2991640/24421349/c94d1460-13aa-11e7-81c4-9fb1c6662561.png)

**Comment by kwelch** [comment]
What is your babel setup look like?

**Comment by mikedevita** [comment]
not sure what information specifically you need but this is a clone of the repo as of 7AM MST this morning... so whatever that setup is like :).

**Comment by mikedevita** [comment]
looks like installing `transform-class-properties` and adding it to my plugins for development, test, production env in `.babelrc` fixed the issue.

**Comment by kwelch** [comment]
Yeah that is why I asked. Glad you were able to get that situated. I use that on my personal project, but slingshot does not come with it out of the box.

**Comment by mikedevita** [comment]
now to just how to figure out how to start testing my navigation component to make sure routes are rendered accordingly... need to learn jest/enzyme.

**Comment by kwelch** [comment]
I have a repo I built out for a local user group that have tests using jest/enzyme, it just lacks a component. It may be of help. 
https://github.com/NashReact/jest-exercises/tree/master/exercises/13%20-%20Component%20Testing

**Comment by mikedevita** [comment]
Thanks man right up my alley on what I needed!

**Comment by kwelch** [comment]
I will be pushing up the solution to a new branch later tonight. Good luck!

**Comment by danywheeler** [comment]
http://stackoverflow.com/questions/42499829/babel-plugin-order-when-merging-env-options-with-non-env-options
