### ISSUE TITLE
Put best practice in place to use "save exact" for npm packages

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#4]
@coryhouse, from what I know, it's recommended/best practice to use save-exact=true for npm packages.

* [Software Versions are Broken](https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783#.rwzkzabth)
* [Best Practices for Node.js Development](https://devcenter.heroku.com/articles/node-best-practices)

I've created pull request #3 for this.

**Comment by coryhouse** [comment]
Agreed. Thanks!
