### ISSUE TITLE
cannot resolve path (or pattern) './src/**/*.spec.js' #21

### ISSUE THREAD

**Issue by freeman29** [coryhouse/react-slingshot#40]
How can fix this? please help..

**Comment by coryhouse** [comment]
You just need to add at least one .spec file under /src. Alternatively, you can disable Mocha. This error occurs when Mocha can't find any tests.

Thus, I'm torn on whether to consider this a bug or a feature. :)

**Comment by freeman29** [comment]
Thanks Cory.. The slingshot is awesome. I will always use this on my projects instead of gulp.

**Comment by coryhouse** [comment]
I'd like to provide a friendly message when no tests are found, but I haven't found a way to suppress this message. Open to ideas.

**Comment by coryhouse** [comment]
I'm considering adding a check in the build that runs before Mocha. It would look for test files and if none exist, it would stop the build and message to the user to either:
a. Add at least one test
b. Disable running tests

This way, this error doesn't confuse others. Sound good?

**Comment by freeman29** [comment]
That would be great. are you using terminal commands on the checking or
webpack?

**Comment by nickytonline** [comment]
I created PR #86 to fix this. Feedback welcome.

**Comment by coryhouse** [comment]
Decided to leave this as is. See PR #86 for conversation on why. That said, thanks again to @nickytonline for continued support! :+1:

**Comment by nickytonline** [comment]
@freeman29, the PR #86 won't be merged, but the functionality you want is there, so feel free to grab it.

**Comment by freeman29** [comment]
I'll check it this weekend then I'll give my feedback. Thanks @nickytonline .
