### ISSUE TITLE
Revert back to pre HMR3?

### ISSUE THREAD

**Issue by oshalygin** [coryhouse/react-slingshot#404]
My mistake, looks like https://github.com/coryhouse/react-slingshot/pull/392 included a RHL 3.0 which isn't an actual deployed version.  Instead the latest is 3.0.0-beta6 as per the fix in https://github.com/coryhouse/react-slingshot/pull/401

Should we revert back to HMR 1 to make sure we're not using any beta packages?

Again sorry, I must've added it in package.json and ran yarn, assumed since there were no hiccups that it was okay.

@coryhouse

**Comment by nickytonline** [comment]
@oshalygin, not necessary to revert. See https://github.com/coryhouse/react-slingshot/pull/393#discussion_r109337607
