### ISSUE TITLE
Include Autoprefixer

### ISSUE THREAD

**Issue by darcnite3000** [coryhouse/react-slingshot#41]
I would like to know if we should include the setup needed to include autoprefixer into the webpack setup.

I found this a bit confusing to figure out how to implement into it given that autoprefixer recommends the use of postcss.

thus my loaders were

```
  if(env === productionEnvironment){
    loaders.push({
      test: /(\.css|\.scss)$/,
      include: path.join(__dirname, 'src'),
      loader: ExtractTextPlugin.extract("css?sourceMap!postcss!sass?sourceMap")
    });
  }else{
    loaders.push({
      test: /(\.css|\.scss)$/,
      include: path.join(__dirname, 'src'),
      loaders: ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap']
    });
  }
``` 

and i also had to add to my config export

```
postcss: ()=> [autoprefixer]
```

**Comment by coryhouse** [comment]
Great point. PostCSS and Autoprefixer have been on my radar. Would you be willing to submit a pull request?

**Comment by darcnite3000** [comment]
I shall see if i can figure out managing this

**Comment by darcnite3000** [comment]
Pull request added #45

**Comment by coryhouse** [comment]
@darcnite3000 Sorry for the slow response. Thanks for the PR! I'm still trying to decide if this warrants being included since I'm trying to keep things simple and lean.

**Comment by joernroeder** [comment]
1+ I would love to see autoprefixer included here as i have to a) add prefixes manually or b) use a sass library with "prefix-mixins" for this otherwise.

**Comment by giotramu** [comment]
Autoprefixer, PostCSS and SCSS Lint would be a great improvement. I use them a lot.

**Comment by kwelch** [comment]
Agreed on SCSS Lint (linting is always good). What are the advantages of PostCSS and/or autoprefixer?

**Comment by LFra** [comment]
I would love to have postcss support in this project! Also using them a ton.

**Comment by coryhouse** [comment]
Okay, enough people have asked, so I'm caving and adding it. :)

PostCSS is now part of the story. For now, only autoprefixer is included, but open to a PR that adds linting. 

Here's the commit: https://github.com/coryhouse/react-slingshot/commit/582f0111a8bee0751c6afbca26ac215367ee7cb8
