### ISSUE TITLE
Update the setup script

### ISSUE THREAD

**Issue by RoM4iK** [coryhouse/react-slingshot#417]
#### Expected behavior:
If user submits an empty string, or something else then "y/n", git should be removed. ( Can be changed to `y/N` )
#### Actual behavior: 
If user submits anything else than `y/yes` git isn't removed.

#### Expected behavior:
If user choose to not delete git, he still able to update `package.json` file
#### Actual behavior: 
If user chose to not delete git, setup script ends. 

#### Expected behavior:
After setup ends, setup files and script are deleted from project.
#### Current behavior:
Only setup files are deleted, `setup` script remains in `package.json`, but script are broken, because of missing files.

**Comment by nickytonline** [comment]
Thanks @RoM4iK. I'll take a peek at this tonight or tomorrow night unless @kwelch or @coryhouse get to it first.
