### ISSUE TITLE
Updating slingshot but having the project in a different git repo

### ISSUE THREAD

**Issue by pantchox** [coryhouse/react-slingshot#425]
Hello,
I want to keep update with the boilerplate changes/bugs by having the ability to do git pull.
but also i want to have the code i am working on on other repo such as bitbucket.
is it possible to update the boilerplate when needed but use git push/pull with my bitbucket or other repo?
i just don't know how to approach this way of thinking.

Thanks!

**Comment by coryhouse** [comment]
If you were using GItHub you could fork this and then pull changes over time. I'm not aware of an easy way to integrate with Bitbucket, but it may exist.

**Comment by kwelch** [comment]
We use BitBucket at your office, it is just a remote server at the end of the day. 

What you could do is clone slingshot and the remote from origin to slingshot (or something similar) this will allow for pulls in the future. 

Then you would setup your origin to point to your bitbucket repo. 

Then you commit and work as expected, when new changes come out in slingshot you would be able to pull (--rebase) from the slingshot remote which would accept in the changes and overlay all of your work on top of the latest slingshot version. 

I have not actually done this, but conceptually this should work.

**Comment by pantchox** [comment]
thanks guys! @kwelch i will try that

**Comment by mikedevita** [comment]
@kwelch's approach is what i typically do. pull down changes and fix any merge conflicts in my package.json, and webpack configs etc.

**Comment by nickytonline** [comment]
@pantchox, @kwelch's approach should work. If you need more info on rebasing or anything git related, check out the docs, https://git-scm.com/docs/git-rebase, but also if you want to become more familiar with git, you can see the commands in action visually at e.g. https://onlywei.github.io/explain-git-with-d3/#rebase

**Comment by nickytonline** [comment]
Closing as out of the scope of the project.
