### ISSUE TITLE
Not an issue but enhancement request.

### ISSUE THREAD

**Issue by vaishaliakhare** [coryhouse/react-slingshot#426]
I am trying to set up a project using react-slingshot but i need to use express for writing  server side / back end API's . 
Can some one guide me on how to use express with react-slingshot.

**Comment by kwelch** [comment]
React-Slingshot is already using express it just happens to be using wrappers over each side. 

The webpack-dev-server is a development wrapper(hot reloading) over the top of express. Same with browsersync. 

I have some details on #263 that shows my setup.

**Comment by iLeonelPerea** [comment]
@vaishaliakhare see my code. I implemented express for production using react-slingshot https://github.com/Tinker-Ware/eyes/blob/development/tools/distServer.js

**Comment by vaishaliakhare** [comment]
Thanks @iLeonelPerea  i was following the https://github.com/coryhouse/javascript-development-environment/blob/master/buildScripts/srcServer.js to implement similar approach. Please correct me here ... will I be missing any thing as I will not be using browserSync? or is there a way i can have plain express server with browser sync?

**Comment by kwelch** [comment]
BrowserSync is only valid to be used within development. This is just a nice to have.

**Comment by iLeonelPerea** [comment]
@vaishaliakhare browsersync is for use in development. and for production you need to use something more robust.. 

@kwelch @coryhouse is ok if I do a pull request adding express for production? like i use in my implementation.

**Comment by vaishaliakhare** [comment]
Thanks every one for helping me here & replying promptly.
i mades changes to srcServer.js  as below.
https://github.com/coryhouse/react-slingshot/issues/353.
 import historyApiFallback from 'connect-history-api-fallback';

import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';
import {chalkSuccess} from './chalkConfig';
import config from '../webpack.config.dev';
import express from 'express';
import http from 'http';

const bundler = webpack(config);
const app = express();
const server = http.createServer(app);
console.log(chalkSuccess('Starting Express server...'));

app.use(express.static('src/*.html'));
app.use(historyApiFallback());
app.use(webpackHotMiddleware(bundler));
app.use(webpackDevMiddleware(bundler, {
  // Dev middleware can't access config, so we provide publicPath
  publicPath: config.output.publicPath,

  // These settings suppress noisy webpack output so only errors are
displayed to the console.
  noInfo: false,
  quiet: false,
  stats: {
    assets: false,
    colors: true,
    version: false,
    hash: false,
    timings: false,
    chunks: false,
    chunkModules: false
  },

  // for other settings see
  // http://webpack.github.io/docs/webpack-dev-middleware.html
}));
app.use('/v1', require('../server/routes'));
server.listen(3000);
console.log(chalkSuccess('Express server is listening on port: ' +
server.address().port));

then i created server/routes directories under that created index.js with
below code

var express = require('express');
var router = express.Router();

router.get('/ingHome', function(req, res) {
  res.send('Welcome to React SlingShot.');
});

module.exports = router;

then in the browser if i try to access http://localhost:3000/v1/ingHome
 then i am getting 404 page not found.
I have attached screen shot as well. Please let me know if i am missing
anything.
It is critical for  my app to have node service in the same  code base.

**Comment by kwelch** [comment]
Looks like you a spinning up both a server and an app and I don't see the two linked. You should not need the server you should be able to end the file with 

```js
app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
```

**Comment by kwelch** [comment]
@iLeonelPerea I am open to the idea but since we have been using the distServer as is for quite some time I don't see a need for making a move away from it.

**Comment by coryhouse** [comment]
I'm unclear what problem this issue is trying to solve. That said, in order to clearly convey the change being proposed, please submit a PR.

**Comment by vaishaliakhare** [comment]
I just need an example where i can write serve side API end point using  express router along with webpack dev server. @kwelch thanks for catching it, i removed the server code you mentioned and replaced with app.listen .... still had no luck getting  it working.  I will try using proxy-middleware.

**Comment by nickytonline** [comment]
@vaishaliakhare, I would recommend checking the Express documentation. You can also look at projects like sails.js or StrongLoop's Loopback that generate REST apis.

**Comment by nickytonline** [comment]
Closing as this is out of the scope of react-slingshot project.

**Comment by iLeonelPerea** [comment]
@coryhouse 

Ready the [PR](https://github.com/coryhouse/react-slingshot/pull/428)
