### ISSUE TITLE
NPM Inject-Loader

### ISSUE THREAD

**Issue by sgriffin916** [coryhouse/react-slingshot#429]
Have you ever used inject-loader (https://www.npmjs.com/package/inject-loader) in your slingshot?  We are able to get the examples to work on inject-loaders page but running the same commands and code in Slingshot generates errors. I have asked for suggestions from the inject-loader project but the only feedback I have heard so far is that it may have something to do with webpack.  Thanks for any thoughts.

Node version: v7.7.4
npm version: v4.1.2
Operating system: Windows 10 Pro

Command line used: npm install --save-dev inject-loader

Steps to reproduce:

Within a spec.js file - 
Error #1 - 
const EnsureLoggedInInjector = require("inject-loader!EnsureLoggedIn"); // error returns cannot found module

Error #2 - 
const EnsureLoggedInInjector = require("inject-loader!./../../src/containers/EnsureLoggedIn"); // this finds the module
let EnsureLoggedIn = EnsureLoggedInInjector({
            "react-router": {
                browserHistory: {
                    replace: browserStub
                }
            }
        }).EnsureLoggedIn;  // but this generates an error that EnsureLoggedInInjector is not a function

**Comment by nickytonline** [comment]
@sgriffin916 I'm assuming you're using this to mock something in a unit test? Do you have a repository with react-slingshot and inject-loader on GitHub that we can look at? Also, react-slingshot uses jest now. Have you looked at the jest docs for mocking?

**Comment by sgriffin916** [comment]
I ended up getting it to work using sinon.stub().  Thanks for getting back with me.

**Comment by nickytonline** [comment]
Np and glad you're all good to go.
