### ISSUE TITLE
Add a contributing.md to the project

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#430]
We've provided a template for opening issues, but sometimes people ignore it. This is one reason I would suggest having a contributing.md for our guidelines.

We're not the only project having this issue, https://twitter.com/DavidDarnes/status/863729976465661952 .

@kwelch, @coryhouse let me know what else you would like to see if anything in the contributing.md.

**Comment by coryhouse** [comment]
My first take: https://github.com/coryhouse/react-slingshot/pull/431
