### ISSUE TITLE
errno 137

### ISSUE THREAD

**Issue by Boggimedes** [coryhouse/react-slingshot#434]
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the react-slingshot@7.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2017-05-18T15_36_42_476Z-debug.log

Node version: v7.10.0

npm version: v4.6.1

Operating system: Ubuntu

Command line used: npm run setup

Logfile:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@4.6.1
3 info using node@v7.10.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-slingshot@7.0.0~presetup: react-slingshot@7.0.0
6 silly lifecycle react-slingshot@7.0.0~presetup: no script for presetup, continuing
7 info lifecycle react-slingshot@7.0.0~setup: react-slingshot@7.0.0
8 verbose lifecycle react-slingshot@7.0.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle react-slingshot@7.0.0~setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/react.gmapp/react-slingshot/node_modules/.bin:/usr/local/sbi$
10 verbose lifecycle react-slingshot@7.0.0~setup: CWD: /home/ubuntu/react.gmapp/react-slingshot
11 silly lifecycle react-slingshot@7.0.0~setup: Args: [ '-c',
11 silly lifecycle   'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js' ]
12 silly lifecycle react-slingshot@7.0.0~setup: Returned: code: 137  signal: null
13 info lifecycle react-slingshot@7.0.0~setup: Failed to exec setup script
14 verbose stack Error: react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-slingshot@7.0.0
16 verbose cwd /home/ubuntu/react.gmapp/react-slingshot
17 verbose Linux 3.13.0-74-generic
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
19 verbose node v7.10.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 137
23 error react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
23 error Exit status 137
24 error Failed at the react-slingshot@7.0.0 setup script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 137, true ]

**Comment by coryhouse** [comment]
Suggest trying Node 6. Suspect it'll run fine.

**Comment by Boggimedes** [comment]
Installed node 6.10.3 still errored out


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'setup' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-slingshot@7.0.0~presetup: react-slingshot@7.0.0
6 silly lifecycle react-slingshot@7.0.0~presetup: no script for presetup, continuing
7 info lifecycle react-slingshot@7.0.0~setup: react-slingshot@7.0.0
8 verbose lifecycle react-slingshot@7.0.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle react-slingshot@7.0.0~setup: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/react.gmapp/react-slingshot/node_modules/.bin:/usr/local/sbi$
10 verbose lifecycle react-slingshot@7.0.0~setup: CWD: /home/ubuntu/react.gmapp/react-slingshot
11 silly lifecycle react-slingshot@7.0.0~setup: Args: [ '-c',
11 silly lifecycle   'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js' ]
12 silly lifecycle react-slingshot@7.0.0~setup: Returned: code: 137  signal: null
13 info lifecycle react-slingshot@7.0.0~setup: Failed to exec setup script
14 verbose stack Error: react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-slingshot@7.0.0
16 verbose cwd /home/ubuntu/react.gmapp/react-slingshot
17 error Linux 3.13.0-74-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "setup"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
22 error Exit status 137
23 error Failed at the react-slingshot@7.0.0 setup script 'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-slingshot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-slingshot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-slingshot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Boggimedes** [comment]
Anything else I can try?

**Comment by nickytonline** [comment]
@Boggmedes, I see you have "Exit status 137" being thrown by npm. From what I found on Google this typically means you're running out of memory.

* https://github.com/driftyco/ionic-app-scripts/issues/231#issuecomment-255792824
* https://github.com/npm/npm/issues/4008#issuecomment-188495114

Can you check your memory usage on your Ubuntu installation?

**Comment by Boggimedes** [comment]
624MB free.  Seems like that should be plenty for an installation

**Comment by Boggimedes** [comment]
Nevermind.  I was looking at the wrong system.  It was more like 200MB.  I
upgraded the RAM and we are good.

**Comment by kwelch** [comment]
Great, is this good to close then?

**Comment by nickytonline** [comment]
Cool @Boggimedes. Glad you're all sorted out now. I think we're good to close this.

**Comment by Boggimedes** [comment]
We are.  thanks again!

**Comment by coryhouse** [comment]
Great catch @nickytonline ! I was stumped on this.
