### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#44]
@coryhouse, this isn't an issue to add TypeScript support as your boilerplate is Babel, but it's just to mention that I have a fork with TypeScript support if that floats people's boats. You can check it out here, https://github.com/typescriptcrew/ts-react-slingshot . I still have some tweaking to do with the typings for stateless components, but aside from that it's all running.

**Comment by coryhouse** [comment]
Cool, thanks for sharing!
