### ISSUE TITLE
NPM script to generate new components

### ISSUE THREAD

**Issue by diegohaz** [coryhouse/react-slingshot#440]
Hi, guys.

I'm working on a project that helps people to generate new components on their projects following their conventions no matter how they structure the project.

I'm trying to apply it on some boilerplates so I can be sure that it works on most structures.

I just want to know if it's desirable to have a `yarn component` script (or something like that) to handle that. I can submit a small PR. :)

**Comment by mikedevita** [comment]
something like this existed once, I can't recall if it was on davezuko's kit or here... but 

[SpencerCDixon/redux-cli](https://github.com/SpencerCDixon/redux-cli)

**Comment by coryhouse** [comment]
Interesting idea, but I think it falls outside of the scope for this in my eyes - Open to other input though.

**Comment by diegohaz** [comment]
After some work I managed to get it working with `react-slingshot` structure (as well as other boilerplates). Here's the repo: https://github.com/diegohaz/generact

![image](https://cloud.githubusercontent.com/assets/3068563/26794686/160a1ce2-49f9-11e7-8f5e-525e68383a97.png)
![image](https://cloud.githubusercontent.com/assets/3068563/26794709/2b3d3cf2-49f9-11e7-8627-92653c9378ba.png)
![image](https://cloud.githubusercontent.com/assets/3068563/26794720/3efa663e-49f9-11e7-95b1-12e3d2341972.png)

**Comment by nickytonline** [comment]
@diegohaz, cool idea, but I agree with @coryhouse on this one. It's out of the scope for this project.
