### ISSUE TITLE
RangeError when reducer returns React element

### ISSUE THREAD

**Issue by QuantumHive** [coryhouse/react-slingshot#441]
Node version: **6.10.3**
npm version: **3.10.10**
Operating system: **Windows 10 version 1703**
Command line used: **N/A**
# Steps to reproduce:

If a reducer (any reducer) returns a state with a React element in it e.g.

```
return {
  myState: <div>Hello World</div>
}
```

Then the following error is produced:

```
RangeError: Maximum call stack size exceeded

trackProperties
trackProperties
trackProperties
trackProperties
trackProperties
...
```
![capture](https://user-images.githubusercontent.com/2554952/27254821-f669b716-5390-11e7-97cf-c38f8b88d38d.PNG)

This only happens when an HTTP request is made to some `Route` which would end up dispatching to such reducer.
When navigating from a route that doesn't have a reducer returning an React element inside the state, then the error is not produced and all seems to work fine.

## Example:

- An HTTP request to route `/` is made.
- User navigate from `/` to `/reducer`
- `/reducer` dispatches an action
- Some reducer returns a React element in the state e.g. `<div>Hello World</div>`
- No error shows up
- User refreshes the `/reducer` page to force an HTTP request
- The error shows up
- Change the reducer so that it does not return a React element.
- Refresh the page and the error is gone (this proves that the React element causes the error).

**Comment by coryhouse** [comment]
The Redux store is for storing plain data, not React elements. I've never seen anyone store a React element in the store, nor have I tried. That said, this isn't a Slingshot bug. I'd suggest posting on the Redux repo for guidance on whether the Redux store supports this use case.
