### ISSUE TITLE
webpack Hot Middleware updates across all tabs instances when using multiple tabs / browsers

### ISSUE THREAD

**Issue by sag1v** [coryhouse/react-slingshot#445]
I've actually posted an [issue ](https://github.com/glenjamin/webpack-hot-middleware/issues/223) about this in the webpack-hot-middleware repo, i thought i might get help here as well as i can confirm this behavior exists with the default settings of `react-slingshot`.

I've bumped into an issue with webpack-hot-middleware, when i open multiple instances of browsers or tabs (chrome IE and FF) i get refreshes or updates on all of them on each visual action being triggered.
For example, scrolling on 1 tab triggers a scroll on another tab.
Anyone came across this behavior?

windows 8.1
chrome - Version 59.0.3071.115 (Official Build) (64-bit)
firefox - 54.0.1 (32-bit)
IE 11

**Comment by sag1v** [comment]
OK, I found the reason for this behavior and its not related to `webpack-hot-middleware` at all.
Actually what cause this is the `browserSync` plugin.
By default it has a [ghostMode](https://browsersync.io/docs/options#option-ghostMode) option set to true. 

> Clicks, Scrolls & Form inputs on any device will be mirrored to all others.

You can disable it by setting it to false.
`ghostMode: false`

**Comment by coryhouse** [comment]
Bingo. I consider that behavior a very handy feature. :)

**Comment by sag1v** [comment]
> Bingo. I consider that behavior a very handy feature. :)

Not when you're trying to implement websockets 😀
