### ISSUE TITLE
analyze-bundle not reporting production stats

### ISSUE THREAD

**Issue by atamaku1** [coryhouse/react-slingshot#446]
Just noticed that analyzeBundle.js is not setting production environment before calling webpack. This is causing the stats to report development dependencies in the bundle statistics.

This needs to be defined before calling webpack in analyzeBundle.js
```
process.env.NODE_ENV = 'production';
```

**Comment by coryhouse** [comment]
Ah, good catch. Just fixed in bd13289c96e95952696b392ff232c5e27333750c

Thanks! 👍
