### ISSUE TITLE
Windows Does allow to provide input or proceed further

### ISSUE THREAD

**Issue by zeegeek** [coryhouse/react-slingshot#447]
Node version: v8.1.0

npm version: 5.0.3

Operating system: Windows 7

Command line used: windows command prompt

Steps to reproduce: 
open cmd prompt then run ntl 
after that i have selected setup
it will install all dependencies
then it will ask for delete local repo works well here, 
then after that it will ask for project name .
Here at this point of time i cannot enter anything ( Keyboards keys doesnt respond )

**Comment by kemotoe** [comment]
@zeegeek This is a known issue with node v8.1x. See here https://github.com/nodejs/node/issues/13557 . The general consensus was to update node to the latest version or use nvm to revert to a pre 8.1.x version of node

**Comment by coryhouse** [comment]
Thanks for the reply @kemotoe! Closing since this isn't a Slingshot-specific issue.
