### ISSUE TITLE
Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

### ISSUE THREAD

**Issue by DavidShusterman** [coryhouse/react-slingshot#454]
Hey,
After installing the slingshot, I have added material-ui@0.18.7 to the application
and when running the most basic application, and using a component from material-ui
I get this error :

```
Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded 
```

Node version:
7.9.0
npm version:
5.3.0
Operating system:
Windows 10

Can somone help please? 
Thanks!

**Comment by kwelch** [comment]
This sounds like it is something within Material-UI and how they control the components. 

Have you added any refs?

Is your react version within their peer dependency range? I have only seen the multiple reacts loaded in a few scenarios, you setup does not sound to be near the once I have encountered.

**Comment by nickytonline** [comment]
@DavidShusterman, this does sound like a peer dependencies issue, https://stackoverflow.com/questions/28519287/what-does-only-a-reactowner-can-have-refs-mean.

Can you remove react from `dependencies` and add it to `peerDepencies` in the package.json? e.g. https://github.com/AdaptiveConsulting/react-flex-layout/pull/17/files. Let me know if that fixes the issue.

**Comment by nickytonline** [comment]
@DavidShusterman, just wondering if you had a chance to try what I suggested.

**Comment by DavidShusterman** [comment]
Hey nick, thanks for the help. but it seems like your solution hasn't help me.
I have checked to see if I got multiple react instances loaded by running ``` npm list react ```
and I have only 1 copy installed..
so I think the problem is related to the "You might be adding a ref to a component that was not created inside a component's `render` method"

**Comment by nickytonline** [comment]
@DavidShusterman, do you have a repo where I can look at this issue?

**Comment by DavidShusterman** [comment]
@nickytonline
I'm sorry but its a private repo...
But you can simply install the slingshot, and then install material-ui, and apply a component of material-ui and ull recreate the problem..

**Comment by raythree** [comment]
I've not tried with those versions, but I have a couple of slingshot starter apps that remove the demo and put in one sample component. I have one for bootstrap and one for material-ui which worked fine:

**Comment by nickytonline** [comment]
@DavidShusterman, did you ever get this resolved or is this still an issue for you?

**Comment by coryhouse** [comment]
Closing - Please provide simple reproducible example if issue persists.
