### ISSUE TITLE
getting jest to transpile outside of src directory

### ISSUE THREAD

**Issue by raythree** [coryhouse/react-slingshot#455]
We've got several apps based on slingshot and we're trying to share some common code (for example, mui-themes) in a directory at the top level where all the apps reside.

Everything is being transpiled just fine when running ```npm start -s``` but when running ```npm run test``` jest is throwing a syntax error.  You can reproduce with any slingshot app by creating:
```
react-slingshot/
  src/...

common/
  theme.js
```
In ```common/theme.js```:
```
export default {
  color: 'red'
}
```
Then inside the ```FuelSavingsForm```:

```
import theme from '../../../common/theme';
...
        <h2 style={{color: theme.color}}>Fuel Savings Analysis</h2>

```
Running ```npm start -s``` will display the red heading, but ```npm run test``` which will produce:
```
src/components/FuelSavingsForm.spec.js
  Test suite failed to run

    /Users/bill/projects/common/theme.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default {
                                                                                             ^^^^^^
    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/components/FuelSavingsForm.js:6:14)
      at Object.<anonymous> (src/components/FuelSavingsForm.spec.js:3:24)Test Suites: 2 failed, 10 passed, 12 total
```
Any suggestions appreciated.

Thanks!

**Comment by coryhouse** [comment]
Root dir may help: https://facebook.github.io/jest/docs/en/configuration.html#rootdir-string

That said, I recommend placing shared code in an npm package instead, so it can be separately versioned and deployed.

**Comment by raythree** [comment]
Thanks. The common areas deliberately have their own packge.json that modules below it inherit, because we want all the apps to be using exactly the same versions of third party packages, and don't want to manage it separately in each app. And these are private, so we can't publish them without running a private npm repository. This structure is i little non-standard, but works well for our situation.

**Comment by coryhouse** [comment]
Ah, we had the same desire. We encapsulate 75+ npm packages in a single npm package that we control. This package contains our build scripts, webpack config, ESLint config, test config, common utils, and more. It's basically a custom fork of Slingshot with a lot of extra opinions built in. This means we have an easy way forward for updating apps over time, and no one else feels the pain of package churn. One team manages this single npm package and decides when to upgrade the company.

**Comment by raythree** [comment]
Yeah, the structure I described is exactly what we want, because it allows code sharing at all levels, yet having the third party package management in one place, without redundant NPM installs. We even have server and UI apps that share code--for example, Mongoose schemas are used not only on the backend, but also for validation in UI apps. We deliberately placed the schemans there so they could be imported by both client and server.

Any code that is common is left out of the app's package.json, and inherited from one level up. This is exactly how node resolve was designed to work:
```
js/
  common/
    package.json (common dependencies)

  servers/
    common/
      package.json (common for servers)    
    app1/
      ... total.js server
     
  ui/
    common/
      package.json (common for all UI apps)
    
    app1/
      ... slingshot app  
```
The problem is that it can cause problems with build tools that don't expect this. I tried setting rootDir for jest as you suggested, but it got worse because it started scanning other subdirs for test, etc. I wanted to tell it where to "resolve only", not where to test.

**Comment by coryhouse** [comment]
So when someone joins your team, to get a given app to run, they need to cd into multiple directories and run `npm install` in each, correct? And if any of those levels above change, you need to run `npm install` in that dir again. 

This is novel, but strikes me as unnecessary friction. 

With traditional npm packages for reusable code, your team could run `npm install` in the root directory and be rolling. And you wouldn't have to do any tricky config work related to your bespoke approach.

What benefit do you get with your current approach over using npm packages?

**Comment by raythree** [comment]
No, when you checkout a repo you run ```npm run setup``` at the root. Likewise for any changes. It runs ```npm install``` in parallel on all the common packages. It didn't strike me as novel, because that's exactly the way npm resolution works (by design), moving up the parent tree. The benefits are that top level builds (that run docker and package everything) are fast, and third party version management is done in exactly one place. 

I'm open to any approach that works, and would like to understand what you are suggesting. 
Taking two examples:

1. UI themes, imported by all UI apps.
2. Mongoose schemas, imported by all servers and ui apps. 

Currently we have:
```
project/

  common/
    package.json
    schemas/
      ... schemas depending on mongoose version 4.x.y in package.json

  servers/
    ...

  ui/
    common/
      package.json
      style/
        ... themes based on material-ui version 4.11.6
```
Are you suggesting that we create (and publish to a private npm repo) 2 packages:

project-schemas-1.0.0
project-themes-1.0.2

And then add:

project-schemas-1.0.0 --> add to all UI and server package.json 
project-themes-1.0.0 --> into all UI app package.json

Then, for a schema change we need to change all server AND UI apps to use project-schemas-1.0.1. And for any theme change we change all UI apps to use project-schemas-1.0.1?

**Comment by raythree** [comment]
OK, I found a solution. In order to get it to work, all that is needed is a .babelrc file in the "common" folder. However, in dev mode, this means that all the dev-dependencies must be resolved, like babel presets. But, we never want "dev-dependencies" installed in any common packages, only production "dependencies". The reason for this is when deploying final packages for production, the bundler needs to copy not just the app/node_modules, but also any common parent node_modules directories. It would be a mess if all dev dependencies got included.

The solution to this was to install all "dev-dependencies" one level up. These never get packaged in production, but are resolved by all apps when running in test and dev mode. Now everything works as desired for production and test, using standard node/npm resolution. 

I would still like your opinion on alternate approaches, and if you meant creating packages for 'project-schemas', for example, that get put into every app's package.json. The issue I see with this is that if we change mongoose versions for the top level scheme package, we now need to recreate the project-schema package and update say 20 server and ui application package.json files to use the new version. With the layout we are using now, we simply make the change at the top level in project/schemas/package.json and all server and ui apps using the schemas immediately inherit the change. This never prevents us from having an individual app use it's own schema and mongoose version in it's package.json, if needed. However the goal is actually to avoid this, and by default enforce a single base version across all apps.

**Comment by coryhouse** [comment]
Correct, that's what I was suggesting. Obviously, there are merits to each approach, I've just not seen your approach before so I was curious.

**Comment by raythree** [comment]
OK, thanks, got it. First, I've solved this specific open issue. It is resolved by adding a '.babelrc' to each of the common parent directories. This takes care of any jest/babel issues. I'll further elaborate on our configuration compared to what you suggest.

I'll note that each common parent directory with a package.json only contains "dependencies", not "dev-dependencies". The reason is that the top-level deployment scripts include all node_modules from the root to the individual apps. This is mainly for 'server' apps, because 'ui' apps work fine with webpack, BUT this also requires that the very top level (above the 'js' folder) has all the 'dev-dependencies' (taken directly from dev-dependencies in slingshot's package.json)--these are never deployed, only in place so that all the ui 'npm start -s' and 'npm run test' scripts work.  

Comparing the approaches, let's say we have 20 server and UI packages using the schemas, and let's say we change either an individual common schema, or change the mongoose version. With our approach, we simply change the top level common folder and everything is immediately inherited by all server and ui apps. With the approach you suggest, we'd need to deploy a new 'project-schema-version', then update all 20 app package.json files with the new version. Ugh.

Also using our approach, any individual app can have a custom schema or use a specific mongo version by simply declaring it, and it all works using node/npm resolution. But this is discouraged. We want the default to be that all apps use the same schemas and mongo version, so this is the default.

**Comment by coryhouse** [comment]
Gotcha. Thanks for clarifying. I can certainly appreciate the merits of your approach given that context. 

We have apps running with different versions of our npm packages and are okay with that. We figure, ain't broke, don't fix it. But your approach helps assure everyone is running the latest bits. That does mean more regression testing on every code change since a single code change may immediately break over a dozen apps. There's no easy way to publish an update to the "core" without impacting many downstream apps immediately. But I can certainly see the merits as well. As in all things software, tradeoffs! :) Thanks for clarifying!

And I assume this issue can be closed?

**Comment by raythree** [comment]
Our goal across the suite of apps is to have common code in one place. When we upgrade mongoose or change a schema, we want dozens of apps to break, because any introduced issue caused by it should be immediately obvious and fail in multiple apps for the same reason. 

In any case, yes you can close it. Thanks.
