### ISSUE TITLE
Upgrade to React Router 4

### ISSUE THREAD

**Issue by MichaelLSmith** [coryhouse/react-slingshot#459]
Before logging an issue:

* Ensure you have followed instructions in the [README](https://github.com/coryhouse/react-slingshot/blob/master/README.md)
* Read the [FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md)
* Look through existing [open](https://github.com/coryhouse/react-slingshot/issues) and [closed](https://github.com/coryhouse/react-slingshot/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone has reported the issue before
* Still stuck? Report a new issue

Node version: 6.11.2

npm version: 3.10.10 (actually using yarn)

Operating system: Linux Mint

Command line used: run start

Steps to reproduce: 

I'm just wondering if you're thinking of upgrading the project to use react router 4.

**Comment by kwelch** [comment]
Yes, there is a PR open #393, but it is slightly behind. We are absolutely open to a PR that adds RRv4.

**Comment by nickytonline** [comment]
@TobiahRex, any chance you can rebase and get #393 up to snuff?

**Comment by TobiahRex** [comment]
@kwelch & @nickytonline You'll have within 72 hrs. In the middle of an app launch today.

**Comment by nickytonline** [comment]
No rush @TobiahRex. Whenever you have time :)

**Comment by kwelch** [comment]
Congrats on the launch 🎉

**Comment by TobiahRex** [comment]
@kwelch & @nickytonline Rebase complete. Couple notes...
1) Coverage percentage dropped a tad (.7%).  I looked at the report and it doesn't appear to be coming from any files I personally changed.  I could be wrong, but it looks like it's coming from the package dependencies version upgrades.  Would need another to confirm.

2) I believe `react-router-redux` hasn't upgraded their Prop Validation library to `prop-types` post `react v15` hence this error ... ![PropType validation error from npm Package](https://user-images.githubusercontent.com/16377119/29909023-0a6df3c2-8e5f-11e7-841c-14462d58a5c5.png)
