### ISSUE TITLE
How to enable pushState support?

### ISSUE THREAD

**Issue by vasyabigi** [coryhouse/react-slingshot#46]
After refreshing page on any url except home I'm getting 404. How can I serve `index.html` by default?

**Comment by dotnetnorm** [comment]
I got this working by using connect-history-api-fallback.

I modified the srcServer.js file:  

Added: var historyApiFallback = require('connect-history-api-fallback');

then below:  webpackHotMiddleware(bundler),
add:       historyApiFallback()

I also had to modify: 
 <script src="bundle.js"></script> to 
 <script src="/bundle.js"></script>

in the index.html file.

This is working for me.

**Comment by coryhouse** [comment]
@dotnetnorm Nice find! First I've seen of that package. Now I just need to decide if this is worth including in the starter kit. Would you be willing to submit a pull request so I can see exactly how you wired this up?

**Comment by dotnetnorm** [comment]
Will do.

**Comment by vasyabigi** [comment]
#47

**Comment by coryhouse** [comment]
@dotnetnorm Thanks for the PR. I'm leaning toward keeping this out of the kit since it's only useful for those doing client-side routing, which I already chose to exclude from the kit. I'm open to being swayed if I'm missing something though... :)

**Comment by coryhouse** [comment]
I've decided to exclude this since it's only useful for some people, but thanks for the PR to help clarify!
