### ISSUE TITLE
minor build script adjustments?

### ISSUE THREAD

**Issue by raythree** [coryhouse/react-slingshot#461]
We use slingshot for all our apps and try to use it with minimum modifications (after doing a remove-app, and re-populating our app) so that we always get the latest enhancments with minimum tweaking of the configuration. There are two specific things we always change for right from the start, and it seems to us like they would be the most common use-case, so we want to understand the reasoning, and if you'd be open to a PR for these minor adjustments.

It really comes down to the usage of ```npm run build``` and ```npm run clean-dist``` or ```npm run remove-dist``` (we don't see the need to distinguist, since webpack creates it anyway?). For the production build, the first thing we change is the ```output.path``` in ```webpack.config.prod.js``` (the dev config isn't used). We point this to where we want it to go for our production release. This could be a static nginx public directory, or a static folder for any other server that may be serving static apps/resources.  This will almost always be app-specific.

Ideally, we'd like to just change the output.path in webpack.config.prod.js and then execute:

```npm run build``` 

To populate whatever path was specified in the webpack config, and then

```npm run clean```

to remove it. Also, we almost always execute this from inside a global top-level build/docker script, so we just want the ```build``` script to generate the bundle, and not also serve it up with ```npm run open:dist```.

The adjustments to the current scripts seem minimal. These would be:

1. Remove the ```&& npm run open:dist``` from ```scripts.build```. Is this a typical use case anyway?
2. Adjust the ```remove-dist``` script such that instead of doing a ```rimraf ./dist``` executed a new script in tools that did a  rimraf of whatever was specified in the webpack output.path, rather than hard-coding ```dist```.
3. Maybe add a ```clean``` script that simply did the above, rather than distingusing between removing the dist folder and then re-creating it (what is the use-case since it get recreated by webpack anyway?).

Thanks!

**Comment by kwelch** [comment]
Just a few notes:

1. I am in favor of this since `build` is typically ran on CI. I also remove this immediately, but understand that it was added to validate the build

2. I am always a fan of minimal changes so reading the output from a configuration, is another valid change in my book. 

3. This I believe is done as a delete and create for permissioning purposes. Not certain. 

I am in favor of the changes, but would recommend good docs around where to change these values. Also, validation on the third point that it will not cause issues (I believe it was windows related)

I am only one voice, so I encourage others to chime in.

**Comment by coryhouse** [comment]
Thanks for the thoughtful suggestions. I'm open to these changes as well. 

1. Cool. I see your point.
2. Rather than declaring the path in webpack.config, how about package.json? More accessible and likely to churn over time (in case webpack's config format shifts down the road).
3. I agree, makes sense. Point is, when you do a prod build, it's key to delete the relevant files first.

I would welcome a PR on this. :)

**Comment by raythree** [comment]
OK great, will take care of a PR. @coryhouse what do you suggest regarding the output path in package.json?

Thanks.

**Comment by coryhouse** [comment]
Good question. Help me understand: What's wrong with always writing to /dist? To me, it's a separate decision where to move the built application to. Other boilerplates like create-react-app always write to the same folder, and expect the user to write the necessary automation for moving the final build to the point desired...

**Comment by kwelch** [comment]
I don't think we should move away from `dist/`. I am fine with having a single point of truth for what directory that is.

**Comment by raythree** [comment]
There's nothing wrong with it, as a default, but it would be nice to be able to point it at the actual target where you are assembling the build. It just avoids an extra unnecessary copy elsewhere in the  assembly script. It could be added as an option to package.json (config: {target: path}}, and then inside the webpack config the output path could be specified like ```$npm_config_target || path.resolve(_dirname, 'dist')```. That would leave current usage unchanged. The key is just having the rimraf use whatever webpack.output resolves to.

**Comment by raythree** [comment]
@coryhouse  create-react-app is a quick way to get an app running, but as soon as you need customization, you "eject" it, and take control of the configuration. Or, just start out with Slingshot, which is my recommendation :-)

Let me illustrate the use-case of controlling the target per each UI app. Your application suite has 5 node servers, 20 React UI apps, and it's all behind an nginx configuration. The top level build/assembly script already needs to know how to package all the servers/routes behind nginx, and where to place all the static assets to be served by nginx. But let's say that 15 of the UI apps are "public" and you want them to be served by nginx directly, and 5 are "private", meaning you only want them served if you've already authenticated/authorized, so they need to go behind one of the server apps. You know which UI needs to go where, so you configure their targets and everything will work. If all the UI builds go to <ui_path>/dist, then you need to manually insert the copy instructions for 5 of them into server packages, and the other 15 into the thing that assembles the nginx configuration. There is definitely a valid use-case for configuring the UI target paths.

**Comment by raythree** [comment]
@kwelch I agree about a single point of truth. In this case I think the answer is where does this app need to go, and that may be different for each app.

**Comment by kwelch** [comment]
The output path of artifacts has never been a big deal for me. Typically we store them in the output folder and then grab that is CI as an artifact and deploy as an artifact.

**Comment by raythree** [comment]
OK, so I tried the following. Added to package.json:
```
  "config": {
    "targetPath": "./dist",
    "publicPath": "/",
    "publicPathDev": ""
  }
```
And then in webpack.config:
```
const configuredTarget = process.env.npm_package_config_targetPath ? 
                         path.resolve(process.env.npm_package_config_targetPath) :
                         path.resolve(__dirname, 'dist');
```
Works exactly as I wanted,  BUT, I'm backing off the suggestion to add it because of my concern about the ```clean``` part. It would be too easy to insert a path that resolved to a directory above where you intended! 

I may just configure our scripts this way, with a safeguard in ```tools/clean.js``` to make sure it resolves N levels below root (we know what that always is)... but probably not a good idea for general use.

Thanks!

**Comment by raythree** [comment]
OK, so I've been using this for over a week, and really like doing:

npm run build 
npm run clean

To produce (or clean) the production bundle, with the destination and public path both specified in the config section of package.json as @coryhouse suggested.  These need to be adjusted for most projects, and its better to be configured via package.json rather than the webpack config.

My only reason for backing off was a concern that too many '../../' in the target path would clean an unintended directory. But it's definitely easy to make sure the path is not too shallow before doing the rimraf, as a precaution (for example most builds will be at or below 3 levels /users/home/user/project)... 

I definitely like this configuration and will continue to use it. Would you still be open to reviewing a PR?

**Comment by kwelch** [comment]
I think a PR would be great. It would also ensure we are on the same page as we discuss this type of change. 👍

**Comment by nickytonline** [comment]
:thumbsup:

**Comment by raythree** [comment]
OK this is done.

https://github.com/coryhouse/react-slingshot/pull/466#issuecomment-326804937

The default target path for ```npm run build``` is exactly the same, ./dist. It does not run open:dist to allow for its use in automated builds. I added documentation to the readme for configuring this, along with the warning about clean not removing paths too close to root, and how to override it.

**Comment by nickytonline** [comment]
Sorry for not following up sooner @raythree. Just following up on this issue. @kwelch, @coryhouse are we still going ahead with this?

**Comment by kwelch** [comment]
Going through the PR again, I am not sure the value add this gives. I am not against working it in, but I don't see a need.

**Comment by coryhouse** [comment]
I'm sorry this set for so long. After thinking about this, I'd vote to close to avoid creating confusion for others. Of course, anyone using this is free to alter as they see fit, but I'm not sold the confusion risk is worth the benefit on this. And changing the output directory manually is simple.

So I'd vote to close.
