### ISSUE TITLE
Where does Internationalisation go?

### ISSUE THREAD

**Issue by jamesladd** [coryhouse/react-slingshot#462]
Hey React-slingshot,

I'm getting a lot of use out of this Slingshot. Thank you for the efforts.
I'm trying to add internationalisation and I think I have it in the right spot (as it is working).
However, I wanted to check.

In components/root.js I have added.

export default class Root extends Component {
  render() {
    const { store, history } = this.props;
    return (
      <IntlProvider locale="en">
        <Provider store={store}>
          <Router history={history} routes={routes} />
        </Provider>
      </IntlProvider>
    );
  }
}

Is this the right place or should it be moved elsewhere?

- James.

**Comment by coryhouse** [comment]
Hi James - The root makes sense to me, but I'd defer to the docs for the lib you've chosen.

**Comment by jamesladd** [comment]
Thank you for the quick response

**Comment by nickytonline** [comment]
@jamesladd, on projects I've worked on, the server-side handles translations and on the front-end, formatting of e.g. currency.

**Comment by nickytonline** [comment]
Closing as this is out of the scope of the project.
