### ISSUE TITLE
Getting an error while starting the server in dev mode

### ISSUE THREAD

**Issue by kallada1978** [coryhouse/react-slingshot#464]
start the server in dev mode : npm start, 
we will see the following error in console 

> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm run test -- --watch

This is because of the additional "--" character in start script.
Removing this will resolve this issue.

**Note:** Empty/additional "--" character is present in some other scripts too.

> "test:cover": "npm run test -- --coverage ",
> "test:cover:CI": "npm run test:CI -- --coverage && cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js",
> "test:watch": "npm run test -- --watch",
> 

AND

>     "lint:watch": "npm run lint -- --watch",

**Comment by nickytonline** [comment]
@kallada1978, please fill out the issue template first so we can have more info about the issue. Thanks.

Before logging an issue:

* Ensure you have followed instructions in the [README](https://github.com/coryhouse/react-slingshot/blob/master/README.md)
* Read the [FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md)
* Look through existing [open](https://github.com/coryhouse/react-slingshot/issues) and [closed](https://github.com/coryhouse/react-slingshot/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone has reported the issue before
* Still stuck? Report a new issue

Node version:

npm version:

Operating system:

Command line used:

Steps to reproduce:

**Comment by nickytonline** [comment]
@kallada1978, are you still experiencing the issue? If so, as mentioned just add the issue template info.

**Comment by nickytonline** [comment]
Closing as no response from the issue opener. @kallada1978, feel free to reopen this if you are still having the issue and once you fill out the necessary issue info.
