### ISSUE TITLE
Add Bootstrap to project

### ISSUE THREAD

**Issue by MehrdadKamelzadeh** [coryhouse/react-slingshot#465]
When I add this line  **import 'bootstrap/dist/css/bootstrap.css';** to my react component my bootstrap classes are applied. but if I remove this line, they won't. 
I have seen in @coryhouse courses in Pluralsight that he just writes ClassName="someClass"and it works.
what shall I add to Slingshot to be able to use Bootstrap classes without the need of having the **import 'bootstrap/dist/css/bootstrap.css';** on top of every component?

**Comment by raythree** [comment]
You don't need to import (or require) bootstrap in every component file, you should only need to do it once in index.js.

**Comment by MehrdadKamelzadeh** [comment]
Thank you @raythree 
You are definitely right. It worked. But Shouldn't I add it somewhere in Webpack?

**Comment by raythree** [comment]
No, Webpack just bundles what you tell it to, and the place to do that is index.js for application wide assets like bootstrap.

**Comment by nickytonline** [comment]
Thanks for the assistance @raythree.

**Comment by nickytonline** [comment]
Closing as this is out of the scope of the project.
