### ISSUE TITLE
Webpack config target: 'web' should not be needed

### ISSUE THREAD

**Issue by doug2k1** [coryhouse/react-slingshot#467]
According to [Webpack docs](https://webpack.js.org/configuration/target/#target), 'web' is the default value for the target option. Both dev and prod configs has it set.

https://github.com/coryhouse/react-slingshot/blob/134b5f9b7dfcc3619a2af604e824f539b386ea47/webpack.config.prod.js#L21

**Comment by kwelch** [comment]
I am not against the explicitness, but the link being broken is not so good.

**Comment by coryhouse** [comment]
I just removed the outdated comment a8707054375b3f8c6ddd75f430e6156b75411299

Prefer leaving the setting to be explicit. Thanks!
