### ISSUE TITLE
Unable to run the boilerplate after running setup and running npm start

### ISSUE THREAD

**Issue by rbanate** [coryhouse/react-slingshot#469]
Unable to run boilerplate using version 7.

`internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at Object.exports.spawn (child_process.js:493:9)
`
Environment details:
Node version: 8.4.0

npm version: 5.4.0

Operating system: Ubuntu 16.4 LTS

Command line used: npm start

Steps to reproduce: 1) clone react-slingshot, 2) run "npm run setup" 3) run "npm start -s"

**Comment by coryhouse** [comment]
The package-lock.json was out of date, so I suggest trying again.

**Comment by nickytonline** [comment]
@rbanate, any luck running the boilerplate since the package-lock.json file was updated?

**Comment by rbanate** [comment]
@nickytonline unfortunately it still didn't work for me.

**Comment by nickytonline** [comment]
@rbanate can you re-clone the repo and try an `npm install --force`?

**Comment by marekstabla** [comment]
Had the same issue. Installing watchman helped.

`brew install watchman`

**Comment by jlaustill** [comment]
Installing watchman fixed it for me on OSX as well.

**Comment by nickytonline** [comment]
@rbanate, have you tried re-installing watchman?

**Comment by nickytonline** [comment]
@rbanate, here's the installation instructions, https://facebook.github.io/watchman/docs/install.html, and here's a post about installing it on Ubuntu, https://medium.com/@vonchristian/how-to-setup-watchman-on-ubuntu-16-04-53196cc0227c

**Comment by rbanate** [comment]
Hi Nick,

Thanks for the effort and apologies for the late reply as I have been busy
working on other stuff. I just tried cloning it and everything is working
well on my end already. Thanks

**Comment by nickytonline** [comment]
Ok, great to hear @rbanate.

**Comment by kwelch** [comment]
As a side note, I am planning on testing/re-documenting our setup process with my new MBP.
