### ISSUE TITLE
deleted spec files for demo and "can't resolve reference #/definitions/basicConfig from id #"

### ISSUE THREAD

**Issue by chaodonghu** [coryhouse/react-slingshot#472]
I've started a project without running the remove demo script however now that i'm pretty deep into the project I wanted to remove the starter files. Once I removed some of the spec and component files I keep getting this error in the console.

can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #

**Comment by coryhouse** [comment]
Thanks for pointing that out. Fixed!
