### ISSUE TITLE
disable BrowserSync

### ISSUE THREAD

**Issue by Aligertor** [coryhouse/react-slingshot#474]
Hi,

I added some Websocket functionality to my application. Now i have the problem that through browser sync i can not run multiple insances to test if my application updates itself properly.

Is it possible to add a start script for development that is not using BrowserSync?

**Comment by Aligertor** [comment]
nvm, its actually easier than it appeared to me in the first place.

just set ui to false in tools\srcServer.js
`
browserSync({
  port: 3000,
  ui: false,
  // {
  //   port: 3001
  // },
  server: {
    baseDir: 'src',
`

**Comment by kwelch** [comment]
Currently, this is not something we are willing to break away from within react-slingshot. 

I would recommend updating the `tools/srcServer.js` to use `webpackDevServer` this should be the closest setup to what is currently shipped with `browsersync` and will not lose ideal capabilities such as hot reloading and in memory file system.

**Comment by nickytonline** [comment]
@Aligertor, if you're not familiar with webpack's dev server, please refer to their docs, https://webpack.github.io/docs/webpack-dev-server.html.

**Comment by nickytonline** [comment]
Closing as we won't implement this.

**Comment by Aligertor** [comment]
thx for the hints

will check
