### ISSUE TITLE
Missing class properties transform.

### ISSUE THREAD

**Issue by seshvs** [coryhouse/react-slingshot#476]
Missing class properties transform.  -- Error when proptypes is declared inside component.

export default class App extends React.Component {
   static propTypes = { name: PropTypes.string.isRequired }; // Declare inside component rather than outside.

  render() {
    return (<Router/>);
  }
}

I'm learning react and redux. found your github very useful. I wanted to use the new syntax of declaring proptypes inside component. However while doing so, babel throws error. I tried to fix the configuration in package.json. But i failed. Will continue to try.

**Comment by mikedevita** [comment]
Its not missing, it's just included in the kit. Its fairly simple to add it though...
