### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#478]
React 16 has been released, so we need to look into upgrading it in the project. Maybe it's a simple upgrade, maybe not ;).

@coryhouse, since this is used for your courses on Pluralsight, are you OK with us doing an upgrade to React 16?

**Comment by coryhouse** [comment]
This isn't tied to my courses, so we're free to upgrade. That said, the ecosystem will need a few days to update their dependencies to accept React 16, so a bit early. But yes, let's upgrade soon.

**Comment by kwelch** [comment]
I will take this, I planned on doing some package upgrades tonight as it is.

**Comment by kwelch** [comment]
Had to do more than just packages (I think we expected that). There are also some prettier format changes in their. The prettier updates I am sorry for, the rest I feel really good about 😄

**Comment by kwelch** [comment]
Closed in #480
