### ISSUE TITLE
Integrate class-properties-transform for Babel?

### ISSUE THREAD

**Issue by Inlesco** [coryhouse/react-slingshot#485]
FEATURE REQUEST.

I'd like to see the class-properties-transform to be integrated by default into react-slingshot, so people can benefit from the new, less boilerplate-y syntax.

Here's more on this: https://babeljs.io/docs/plugins/transform-class-properties/

Are PRs accepted on very much needed improvements like this?

**Comment by coryhouse** [comment]
I'm open to a PR on this. :)

**Comment by nickytonline** [comment]
@Inlesco, could you create an issue for the feature request so we can track it and as @coryhouse mentioned, PRs welcome. ;)

**Comment by samit4me** [comment]
This repo is using `preset-stage-1` which includes `preset-stage-2` and `preset-stage-3`. According to the docs `preset-stage-2` includes the `transform-class-properties` so this should already work.

I tested this by modifying `FuelSavingsForm.js`

FROM:
```JS
class FuelSavingsForm extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.save = this.save.bind(this);
    this.onTimeframeChange = this.onTimeframeChange.bind(this);
    this.fuelSavingsKeypress = this.fuelSavingsKeypress.bind(this);
  }

  onTimeframeChange(e) {
    this.props.calculateFuelSavings(this.props.fuelSavings, 'milesDrivenTimeframe', e.target.value);
  }

  fuelSavingsKeypress(name, value) {
    this.props.calculateFuelSavings(this.props.fuelSavings, name, value);
  }
...
```

TO
```JS
class FuelSavingsForm extends React.Component {
  onTimeframeChange = (e) => {
    this.props.calculateFuelSavings(this.props.fuelSavings, 'milesDrivenTimeframe', e.target.value);
  };

  fuelSavingsKeypress = (name, value) => {
    this.props.calculateFuelSavings(this.props.fuelSavings, name, value);
  };

  save = () => {
    this.props.saveFuelSavings(this.props.fuelSavings);
  };
...
```

But this failed with the following error:
```
Module build failed: SyntaxError: Missing class properties transform.
```

After a bit of searching around, I found the following links and with some experimenting, I managed to get it working without any additional dependancies. I will open a PR shortly, showing the changes I made.

- https://github.com/babel/babel/issues/4628
- https://babeljs.io/docs/plugins/#plugin-preset-ordering

**Comment by coryhouse** [comment]
Wow, never knew ordering mattered! Thanks for sharing and the research! Would welcome a PR
