### ISSUE TITLE
Drop node 4 support

### ISSUE THREAD

**Issue by samit4me** [coryhouse/react-slingshot#490]
Currently, it looks like CI builds are failing and I suspect they have been since updating to react 16 in #480.

<img width="578" alt="screen shot 2017-10-20 at 7 25 58 pm" src="https://user-images.githubusercontent.com/3248531/31814355-b7e75950-b5cc-11e7-99c9-ab6861e70aaf.png">

After looking into this, it turns out enzyme swapped one of their dependencies `scapel` for `rst-selector-parser` which only supports node 5 and above. It also seems that node 4 is no longer active according to the [node release schedule](https://github.com/nodejs/Release), so my question is can this repo drop support for node 4?

For further details see comments in #488.

**Comment by kwelch** [comment]
Here are some note from when i initially looked at this issue. 

>Further review yarn is also the cause of this. It is failing due to the engines field which is only >enforced by yarn. Found in this enzyme issue airbnb/enzyme#1182

I am not against dropping Node v4, but we should look into supporting Node v7.

**Comment by samit4me** [comment]
That sounds good, supporting node 8 would be good also it's the next LTS.

You're right `yarn` throws the error and stops. That seems like a good thing as npm 2.15.11 throws the following:

```
npm WARN engine rst-selector-parser@2.2.2: wanted: {"node":">=5"} (current: {"node":"4.8.4","npm":"2.15.11"})
```

Then what feels like 2 hours later:

```
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/sam/.nvm/versions/node/v4.8.4/bin/node" "/Users/sam/.nvm/versions/node/v4.8.4/bin/npm" "i"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@16.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@16.0.0 wants react@^16.0.0-beta.5
npm ERR! peerinvalid Peer react-redux@5.0.5 wants react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0
npm ERR! peerinvalid Peer react-router-dom@4.2.2 wants react@>=15
npm ERR! peerinvalid Peer react-router-redux@5.0.0-alpha.6 wants react@^15
npm ERR! peerinvalid Peer enzyme-adapter-react-16@1.0.0 wants react@^16.0.0-0
npm ERR! peerinvalid Peer react-test-renderer@16.0.0 wants react@^16.0.0-beta.5
```

**Comment by samit4me** [comment]
Looks like there might be a fix for this soon, see https://github.com/airbnb/enzyme/issues/1285

**Comment by nickytonline** [comment]
I'm down with dropping node 4. ❎

**Comment by nickytonline** [comment]
It looks like airbnb/enzyme#1285 is sorted out. Are we all OK to drop Node 4 support?

**Comment by coryhouse** [comment]
I'm okay w/ it if we must, but I'm unclear. The last comment in the thread you linked says the Enzyme CI actually runs Node 4 too. Where did you read that they don't support Node 4?

**Comment by nickytonline** [comment]
I must have misread. In that case, ignore my last comment.

**Comment by samit4me** [comment]
Closing this issue as the problem with node 4 was resolved upstream in `rst-selector-parser`.
