### ISSUE TITLE
Warning: PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by imakou** [coryhouse/react-slingshot#492]
Node version: 6.3.1

npm version: 3.10.3

Operating system: MacOS

Command line used: yarn start

Does anyone faces the same warning??
I've installed prop-types package, but the warning is still showing.
The warning even happens when I don't do any change since the original example.

![screen shot 2017-10-20 at 10 07 30 am](https://user-images.githubusercontent.com/1507950/31824988-c213027e-b57e-11e7-97a4-575837eb35fb.png)

**Comment by coryhouse** [comment]
This isn't a slingshot issue - as the error says, you need to use prop-types instead of referencing propTypes directly in React since prop-types were extracted to a separate package in React 16.
