### ISSUE TITLE
Strip comments from production build

### ISSUE THREAD

**Issue by pantchox** [coryhouse/react-slingshot#493]
Before logging an issue:

* Ensure you have followed instructions in the [README](https://github.com/coryhouse/react-slingshot/blob/master/README.md)
* Read the [FAQ](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md)
* Look through existing [open](https://github.com/coryhouse/react-slingshot/issues) and [closed](https://github.com/coryhouse/react-slingshot/issues?q=is%3Aissue+is%3Aclosed) issues to see if someone has reported the issue before
* Still stuck? Report a new issue

Node version:
6.6.0

npm version:
3.10.3
Operating system:
Windows

Command line used:
npm run build

Steps to reproduce:
### my issue
Hi,

I am using react slingshot v5  (sorry it's old i know but i didnt have time to upgrade)
I am trying to add to the uglify webpack the "comments: false" to strip comments, it doesn't work.
Any idea why?
```
new webpack.optimize.UglifyJsPlugin({
      comments: false,
    })
```

**Comment by nickytonline** [comment]
@pantchox what is the error you're getting? Can you provide a trace? Also, can you clone the current react-slingshot and add 

```
new webpack.optimize.UglifyJsPlugin({
      comments: false,
    })
```

and see if you still get the error?

**Comment by pantchox** [comment]
I didn't say I get any errors, it just doesn't remove the comments.

If I run the production build dist in a production server I can view the source and see all the comments

**Comment by nickytonline** [comment]
@pantchox, this seems to be more of a webpack plugin issue than react-slingshot. I found this [issue about UglifyJS](https://github.com/webpack/webpack/issues/1205) about stripping comments .

Also, as I mentioned, try cloning the latest react-slingshot with your plugin configuration. We're using webpack 3 now. I believe v5 was webpack 2.

**Comment by pantchox** [comment]
Worse it was webpack 1.x
I will try after I come back from vacation and will give an update.
Thanks

**Comment by nickytonline** [comment]
:+1:

**Comment by nickytonline** [comment]
@pantchox, are you still having issues with this?

**Comment by pantchox** [comment]
yes but i am using an older version of react slingshot.
i need to refactor my code, i might just isolate it when i am about to release and clone react slingshot latest version , run the clean demo command and copy my files.

**Comment by nickytonline** [comment]
OK. I'm going to close this as the latest version does not exhibit this issue.
