### ISSUE TITLE
Dynamic meta tags?

### ISSUE THREAD

**Issue by paulwalczewski** [coryhouse/react-slingshot#498]
Hello,

has anybody managed to get Slingshot some basic functionality of dynamic meta tags, that can be read by site crawlers and scrapers (for example Facebook sharer mechanism)?

I've been playing around with [React Helmet](https://github.com/nfl/react-helmet), however that one adds dynamic meta tags only after site is rendered, which is too late for scrapers.
I suppose that the possible solution would be to have at least partial server side rendering in place, but I'm not sure how we can achieve that with Slingshot boilerplate. Any ideas? :)

**Comment by kwelch** [comment]
@paulwalczewski Sorry I am not familiar with SSR, but I will continue to push this to channels I know that have dev that are using SSR.

**Comment by paulwalczewski** [comment]
hi @kwelch, I've found a workaround solution for this.
Basically I serve production files as a .ejs templates rather than pure html. Then I can populate metatags directly from node - so they are both dynamic (using ejs variables) and generated on server.

Of course downside of getting them from node is that they don't come from react app itself any more, so there has to be separate handling, translations etc, so I guess it would still be awesome to get a  proper SSR solution for slingshot ;)

**Comment by kwelch** [comment]
I don't think there was ever an intent for Slinshot to handle SSR. If something is running in both client and server I personally would extract it to a package that could be a dependency or both.

**Comment by coryhouse** [comment]
Closing since React Slingshot isn't focused on server-side rendering support. Suggest alternatives like Next.js for that.
