### ISSUE TITLE
Unable to setup project

### ISSUE THREAD

**Issue by Suver1** [coryhouse/react-slingshot#499]
- Created a new NodeJS (linux) 'Droplet' from digitalocean
- Followed the instructions here: https://github.com/coryhouse/react-slingshot#get-started
- Failed upon running: npm run setup:
> npm ERR! Linux 4.4.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-slingshot@7.0.0 setup: 'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js'
npm ERR! Exit status 137

npm-debug.log:
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle react-slingshot@7.0.0~presetup: react-slingshot@7.0.0
6 silly lifecycle react-slingshot@7.0.0~presetup: no script for presetup, continuing
7 info lifecycle react-slingshot@7.0.0~setup: react-slingshot@7.0.0
8 verbose lifecycle react-slingshot@7.0.0~setup: unsafe-perm in lifecycle true
9 verbose lifecycle react-slingshot@7.0.0~setup: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/andy/git/react-slingshot/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle react-slingshot@7.0.0~setup: CWD: /home/andy/git/react-slingshot
11 silly lifecycle react-slingshot@7.0.0~setup: Args: [ '-c',
11 silly lifecycle   'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js' ]
12 silly lifecycle react-slingshot@7.0.0~setup: Returned: code: 137  signal: null
13 info lifecycle react-slingshot@7.0.0~setup: Failed to exec setup script
14 verbose stack Error: react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-slingshot@7.0.0
16 verbose cwd /home/andy/git/react-slingshot
17 error Linux 4.4.0-87-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-slingshot@7.0.0 setup: `node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js`
22 error Exit status 137
23 error Failed at the react-slingshot@7.0.0 setup script 'node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-slingshot package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node tools/setup/setupMessage.js && npm install && node tools/setup/setup.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-slingshot
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-slingshot
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Node version: 6.11.2

npm version: 3.10.10

Operating system: Ubuntu 16.04

Command line used: npm run setup

**Comment by coryhouse** [comment]
You need to run at least npm 4

**Comment by Suver1** [comment]
Okey. It worked after I upgraded npm. Thanks for the starter kit!

**Comment by nickytonline** [comment]
Glad you got it working @Suver1! Maybe see if Digital Ocean can upgrade their npm.
