### ISSUE TITLE
React-Router

### ISSUE THREAD

**Issue by kevinchiu** [coryhouse/react-slingshot#50]
What would be the "correct" way to add React Router to this?

**Comment by coryhouse** [comment]
Check out https://github.com/coryhouse/react-slingshot/issues/10 for an example. Also, check Redux's examples. The real world example uses React Router.

**Comment by kevinchiu** [comment]
Hmm. I get "page not found" when trying to follow the Github links in that thread.

**Comment by coryhouse** [comment]
Ah, try this: https://github.com/barrystaes/react-slingshot/tree/trebuchet

**Comment by barrystaes** [comment]
The "correct" way to add React-Router to this would be to use [react-router-redux](https://github.com/reactjs/react-router-redux) which uses `react-router` but keeps location state in `redux`. Follow their tutorial and you're set.

Also the branch linked here is moving to https://github.com/barrystaes/react-trebuchet/
