### ISSUE TITLE
Start script fails after initial installation - After merge #488

### ISSUE THREAD

**Issue by DennisOosterling** [coryhouse/react-slingshot#500]
Node version:
6.11.2

npm version:
3.10.10

Operating system:
Ubuntu 16.04

Command line used:
zsh

Steps to reproduce:

1. git clone git clone https://github.com/coryhouse/react-slingshot.git
2. `npm setup`
3. `npm start -s`

Jest can't find tests.

```
Starting app in dev mode...
No tests found
In /home/dennis/Documents/MB/react-slingshot
  50 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 12 matches
  testPathIgnorePatterns: /node_modules/ - 50 matches
Pattern: "--watch" - 0 matches 
```

**Comment by velser** [comment]
Can confirm issue. Managed to solve problem with removing -k flag, as `npm run test:watch` exits and everything is killed

**Comment by coryhouse** [comment]
Thanks for reporting. Fixed!

**Comment by coryhouse** [comment]
Get latest. I just realized #497 was the root cause, so I moved us back to using concurrently.
