### ISSUE TITLE
unminified the build

### ISSUE THREAD

**Issue by dotamir** [coryhouse/react-slingshot#502]
Hello, I have a problem with building app. It's completely done and I have the build but that build doesn't minify. I just run the build command and i didn't change webpack.prod.js.
And React tools got errors to me, which is not minified.

Node version: v8.9.0

npm version: 5.5.1

Operating system: Arch Linux

Command line used: npm run build

**Comment by coryhouse** [comment]
Does this issue occur with React Slingshot out of the box?

**Comment by dotamir** [comment]
Yep, I use Slignshot.

**Comment by coryhouse** [comment]
I just confirmed the production build runs fine for me on Mac. What error are you seeing?

**Comment by dotamir** [comment]
I don't have any errors on while the build command is run. Just react tools tell me this page is using unminified build of react!

**Comment by coryhouse** [comment]
That doesn't occur for me. `npm run build`, then open in browser:

https://www.dropbox.com/s/b954yfnrnut7pd5/Screenshot%202017-11-06%2007.53.17.png?dl=0

**Comment by konekoya** [comment]
I can confirm the production build works fine as well. I'm on Mac with the same node.js and npm version as @dotamir does.

**Comment by dotamir** [comment]
Sorry, I have an error in build progress and I didn't see that before, So it's working! Thank you again.
