### ISSUE TITLE
prebuild npm scripts order

### ISSUE THREAD

**Issue by sag1v** [coryhouse/react-slingshot#509]
Hi Cory, 
I'm using this starter kit quite a lot and i find myself often changing the order of the [prebuild](https://github.com/coryhouse/react-slingshot/blob/master/package.json#L21) scripts.

Currently it will run `clean-dist` first and then run `lint` and `test`.
`"prebuild": "npm run clean-dist && npm run lint && npm run test"`

I think if i have lint errors or failed tests (or any other things that may break my build) it shouldn't really do any build related processing, like deleting the `dist` folder.
By the way, sometimes on windows you can get an error if you try to build, and it fails, then try to build again.
I'm not sure but i think it is due to how windows is handling the I/O. maybe the process who deleted the folder didn't finished yet and another process is trying to re-create it. I'm not sure this is why i got errors but these errors are the reason i started changing the order in the first place, needless to say that it solved my problem. 

My suggest is to just re-order the scripts calls, let the `clean-dist` run only if the build isn't broken: 
`"prebuild": "npm run lint && npm run test && npm run clean-dist"`

**Comment by coryhouse** [comment]
Great point. I'd welcome a PR for the change.

**Comment by sag1v** [comment]
done #510

**Comment by coryhouse** [comment]
Thanks!

**Comment by sag1v** [comment]
No problems, and thank you!
