### ISSUE TITLE
implementing less loader

### ISSUE THREAD

**Issue by sag1v** [coryhouse/react-slingshot#511]
Hi Cory,
In my team we are working with `less` instead of `sass` and i often add the `less` loader to the project.  
Do you think it is OK to add the `less`  loader to webpack, so slingshot will support `less` out of the box? 
Maybe after or before the `sass` loader in the pipe.

**Comment by coryhouse** [comment]
Yeah, I can see your point. I'm open to a PR. @nickytonline @kwelch thoughts?

**Comment by nickytonline** [comment]
@coryhouse, I don't see any issues with supporting it OOTB.

**Comment by kwelch** [comment]
Sounds like a great idea! 👍

**Comment by sag1v** [comment]
Great. 
here you go #512

**Comment by nickytonline** [comment]
I forgot that we added the `package-lock.json` a while back.

**Comment by kwelch** [comment]
Merged.
