### ISSUE TITLE
Where to put Google Analytics

### ISSUE THREAD

**Issue by eferrervaughn** [coryhouse/react-slingshot#514]
Trying to add GA to my site. This https://developers.google.com/analytics/devguides/collection/analyticsjs/ recommends adding analytics.js in the <head> block of the html document. 

Looking at this boiler, there is no index.html only an index.js. So I am wondering where to load this script.

Do I add it in Root.js? Index.js? App.js?

Do I have to use a library like react-ga to intialize?

**Comment by kwelch** [comment]
The `index.html` is build using the [`index.ejs`](https://github.com/coryhouse/react-slingshot/blob/master/src/index.ejs) file in the root of the `src` directory.

I have used [`autotrack`](https://www.npmjs.com/package/autotrack) in the past and I love it. I highly recommend the `urlChangeTracker`.
