### ISSUE TITLE
production main.js name origin

### ISSUE THREAD

**Issue by sag1v** [coryhouse/react-slingshot#515]
Hi, 
I thought i know slingshot inside out but i guess i was wrong :)
after [this change](https://github.com/coryhouse/react-slingshot/commit/fdb0c42d84100b3f9419a9bb5d083934605e9f4a#diff-b83f3305d04bb1c8d674be30b5f9e1efR23) a while back, the name `bundle.js` changed.
Now it will be `main.js` inside the dist folder, but from where does webpack takes the configuration for this? is it the defaults for the chunks name? is it possible to modify it without hard-coding it as `newName.js` ?

**Comment by coryhouse** [comment]
Correct, it's the default. I'm not aware of a way to change it without hard-coding. But that's a better question for the webpack GitHub or StackOverflow. :)
