### ISSUE TITLE
npm remove-demo leaves demo app type definitions

### ISSUE THREAD

**Issue by listopher** [coryhouse/react-slingshot#516]
Running `npm remove-demo` leaves `src/types/index.js` intact, which defines types for the demo application.

**Comment by coryhouse** [comment]
Torn on that. Having the examples there to reference is useful though. And easy to delete if you don't want it.

**Comment by listopher** [comment]
It is a useful reference.

I only point it out because folders like `./src/utils` and `./src/styles` were completely removed with the demo, so the intent seemed to be that anything not needed for a fresh React/Redux project would be cleaned out.

Personally, I backed up the original `./src` folder before running `remove-demo` so I could keep referring to the entire example app, which is why the leftover `./src/types/index.js` file in my clean `./src` folder stuck out to me.
