### ISSUE TITLE
FuelSavingsPage.spec.js: test fails with `Invariant Violation: Could not find "store" ...`

### ISSUE THREAD

**Issue by iafan** [coryhouse/react-slingshot#517]
In current master, tests fail with this error:
```
FAIL  src/components/containers/FuelSavingsPage.spec.js

  ● <FuelSavingsPage /> › should display results when populated


    Invariant Violation: Could not find "store" in either the context or props of "Connect(FuelSavingsPage)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(FuelSavingsPage)".
```

It looks like Travis reports the same error now (but somehow the build is still marked as passed):
https://travis-ci.org/coryhouse/react-slingshot/jobs/317806116#L498-L513

**Comment by coryhouse** [comment]
Whoops! That was WIP that I meant to place on a feature branch. Thanks for the heads up! Fixed.

**Comment by iafan** [comment]
Thanks for clarifying and fixing! I guess the fact that alarmed me most that Travis didn't complain about failing tests, marking the build as passed. Was that expected?
