### ISSUE TITLE
Setup complete! Cleaning up... for 10 min. CTRL+C not working

### ISSUE THREAD

**Issue by nicolasflorth** [coryhouse/react-slingshot#518]
It got stuck here https://gyazo.com/275176214472f1c373a6eb7e7c94ba59 for about 10 min
I have the latest versions on all the tools needed to run this

**Comment by coryhouse** [comment]
I suspect it's because there was a breaking test. Can you get latest and try again?

**Comment by nickytonline** [comment]
@nicolasflorth, did you grab latest? Are you still experiencing the issue?

**Comment by coryhouse** [comment]
Closing since no reply. Please reply if issue persists.
