### ISSUE TITLE
Redux Thunk

### ISSUE THREAD

**Issue by nqs** [coryhouse/react-slingshot#52]
The only way I could get Thunk to work is by upgrading Redux to 3.1.3 and React Redux to 4.4.0.  Is this true?  If so, the template should probably be upgraded to use those versions by default.

**Comment by coryhouse** [comment]
I have redux-thunk working fine with older versions on a separate project, but I just updated Redux and React-redux to the latest versions in case there was indeed an issue on some older versions. Thanks!
