### ISSUE TITLE
Add Node 8 to CI

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#523]
Node 8 is the current LTS version and since we're considering dropping Node 4 support in #490, I think we should add 8 to CI. Thoughts @kwelch and @coryhouse? If everyone is on board, I can throw up a PR for this.

**Comment by coryhouse** [comment]
Good call. Thanks!

**Comment by nickytonline** [comment]
Cool. I'll throw up a PR later today or tomorrow for this.
