### ISSUE TITLE
Can I & how enable TSX support

### ISSUE THREAD

**Issue by zakkra** [coryhouse/react-slingshot#531]
I would like give files tsx extension and start using type script. Any hints how to do this?

**Comment by nickytonline** [comment]
Hey @zakkra, I forked react-slingshot and made a TS version, but it's quite out of date. If you want to take a peek at it for inspiration, it's available here, https://github.com/typescriptcrew/ts-react-slingshot.

I will update it at some point, but I honestly don't have time at the moment. If you want to see it get updated, pop a thumbs up in this comment, https://github.com/typescriptcrew/ts-react-slingshot/issues/21#issuecomment-331741154.

**Comment by zakkra** [comment]
Thank you

**Comment by nickytonline** [comment]
@zakkra, you can also look at https://github.com/nickytonline/ts-preact-starter/blob/master/webpack.config.ts. I discovered that you can have a webpack config in typescript. See https://twitter.com/nickytonline/status/930103460149809152
