### ISSUE TITLE
[Proposal] Add Storybook

### ISSUE THREAD

**Issue by kwelch** [coryhouse/react-slingshot#533]
The intent of this repo as I see it is to help get users up and ready with a custom yet standard toolkit for react. Storybook has a wonderful community and even greater toolsets building around it. I think it would be a helpful addition to this repo to get users looking at and seeing their components as small, individual, reusable pieces. 

Before going through the effort of incorporating this out of the gate, I wanted to gauge interest level and hear from others experience with it to determine if it is worth the time.

**Comment by coryhouse** [comment]
While I agree it's great (and quickly getting even better!), I don't see the need to include here. 

1. It's easy to add
2. It's not particularly universal in its use

**Comment by nickytonline** [comment]
Linking #371 for previous discussion about Storybook.

**Comment by kwelch** [comment]
Oh yeah, 😅 I forgot about that conversation. I still agree with keeping it out for those same reasons.
