### ISSUE TITLE
Feature Request for Cdn deployment  and Vagrant uses 

### ISSUE THREAD

**Issue by ARKKYN** [coryhouse/react-slingshot#534]
Please add support for using with php [ Laravel ] projects, and  add support for vagrant uses

SInce i Have a similar setup got me trouble

app 
  |
   -FRONTEND -- REACT SLINGSHOT .  ==> http://ASSET.APP.DEV/ .  ==> CDN
   |
   -BACKEND -- LARAVEL                            ==> http://APP.DEV/    ==> MAIN APPLICATION

SInce the project feasibility for other project based on other languages it would be better to add build script to create only asset files without chunk hash, But it may look bit out of scope we can add few build scripts for generating files only and Also the testing file in  diffrent folder with added support for automated testing like  selenium would be good 

if it optimized for creating files for cdn specific it would be good

**Comment by kwelch** [comment]
This sounds like a fork would be a better option. I am open to the idea, but I don't see that being something valid for this repo directly.

**Comment by nickytonline** [comment]
This is out of the scope of the project.

It would be helpful if you were more specific as to what doesn't work. What are the issues that you're running into? I haven't worked with Laravel, but PHP will just serve a page and from there you should be able to serve the bundled js we provide.

**Comment by nickytonline** [comment]
Also if it's a deployment issue, it would make more sense that it gets documented, which would be a nice first PR to our repo 😉.

**Comment by ARKKYN** [comment]
@nickytonline vagrant setup had little problem but sorted out with correct permission issues,
if it is an simplified project structure as a node package it wood be easier to create also add support for get environment values from config files also would be good option,  Since laravel has 
[React.mix()](https://laravel.com/docs/5.5/mix#react) it is easy to add react to laravel App, but not a cool setup like react-slingshot could be had with it easily

**Comment by nickytonline** [comment]
Glad to hear you got things sorted out @ARKKYN. It would be great if you could document how you got your deployment working. You could throw up a PR for react-slingshot's docs to help others. ;)

In the meantime, I'm going to close this as the issue appears to be resolved.
