### ISSUE TITLE
Are there any plans for supporting compiling to static files?

### ISSUE THREAD

**Issue by mishrakrishnakant** [coryhouse/react-slingshot#535]
I am currently trying to fiddle with `static-site-generator-webpack-plugin` and similar other webpack plugins to compile files at build time so that they can be served as static files.

I need this because I have noticed that crawlers cannot parse the meta tags on my site if it renders on client side. It will be nice to have some support for the use case. Also, alternatives like configuring robots.txt or provide in-built support for sitemap would be nice.

PS: Would love to collaborate on this if someone is interested.

**Comment by nickytonline** [comment]
I would strongly suggest having a look at [Gatsby JS](https://github.com/gatsbyjs/gatsby). It does exactly what you're looking for and it's built with React/GraphQL. And if you go that route, I strongly suggest deploying to [Netlify](https://www.netlify.com). They have great support for a lot of static site generators, [including Gatsby](https://www.netlify.com/blog/2016/02/24/a-step-by-step-guide-gatsby-on-netlify).

**Comment by coryhouse** [comment]
I agree with @nickytonline. Also check out next.js and after.js.

**Comment by mishrakrishnakant** [comment]
These comments were definitely helpful and do give me a starting point. Thanks for the help. Closing the issue.
