### ISSUE TITLE
Sudden laptop restarts

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#538]
Node version:
v6.11.1

npm version:
v5.3.0

Operating system:
mac

Command line used:
npm start / yarn start

Steps to reproduce:
Just started the development and fastenly saving code. It suddenly restarts the laptop out of nowhere. Probably with intense usage of linting.

**Comment by nickytonline** [comment]
Hi, thanks for reporting the issue.

That seems quite odd. What version of macOS are you using? How much memory do you have? Also, can you retry what you were doing but ensuring only your editor and whatever you use for your terminal are running?

What does the Activity Monitor display in terms of memory and CPU usage?

**Comment by gitlovenotwar** [comment]
Hi, thanks for the reply.

I'm on mac 10.13.2 with memory of 8gb and processor core i7.  

Sorry, I am not familiar how to read readings from activity monitor. I just observe it happens (twice now), with fast saving and refreshing the browser while webpack is still building.

**Comment by nickytonline** [comment]
@gitlovenotwar, I'm on the same specs for a machine on a MacBook Air and have never experienced this. I'm 99.9999999999% sure this is not react-slingshot, but I can offer some advice to figure out what's going on your machine.

I would suggest you try the following:

* For the [Activity Monitor](https://support.apple.com/en-ca/HT201464), just launch Spotlight and type in Activity Monitor. It will open the Activity Monitor Window and in there you can view what's using CPU time and consuming memory.

![image](https://user-images.githubusercontent.com/833231/36040197-cdeacfe8-0d92-11e8-9d95-bd30a9772a0b.png)

I would suggest you close all your applications except for your editor and whatever you use for terminal. Look at the Activity Monitor before you start making tonnes of saves to files. Now start working like you were before and see if you notice anything with high-memory consumption or high CPU usage.

* If you suspect it's a webpack issue, perhaps check out [their isssues](https://github.com/webpack/webpack/issues).
* If the computer restarts again, have a look at https://support.apple.com/en-us/HT200553.
* Maybe it's a hardware issue. You can [check your RAM](https://www.macworld.co.uk/how-to/mac/how-test-for-bad-or-faulty-ram-on-mac-3640485).

**Comment by gitlovenotwar** [comment]
From my activity monitor, it looks like node is using a lot of memory http://take.ms/ZpXZ5
