### ISSUE TITLE
Consider using greenkeeper.io on react-slingshot

### ISSUE THREAD

**Issue by nickytonline** [coryhouse/react-slingshot#541]
Greenkeeper is a great way to manage updates of our dependencies. It's free for OSS projects... us 😉, and is pretty easy to setup. Anytime there are updates to packages, we'll receive PRs from Greenkeeper, e.g.

![image](https://user-images.githubusercontent.com/833231/36362097-8f7e3884-14ff-11e8-9cd4-5c1c79e2fadb.png)

Just one less thing to manage.

Let me know what your thoughts are on this @coryhouse, @kwelch

**Comment by nickytonline** [comment]
There is also [david-dm](https://david-dm.org) which the Yeoman generator template appears to use. Discovered it when I enabled greenkeeper on one of my repos tonight.

**Comment by coryhouse** [comment]
I actually used Greenkeeper on Slingshot early on. Drove me nuts because we'd have a PR every day. Exhausting.

**Comment by nickytonline** [comment]
I guess that's a no? 🙃

**Comment by coryhouse** [comment]
Sorry Nick, my tone there was lousy. I woke up on the wrong side of the bed. I appreciate the suggestion. :) 

That said, if Greenkeeper could be throttled to open a PR once a month or so, that'd be more useful.

**Comment by nickytonline** [comment]
No offense taken. I'll look into it. I just added it to some of my personal repos to try out. I'll report back ;)
