### ISSUE TITLE
The app is not loading when javascript is disabled 

### ISSUE THREAD

**Issue by some81** [coryhouse/react-slingshot#543]
I can load the app if I disabled my javascript.

**Comment by nickytonline** [comment]
Hi @some81. The application is a single page applications (SPA) that uses JavaScript. It will require that JavaScript be enabled in the browser.

**Comment by kwelch** [comment]
A way to get around this would be to server side render so that the page is static.

**Comment by some81** [comment]
I want to the code base for my project, but how the SEO will work when the code does not render with js disabled

**Comment by kwelch** [comment]
For SEO I would also recommend server side rendering. Unfortunately, I am not knowledgable enough to help you move further on that. I would imagine this would be a good base project for it, but I may be wrong. There are other boilerplates that have it included.
