### ISSUE TITLE
Deprecated dependency - react-transform-hmr

### ISSUE THREAD

**Issue by Maxim-Filimonov** [coryhouse/react-slingshot#554]
Hi,
I have noticed that the package used in the project `babel-preset-react-hmre` is using [react-transform-hrm](https://github.com/gaearon/react-transform-hmr) which according to the README of the project has been deprecated in favour of [react-hot-reloader](https://github.com/gaearon/react-hot-loader)
Should the dependency be updated ?

**Comment by coryhouse** [comment]
PR welcomed! :)
