### ISSUE TITLE
Issue when run build

### ISSUE THREAD

**Issue by alex986** [coryhouse/react-slingshot#555]
Hello when put this command: npm run build:dist in the browser send 

![image](https://user-images.githubusercontent.com/5686138/38336825-c3a0ba32-3828-11e8-81d7-8ab9afbf3ec7.png)

this is in react-slingshot@5.0.0

node v8.9.4

npm 5.6.0

Help

**Comment by coryhouse** [comment]
Sorry for the slow reply. Please upgrade to the latest and open a new issue if this persists.
