### ISSUE TITLE
Material-UI beta RadioButtons and CheckBoxes don't work

### ISSUE THREAD

**Issue by bmmathe** [coryhouse/react-slingshot#557]
This may be a very specific use-case but when using React-Slingshot with Material-UI vNext radio buttons and check boxes don't work.  They seem to work using create-react-app (react-scripts) so I'm thinking the issue is how either babel or webpack is configured. 

To reproduce install material-ui next then add the RadioButtonsGroup demo from their vNext document page.  Reference RadioButtonsGroup somewhere in the demo react-slingshot app and notice that the radio buttons can't be selected.

https://material-ui-next.com/demos/selection-controls/

You can see how the radio buttons should behave on the link above.

If you go to the material-ui (beta branch) git repo and clone the example project and include the same RadioButtonsGroup demo it works fine.

**Comment by kwelch** [comment]
I agree this is a very specific case. I imagine this is not slingshot specific. Do you have a repo that shows how you configured the cross between the two repos?

**Comment by dawangdw** [comment]
I met this problem, too. But it works in production mode.

**Comment by nickytonline** [comment]
Feel free to continue the discussion, but closing as this does not appear to be react-slingshot specific.
