### ISSUE TITLE
Keep react-slingshot up to date

### ISSUE THREAD

**Issue by atif** [coryhouse/react-slingshot#558]
Is there a plan to export it as a package so that there's a possibility to keep the starter kit up to date?

**Comment by coryhouse** [comment]
I'd welcome a PR that does so. The most logical way to go about it is to fork create-react-app as a starting point. Their approach works great.

**Comment by atif** [comment]
Thanks for your feedback. I will try to come up with a PR. Any pointers in moving the react-slingshot as a package? I tried create-react-app in start but you end up using its eject feature in the end to get more control of the application.

**Comment by nickytonline** [comment]
Here's my two cents.

In regards to Create React App (CRA), generally you can have it bootstrap with custom scripts, e.g. https://github.com/kitze/custom-react-scripts. You could do that for the stuff you want to include from react-slingshot and make that the package. Also, just FYI, opt-in SASS support is coming to CRA, https://twitter.com/dan_abramov/status/985249038181289985.

I think the main issue you'd run into would be BrowserSync as CRA uses webpack dev server.
