### ISSUE TITLE
Stylelint Watch

### ISSUE THREAD

**Issue by NickToye** [coryhouse/react-slingshot#559]
Before logging an issue:

Node version: v8.11.1

npm version: 5.6.0

Operating system: OSX 10.13.3

Command line used: Atom Terminal

I'm basically trying to incorporate Stylelint and Stylelint watch into my process.  If I have errors it reports the lint errors and then fails.  

src/styles/generic/_generic.scratch.scss
 29:36  ✖  Unexpected named color "black"   color-named

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! Alchemy@1.0.0 stylelint: `stylelint "**/*.scss" --syntax scss`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the Alchemy@1.0.0 stylelint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If I have it on watch and there are no errors then it just returns me to the command line.

I appreciate that this may fall out of the scope of Slingshot, but I thought I would ask here to see if anyone else has a similar issue.

I have these packages installed:

"stylelint": "9.2.0",
"stylelint-order": "0.8.1",
"stylelint-scss": "3.0.1",
"stylelint-webpack-plugin": "0.10.4",

These are my commands:

"stylelint": "./node_modules/.bin/stylelint \"**/*.scss\" --syntax scss",
"stylelint:watch": "npm run stylelint -- --watch"

So when I run 'npm run stylelint' or 'npm run stylelint:watch' I get errors.  It's kind of doing its job but I'm trying to get it involved eventually with the single command that does the lot.

This is my plugin code: **webpack.config.dev.js**

new StyleLintPlugin({
      configFile: '.stylelintrc',
      failOnError: false,
      quiet: false,
      syntax: 'scss',
    }),

**Comment by kwelch** [comment]
Personally, I would recommend finding a way to incorporate this into an existing watching process, like `jest` or `webpack`. There is a [`stylelint-webpack-plugin`](https://www.npmjs.com/package/stylelint-webpack-plugin).

Additionally, `jest` is moving to be a bigger platform that can run other types of processes on watch. They have a [`jest-runner-stylelint`](https://www.npmjs.com/package/jest-runner-stylelint) that should cover your needs. 

I recently added a new jest-runner to in this PR https://github.com/eventbrite/eventbrite-sdk-javascript/pull/19 and it was pretty smooth.

**Comment by NickToye** [comment]
@kwelch yeah I have stylelint-webpack-plugin installed.  I'm not seeing the webpack config here.  Unless I've missed something.

**Comment by kwelch** [comment]
We have 2 files `webpack.config.dev.js` and `webpack.config.prod.js`. Is that what you are looking for? The implementation of the runner should be similar to the `lint-webpack-plugin`.

**Comment by nickytonline** [comment]
Hey @NickToye, just following up on this. You still in a jam or did @kwelch's advice help you out?

**Comment by NickToye** [comment]
I think the problem just went away,
