### ISSUE TITLE
routing issues 

### ISSUE THREAD

**Issue by BHARAT703** [coryhouse/react-slingshot#562]
@coryhouse 

Hi there, I am coming from plural sight.
Today I was configuring my router, but it seems like the code is not working any more. 
see below snap.

![image](https://user-images.githubusercontent.com/24493137/39475022-2635ee78-4d74-11e8-9f1a-d0cbb355e80d.png)

so, what is a perfect way to resolve this issue?
I can see there are lots of discussion on this topic like this one https://github.com/coryhouse/react-slingshot/pull/393

but as I am new to react, I don't know which one is correct. can you help me with this? thanks.

**Comment by kwelch** [comment]
The issue with this is not how you configured the route rather it is the syntax. 

Here is what you have 
```
export default {
	<Route path="/" component ={App} >
		<IndexRoute component={HomePage} />
		<Route path="about" component={AboutPage} />
	</Route>
};
```

This is on the right track but instead of returning this as an object, you need to format this as a function with that JSX returned. 
Here is an updated version. 

```
export default () => {
	return (
		<Route path="/" component ={App} >
			<IndexRoute component={HomePage} />
			<Route path="about" component={AboutPage} />
		</Route>
	);
};
```

By adding the arrow syntax this is now a function then we explicitly return the JSX. 

I hope this helps!

**Comment by BHARAT703** [comment]
yes, it's worked. errors gone.

I got in wrong direction because I totally followed video.
see this snap of that class in video.

![image](https://user-images.githubusercontent.com/24493137/39477553-3efb421a-4d7d-11e8-9c97-d8fb8b5c8e3a.png)

but anyway thanks for the help. really appreciate.

**Comment by coryhouse** [comment]
That snap of the video is correct - note that it's using parentheses, not curly braces. :)

**Comment by BHARAT703** [comment]
@coryhouse that's true, I just get confused when I saw errors first and then I started seeing conversation in #393, sorry guys..
