### ISSUE TITLE
The documentation seems outdated

### ISSUE THREAD

**Issue by DavidHenri008** [coryhouse/react-slingshot#567]
The documentation (readme and faq) seems outdated on some points. 
- [x] There is reference to buildhtml.js file but it does not exists.
- [x] The folder structure does not match the project concerning the containers and components folders.
- [x] The folder structure lack some files like assetsTransformer.js, testCi.js, ...
- [x] The description of the script seems wrong concerning the prestart, I do not see the delete call.

Thanks.

**Comment by coryhouse** [comment]
Thanks! fixed.
