### ISSUE TITLE
Usage of Object.assign

### ISSUE THREAD

**Issue by DavidHenri008** [coryhouse/react-slingshot#568]
Why using the object-assign package dependency when the Object.assign seems to work properly with babel compilation?

Thanks.

**Comment by kwelch** [comment]
That came as part of [this commit](https://github.com/coryhouse/react-slingshot/commit/a2c855b0c7b984e85745a74d2bafa231e5259f2d) to allow for support in IE.

**Comment by DavidHenri008** [comment]
But the babel is ran on the npm start isn't it?
