### ISSUE TITLE
Add React-Router

### ISSUE THREAD

**Issue by S1E-** [coryhouse/react-slingshot#57]
This is great boilerplate but if react router is also added to it then it will be more faster for developers to start developing with it

**Comment by coryhouse** [comment]
I left it out initially because it's not always necessary.

That said, you're not the first to ask. Submit a PR and I'll consider adding it.

**Comment by coryhouse** [comment]
If others really feel strongly about whether React Router belongs in the kit, this is the place to chime in...

**Comment by attilad** [comment]
Actually I like your kit because it DOESN'T include it.  I use React Router sometimes but I don't need it for every project.

**Comment by S1E-** [comment]
But it is always easier to remove a functionality than adding it.

**Comment by attilad** [comment]
That's a good point.

**Comment by PetaPetaPeta** [comment]
It would be nice to have it included along with a toggle function for turning it on or off.

**Comment by coryhouse** [comment]
Great points. I'm open to it if someone submits a pull request. One important point is the example app should be enhanced to have simple navigation in order to display the router working.

**Comment by coryhouse** [comment]
Added in [2.0 release](https://github.com/coryhouse/react-slingshot/releases/tag/v2.0.0)
