### ISSUE TITLE
macOS High Sierra installation requires "watchman" and "hard-source-webpack-plugin: 0.7.4"

### ISSUE THREAD

**Issue by BR0kEN-** [coryhouse/react-slingshot#572]
After running `npm start -s` on macOS 10.13.4 I got the errors described in https://github.com/facebook/create-react-app/issues/871. After doing `brew install watchman` I got https://github.com/mzgoddard/hard-source-webpack-plugin/issues/316. After changing the version of `hard-source-webpack-plugin` to `0.7.4` in `package.json` and running `npm install` the `npm start -s` gave an expected result.

Shall we consider updating the documentation and mention `watchman` as a requirement for macOS Sierra and above and update the `hard-source-webpack-plugin`?

```bash
BR0kEN@Macintosh:~ $ node --version
v10.3.0
BR0kEN@Macintosh:~ $ npm --version
6.1.0
```

**Comment by coryhouse** [comment]
Great point, yes. Would you be willing to open a PR to add this info?

**Comment by Jorgu5** [comment]
I had run into the same problem today. I've installed watchman with brew and updated the hard-source plugin, but still, i'm fighting with this on High Sierra:

` RUNS  src/components/containers/FuelSavingsPage.spec.js
[hardsource:f3fa523e] Tracking node dependencies with: package-lock.json, yarn.lock.
[hardsource:f3fa523e] Reading from cache f3fa523e...
✖ ｢wdm｣: Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'
    at Object.parseError (/Users/jorgus/Desktop/offer/node_modules/jsonlint/lib/jsonlint.js:55:11)
    at Object.parse (/Users/jorgus/Desktop/offer/node_modules/jsonlint/lib/jsonlint.js:132:22)
    at Object.exports.parse (/Users/jorgus/Desktop/offer/node_modules/jsonlint/lib/jsonlint.js:417:53)
    at module.exports.data (/Users/jorgus/Desktop/offer/node_modules/hard-source-webpack-plugin/lib/util/parseJson.js:9:34)
    at Append2._readFile (/Users/jorgus/Desktop/offer/node_modules/hard-source-webpack-plugin/lib/SerializerAppend2.js:164:19)
 PASS  src/components/containers/FuelSavingsPage.spec.js

 RUNS  src/components/AboutPage.spec.js`

Any ideas what could be the issue?

**Comment by BR0kEN-** [comment]
@coryhouse, PR has been opened.
@Jorgu5, are you using bare `react-slingshot` without any modifications?

**Comment by nickytonline** [comment]
@Jorgu5, sounds like you might have an encoding issue. It looks like you have bad characters in a file. Not the same project, but the error you're getting is discussed here, https://github.com/josdejong/jsoneditor/issues/238.

**Comment by Jorgu5** [comment]
Thanks, after removing and downloading again entire slingshot, everything works again. Not sure why.
