### ISSUE TITLE
Does this boilerplate support debugging with something like VS Code?

### ISSUE THREAD

**Issue by mikedevita** [coryhouse/react-slingshot#574]
I am trying to get breakpoints working in VS Code with this boilerplate, does anyone have a working  configuration example or will the CRA (create-react-app) method work for this?

**Comment by mikedevita** [comment]
Looks like with adding `launch.json` to my `.vscode` folder with the following contents and adding breakpoints seems to work.

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [

    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "sourceMapPathOverrides": {
        "webpack:///src/*": "${webRoot}/*"
      }
    }
  ]
}

```

**Comment by nickytonline** [comment]
Mike you can have a launch configuration like you have and you can also just add a config to attach to Chrome. To do this though, Chrome has to be running with [remote Debugging enabled](https://github.com/Microsoft/vscode-chrome-debug/blob/master/README.md). If you want to spruce up the [FAQ section for Debugging in VS Code](https://github.com/coryhouse/react-slingshot/blob/master/docs/FAQ.md#debugging-in-visual-studio-code), PRS are always welcome. 😉

**Comment by mikedevita** [comment]
@nickytonline PR submitted 😄.
