### ISSUE TITLE
Move past react-router-redux as it is now deprecated

### ISSUE THREAD

**Issue by blakeperdue** [coryhouse/react-slingshot#575]
**Is your feature request related to a problem? Please describe.**
The problem is react-router as of 4.3.0 has removed react-router-redux as it is deprecated: https://github.com/ReactTraining/react-router/releases/tag/v4.3.0

> One other thing to mention, while I have your attention, is the deprecation of react-router-redux. It's no longer maintained and has a number of fundamental problems (particularly around time travel). 

**Describe the solution you'd like**
Upgrade to the latest react-router version and remove the react-router-redux package.

**Describe alternatives you've considered**
Consider using existing app as is for the time being ;)

**Additional context**
None, thank you for your awesome kit!

**Comment by nickytonline** [comment]
Thanks for reporting @blakeperdue. Would you be willing to put up a PR for this? Also, thanks for the kind words. 👍

**Comment by blakeperdue** [comment]
Looks like this will require an upgrade to React 16.4.0 which has some deprecations (like `componentWillReceiveProps`). Shouldn't be a big PR though as it doesn't look like you're using many of those deprecations in Slingshot.

**Comment by m10** [comment]
should be closed as of #581

**Comment by kwelch** [comment]
Agreed thanks for following up on this.
