### ISSUE TITLE
ES6 features is not working.

### ISSUE THREAD

**Issue by chaudharykiran** [coryhouse/react-slingshot#579]
ES6 features is not working.

I am trying to using ES6 features in React but arrow function is not working. Spread operator is also not working.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser chrome, safari
 - Version 68

**Additional context**
`Module build failed: SyntaxError: Unexpected token (24:11)
 
>  onSubmit = (e) => {
                    ^
      e.preventDefault();
     const err = this.validate();
     if (!err) {
`

**Comment by coryhouse** [comment]
Arrow functions on class fields and spread operator work just fine in the example app, so must be something in your config. Try these features in the unchanged Slingshot demo app and you'll see they work fine.
