### ISSUE TITLE
use cssnano for css minimification

### ISSUE THREAD

**Issue by m10** [coryhouse/react-slingshot#582]
**Describe the bug**
Css Minimization does not work.
The minimize option of css-loader is deprecated since 1.0.0 in favour of using cssnano with postcss-loader 
https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md

**Proposed solution**
Use cssnano as a postcss plugin like autoprefixer

**To Reproduce**
1. compile production build with some css
2. Notice css is not minified

**Expected behavior**
Css should be minified in production build

**Comment by m10** [comment]
#583

**Comment by nickytonline** [comment]
Thanks for opening the issue. Just read the link to css-loader docs and indeed you are correct. It's deprecated in favour of cssnano

**Comment by coryhouse** [comment]
Fix merged. Thanks!
