### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by vonwao** [coryhouse/react-slingshot#59]
otto at Ottos-MacBook-Pro in ~/code/meteor/projects/react-slingshot on master
$ npm start -s
sh: babel-node: command not found
otto at Ottos-MacBook-Pro in ~/code/meteor/projects/react-slingshot on master
$ module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/lang/cloneDeep'
    at Function.Module._resolveFilename (module.js:325:15)

**Comment by coryhouse** [comment]
Odd. Running fine on my Macbook pro.

1. Did you get any errors from npm install?
2. Did you happen to have a previous version installed? With the latest release, it's important to delete node_modules before doing an npm install.

**Comment by vonwao** [comment]
No, but I had an old version of node.  I ran npm install again, but it seemed to do nothing. Then I upgraded to node 4 using nvm.  So, I will try deleting node modules and start again.

**Comment by vonwao** [comment]
Ok, it worked now, thanks.  I didn't think about deleting node_modules

**Comment by coryhouse** [comment]
Great to hear!
