### ISSUE TITLE
Can not use react-table

### ISSUE THREAD

**Issue by bachnxhedspi** [coryhouse/react-slingshot#598]
**Describe the bug**
I would like to use [react-table](https://react-table.js.org/) for displaying data in table. But seem to a conflict of babel version. 

**To Reproduce**
1. Install react-table: npm install --save react-table
2. The program will fail when run any test (during npm start/build/...). The error is:

` FAIL  src/components/AboutPage.spec.js
   Test suite failed to run

    Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

      at throwVersionError (node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
      at Object.assertVersion (node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
      at _default (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
      at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
          at Array.map (<anonymous>)
`
3. Because of that I can not create test or build the program

**Request**
Please tell me how to use react-table with slingshot; I think there will be a way to specific jest to load babel 7.0.0

**Comment by kwelch** [comment]
Have you pulled latest version of slingshot? Currently we are using babel@7, see our [package.json](https://github.com/coryhouse/react-slingshot/blob/master/package.json#L44)

**Comment by Downloaddave** [comment]
**Description**
Looks like I'm running into a similar issue. I'm running node version 10.1 and it's companying npm version 5.6.0. I'm required to run node 10.1 because Azure only supported Node 10.1 when I started the project.

**Repro**
Run `npm install`
Run `npm start`

```
  ● Test suite failed to run

    Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

      at throwVersionError (node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
      at Object.assertVersion (node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
      at _default (node_modules/@babel/plugin-proposal-class-properties/lib/index.js:81:7)
      at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.544s
Ran all test suites.
```

**Troubleshooting Notes**
I checked my package.json agains the latest found in this repo. I can confirm that I have babel-core 7.0.0-bridge.0 module that (I think) is supposed to resolve this issue is part of the file.

```
"devDependencies": {
    "@babel/cli": "7.0.0",
    "@babel/core": "7.0.0",
    "@babel/node": "7.0.0",
    "@babel/plugin-proposal-class-properties": "7.0.0",
    "@babel/plugin-transform-react-constant-elements": "7.0.0",
    "@babel/polyfill": "7.0.0",
    "@babel/preset-env": "7.0.0",
    "@babel/preset-react": "7.0.0",
    "autoprefixer": "9.1.3",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "9.0.0",
    "babel-jest": "23.4.2",
    "babel-loader": "8.0.0",
    "babel-plugin-transform-react-remove-prop-types": "0.4.15",
    "browser-sync": "2.24.7",
    "chalk": "2.4.1",
    "concurrently": "4.0.1",
    "connect-history-api-fallback": "1.5.0",
```

I suspect that issue may be related with the package-lock.json where it's loading `babel-core: 6.26.3`

```
    },
    "jest-runtime": {
      "version": "23.6.0",
      "resolved": "https://registry.npmjs.org/jest-runtime/-/jest-runtime-23.6.0.tgz",
      "integrity": "sha512-ycnLTNPT2Gv+TRhnAYAQ0B3SryEXhhRj1kA6hBPSeZaNQkJ7GbZsxOLUkwg6YmvWGdX3BB3PYKFLDQCAE1zNOw==",
      "dev": true,
      "requires": {
        "babel-core": "6.26.3",
        "babel-plugin-istanbul": "4.1.6",
        "chalk": "2.4.1",
        "convert-source-map": "1.6.0",
        "exit": "0.1.2",
```

However, I'm not sure how to resolve this (there are a lot of places in package-lock.json that use `babel-core: 6.26.3` ). Perhaps I should do a global find and replace? Any suggestions?

**Comment by coryhouse** [comment]
Try deleting package-lock and node_modules then npm install again

**Comment by bachnxhedspi** [comment]
@Downloaddave 
Hi, I found out that the problem was because of jest-cli. It was solved after I upgrade jest-cli to 24.1.0

**Comment by nickytonline** [comment]
Would you like to put a PR up to update the jest dependency?

**Comment by Downloaddave** [comment]
Thank for the quick response. Do we need to update both the jest-cli and jest dependency in the package.json to 24.1.0?

**Comment by nickytonline** [comment]
Probably best to do both.
