### ISSUE TITLE
Unexpected token ) on line 105 of node_modules\hard-source-webpack-plugin\index.js

### ISSUE THREAD

**Issue by companyjuice** [coryhouse/react-slingshot#599]
**Describe the bug**
When attempting to run a new project, a node_module called "hard-source-webpack-plugin" throws a syntax error

**To Reproduce**
1. $ git clone https://github.com/coryhouse/react-slingshot.git
2. $ cd react-slingshot
3. $ npm run setup
4. $ npm start -s
5. See error in console...
c:\webroot\react-slingshot\node_modules\hard-source-webpack-plugin\index.js:105
  );
  ^

SyntaxError: Unexpected token )

**Expected behavior**
Should build without error.

**Screenshots**

**Desktop (please complete the following information):**
Node version:
v8.11.4

npm version:
5.6.0

Operating system:
Windows 10

**Comment by boshea** [comment]
I am also seeing this error with Node version 6.14.4 on Ubuntu Linux 16.04.  It happens everywhere that there is a list in parentheses that has an extra comma between the last element and the closing parenthesis, i.e. ( "one", "two", "three", )  // Note the extra dangling comma.  Do I need to add a .eslintrc file that allows this syntax?

$ npm start -s
Starting app in dev mode...
/home/boshea/github/team-tracker/web-ui/react-slingshot/node_modules/hard-source-webpack-plugin/index.js:105
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Module._compile (/home/boshea/github/team-tracker/web-ui/react-slingshot/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:586:10)
    at Object.newLoader [as .js] (/home/boshea/github/team-tracker/web-ui/react-slingshot/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by nickytonline** [comment]
Eslint config in the project should be fine. Our builds aren't failing. I believe the minimum node version now that we support is 8 due to changes in jest? cc: @coryhouse.

Our CI currently passes for Node 8, 9 and 10 on Windows and Linux (Ubuntu).

**Comment by boshea** [comment]
Thanks @nickytonline. Can you verify the requirement for Node version 8, and update the documentation accordingly?  Currently the Initial Machine Setup section of the documentation says that a minimum of version 4.0.0 is required, but recommends version 5.0 or greater.

https://github.com/coryhouse/react-slingshot#initial-machine-setup

In the mean time, I will use the pluralsight-redux-starter project since it isn't a moving target, and I'll upgrade once this issue is resolved.

Thanks.
-brian

**Comment by konekoya** [comment]
Agreed with @boshea since node.js 4.0.0 is no longer maintained. 
Source: https://github.com/nodejs/Release

**Comment by coryhouse** [comment]
Thanks all. I just updated package.json's engine prop and the docs to require Node 8.

**Comment by nickytonline** [comment]
Just following up @boshea. Any issues for you now if you grab the latest from master?

**Comment by nickytonline** [comment]
Closing as this appears to be resolved.
