### ISSUE TITLE
Environment variables not accessible

### ISSUE THREAD

**Issue by rizvified** [coryhouse/react-slingshot#603]
I'm trying to setup start and build commands for three different environment namely Dev, QA and Prod as follows in package.json

`    "start:dev": "NODE_ENV=DEV npm run sass -s && npm-run-all --parallel open:src",
    "start:qa": "NODE_ENV=QA npm run sass -s && npm-run-all --parallel open:src",
    "start:prod": "NODE_ENV=PROD npm run sass -s && npm-run-all --parallel open:src",   
     "build:dev": "NODE_ENV=DEV babel-node tools/build.js",
    "build:qa": "NODE_ENV=QA babel-node tools/build.js",
    "build:prod": "NODE_ENV=PROD babel-node tools/build.js",`

And i am using a variable to link to different API endpoints who's value is based on these env variable i use.

`const CURRENT_ENV = process.env.NODE_ENV
`

Now the problem is that process.env.NODE_ENV is undefined .. or for that matter, any environment variable i pass. 

Isn't there any support for environment variables in this boilerplate?

**Comment by coryhouse** [comment]
You can use the `dotenv` package at the top of any Node file where you want to read env vars:

`require("dotenv").config();`
