### ISSUE TITLE
Unhandled 'error' event #167

### ISSUE THREAD

**Issue by tfak** [coryhouse/react-slingshot#604]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'F:\sasa\android\app\build\generated\source\r\debug\android\arch\core\R.java'
Emitted 'error' event at:
    at NodeWatcher.<anonymous> (F:\sasa\node_modules\sane\src\node_watcher.js:306:14)
    at F:\sasa\node_modules\graceful-fs\polyfills.js:282:31
    at FSReqWrap.oncomplete (fs.js:154:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sasa@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sasa@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tf\AppData\Roaming\npm-cache\_logs\2019-01-04T07_43_17_428Z-debug.log

F:\sasa>npm -v
6.5.0

**Comment by coryhouse** [comment]
Slingshot only supports Node 8+.
