### ISSUE TITLE
Feature Request: Update README "Get Started" to include YARN details along with existing NPM details.

### ISSUE THREAD

**Issue by DaneTheory** [coryhouse/react-slingshot#607]
**PROBLEM**
Currently, the react-slingshot README section "Get Started" provides instruction details which assumes the user to be utilizing NPM as their preferred package-manager for Node. However, if the user follows the instructions as written, but utilizes YARN instead of NPM, then it is not immediately obvious what to do, and more importantly, the final step in the process fails. YARN does not recognize the `-s` flag to enable silent mode as NPM does, and instead requires a different flag of `--silent` to successfully enable silent mode on script run. See **ADDITIONAL CONTEXT** for broader explanation as to why this is a relevant problem that should be fixed.

**SOLUTION**
Update README section "Get Started" to include the the NPM equivalent YARN scripts alongside the already provided NPM scripts listed.   

**ALTERNATIVES**
Seems like this is pretty straight forward. 

**ADDITIONAL CONTEXT**
React-Slingshot supports YARN already. Can't see why this wasn't just included when support was added. 
See: #319 and #292

**Comment by nickytonline** [comment]
Thanks for the feature request @DaneTheory. PRs are definitely welcome for updating the docs!

**Comment by nickytonline** [comment]
Closing as per comments in #610.
