### ISSUE TITLE
Error executing "heroku config:set NPM_CONFIG_PRODUCTION=false"  

### ISSUE THREAD

**Issue by roberto-rodriguez** [coryhouse/react-slingshot#612]
Im following hte steps here http://www.latrovacommits.com/en/2017/12/14/how-publish-dist-folder-heroku/ to setup the starter in heroku, following the **Express with server side building** and in the last step I need to execute this command line:
`
heroku config:set NPM_CONFIG_PRODUCTION=false`

But I get this error in the console:

 **[UNKNOWN] Error Plugin: heroku: UNKNOWN: unknown error. open 'H:\_netrc'**

I have heroku installed in my PC, and Im able to create and push to apps in heroku.. any idea what Im missing here?

Thanks!

**Comment by nickytonline** [comment]
I don't have any experience with Heroku and this is out of scope for the project. Your best bet would be to contact Heroku support.

I also see that you added a comment on the heroku cli repo. Hopefully you can assume answers there, https://github.com/heroku/cli/issues/694#issuecomment-478414749
