### ISSUE TITLE
Question: Any interest in putting together a premium version for sale on SugarKubes?

### ISSUE THREAD

**Issue by wrannaman** [coryhouse/react-slingshot#616]
Hi @coryhouse, congrats on the traction! Would you be interested in putting together a premium version of this repo to sell on [SugarKubes](https://sugarkubes.io)? It's a code and container marketplace I'm putting together.

**Comment by coryhouse** [comment]
No thanks, but appreciate the offer!

**Comment by wrannaman** [comment]
no worries, thanks for the response!
