### ISSUE TITLE
remove-demo npm script is not removing store.spec.js.snap file

### ISSUE THREAD

**Issue by Gr8manish** [coryhouse/react-slingshot#624]
**Describe the bug**
remove-demo npm script is not removing store.spec.js.snap file

**To Reproduce**

- run **npm run remove-demo**
- store.spec.js.snap file is still there in snapshots

**Expected behaviour**
store.spec.js.snap should also be removed

**Comment by coryhouse** [comment]
Resolved via #646. Thanks @kkankala!
