### ISSUE TITLE
Server-side 404 error on route with period in url

### ISSUE THREAD

**Issue by samuelneff** [coryhouse/react-slingshot#625]
**Describe the bug**

I'm getting 404 error from dev server on this URL:

`http://localhost:3000/fuel-savings/test.two`

This URL works fine:

`http://localhost:3000/fuel-savings/test`

Every URL that that I tested that has a period in it causes the 404.

I cloned react-slingshot and ran it almost exactly as is. I had to change react-dom from 16.8.x to 16.9.0 for the install to succeed (corp npm cache doesn't have 16.8.x), but otherwise zero changes.

There is no output in the node console when I try to load this route. 

I originally ran into this problem in my app and then made a clean clone of `react-slingshot` to test with that and see the same error.

*To Reproduce**
1. Go to `http://localhost:3000/fuel-savings/test`
2. Notice it renders fine, the fule-savings page (the /test is ignored)
3. Navigate to `http://localhost:3000/fuel-savings/test.two`
4. See 404 error

**Expected behavior**

Page should render same as url without period in it.

**Screenshots**

<img width="882" alt="Screen Shot 2019-09-04 at 10 04 29 PM" src="https://user-images.githubusercontent.com/1799385/64306233-0d645500-cf60-11e9-95fa-c1b6350ff3da.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version Version 76.0.3809.100 (Official Build) (64-bit)

Thanks!!

**Comment by nickytonline** [comment]
This seems more like a react-router issue. Consider taking a peek in the list of issues there, https://github.com/ReactTraining/react-router/issues

**Comment by samuelneff** [comment]
Thank you for reviewing and responding.

The error is server side. The server is sending a 404 when it should have sent the root index page. 

Not related to react router. That's client side.

Sam

**Comment by nickytonline** [comment]
Ahh didn't realize it was a server-side error. I thought you had a client side route defined that was erroring out. 🙃

**Comment by kwelch** [comment]
This was an error in https://github.com/webpack/webpack-dev-server/pull/303. 

According to the docs, the fix is small: https://webpack.js.org/configuration/dev-server/#devserverhistoryapifallback

We just need to flip `historyApiFallback.disableDotRule` to `true`.

**Comment by samuelneff** [comment]
@kwelch  Thank you! It wasn't quite that simple because once `disableDotRule` is set, then the `bundle.js` call gets redirected to root too, so no JS is served. Found fix on another thread:

https://github.com/bripkens/connect-history-api-fallback/issues/40

Which is to also include an accept header filter.

```json
{
  disableDotRule: true,
  htmlAcceptHeaders: ['text/html', 'application/xhtml+xml']
}
```

Is there any reason this should not be done in `react-slingshot` by default? I would be happy to submit a PR.

**Comment by nickytonline** [comment]
Probably makes sense to add it. Thoughts @coryhouse?

**Comment by coryhouse** [comment]
Fine by me :)

**Comment by samuelneff** [comment]
I'll submit a PR, hopefully this weekend.

**Comment by kwelch** [comment]
I am going to recommend that we leave this open until we fix it with the PR. Thanks!

**Comment by samuelneff** [comment]
PR created https://github.com/coryhouse/react-slingshot/pull/627

**Comment by nickytonline** [comment]
Thanks for your contribution @samuelneff! 👏
