### ISSUE TITLE
Update README.md to thank all our wonderful contributors by name!

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#63]
This is long overdue! :) Thanks everyone!

**Comment by nickytonline** [comment]
@coryhouse I created a CONTRIBUTORS.md file which seems to be more standard. Available via PR #66

**Comment by nickytonline** [comment]
@coryhouse I spoke too quick. I'm actually not sure what is standard. There is the CONTRIBUTORS.md, package.json file [contributors section](https://docs.npmjs.com/files/package.json#people-fields-author-contributors) and also your suggestion to put it in the README.md `¯\_(ツ)_/¯`

**Comment by coryhouse** [comment]
I think you're right that CONTRIBUTORS.md is the most popular standard of the bunch. Thanks for compiling the names!
