### ISSUE TITLE
why there are yarn.lock and package-lock.json both present?

### ISSUE THREAD

**Issue by adamchenwei** [coryhouse/react-slingshot#643]
Just wondering why. Since mostly I see it as a mishap. is it?
Also because I am keep getting error after run `npm run setup`

<img width="1079" alt="Screen Shot 2020-02-20 at 10 02 28 PM" src="https://user-images.githubusercontent.com/4201698/75000588-c3e3c580-542c-11ea-90c8-b8714281c34f.png">

My versions
<img width="320" alt="Screen Shot 2020-02-20 at 10 03 17 PM" src="https://user-images.githubusercontent.com/4201698/75000600-d100b480-542c-11ea-95e7-5808bed4d8bd.png">

**Comment by nickytonline** [comment]
Thanks for opening this issue @adamchenwei! I believe both are present because at some point we were supporting both yarn and npm, and then we opted for just npm.

I'm pretty sure the yarn.lock file can be removed from the project, but I'll let @kwelch and @coryhouse  chime in.

**Comment by kwelch** [comment]
I agree we should centralize around just one of them.

**Comment by coryhouse** [comment]
I vote we dump Yarn.

**Comment by nickytonline** [comment]
I'm fine with just npm as well.

**Comment by kwelch** [comment]
I prefer how yarn handles lock files, but I am good with npm. 

Alternative idea, since this is a template repo, do we want to include neither? And add something to the setup script that asks and removes one from the ignore file?

**Comment by coryhouse** [comment]
I just removed yarn.lock. Closing. Thanks guys!
