### ISSUE TITLE
Implementation of redux-persist with react-slingshot

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [coryhouse/react-slingshot#647]
**Is your feature request related to a problem? Please describe.**
To persist the data in the store that will hold it even after page reloads.

**Describe the solution you'd like**
I  want to persist the data in the store came from the API calls using redux and thunk on app load. for that, I want to integrate redux-persist.

**Describe alternatives you've considered**
No any.

**Additional context**
want to use this but I can't.
https://www.npmjs.com/package/redux-persist

**Comment by coryhouse** [comment]
What is stopping you from using redux-persist?

**Comment by muhammadawaisshaikh** [comment]
too complex to integrate redux-persist into configureStore, and getting issues after one another.

**Comment by muhammadawaisshaikh** [comment]
finally, I have done it.

**Comment by muhammadawaisshaikh** [comment]
@coryhouse can I open the PR for this thing if you guys find this helpful? Otherwise I have to close this issue. Thanks

**Comment by coryhouse** [comment]
Glad to hear you got it working. No need for a PR, but thanks!
