### ISSUE TITLE
Required Information about peripheral files.

### ISSUE THREAD

**Issue by shivgarg5676** [coryhouse/react-slingshot#651]
Let me put it straight. Can I delete the following files?
1. .travis.yml
2. appveyor.yml
3. .istanbul.yml 

Can someone please give me a brief of the effects If I remove these files?
I have little idea for .istanbul.yml that if I remove this file then .spec files will start showing in the coverage report but I don't have any idea where .travis.yml and appveyor.yml are used.

**Comment by Ramadanko** [comment]
travis.yml and appveyor are files for Continuous Integration (CI for short)
the purpose of these files is to automate build process and deployment on the fly.
they are required for https://travis-ci.org/ and https://www.appveyor.com/ 
they shouldn't affect the project if you remove them but you should learn about it you can check this course 
https://app.pluralsight.com/library/courses/javascript-development-environment/table-of-contents by @coryhouse 
Testing and Continuous Integration module to learn more about CI

**Comment by nickytonline** [comment]
What @Ramadanko said and the Istanbul yaml file is for deciding which files to collect code coverage from.

Hope that clears things up for you.
