### ISSUE TITLE
accessing state from outside of component context

### ISSUE THREAD

**Issue by bingomanatee** [coryhouse/react-slingshot#68]
In this archictecture how do you access state from outside of components? 

My use case is this: 

I want certain components, when loaded, to register menu links onto the navigation system, potentially  interacting with the user ACL. Other similar stuff might include i18n content registration etc. 

How would I add stuff to the state / call actions not from inside the containers, but upon load time? 
Thanks, Dave

**Comment by coryhouse** [comment]
@bingomanatee I have some ideas but am unsure if they're the best approach. Since this is a Redux specific question, I'd suggest asking on the StackOverflow where more eyes will see it and benefit. Thanks!
