### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by waltercolindres** [coryhouse/react-slingshot#69]
So I've run into a bit of a wall with background images in sass loader. They are being encrypted in base64 and I can't seem to get them to link up correctly. I know this isn't a sass loader project, but was wondering if you had any recommendations on what to use along side it for the react-slingshot setup?

**Comment by waltercolindres** [comment]
Should probably explain a bit more:

I am putting some background images in my scss files and running this in my config.
```
const getLoaders = function (env) {
  const loaders = [{ test: /\.js$/, include: path.join(__dirname, 'src'), loaders: ['babel', 'eslint'] },
  {
     test: /\.(jpe?g|png|gif|svg)$/i,
     loaders: ['file']
   }

   ];

  if (env === productionEnvironment ) {
    // generate separate physical stylesheet for production build using ExtractTextPlugin. This provides separate caching and avoids a flash of unstyled content on load.
    loaders.push({test: /(\.css|\.scss)$/, loader: ExtractTextPlugin.extract("css?sourceMap!sass?sourceMap")});
  } else {
    loaders.push({test: /(\.css|\.scss)$/, loaders: ['style', 'css?sourceMap', 'sass?sourceMap']});
  }

  return loaders;
};

```

what i am getting is a an image with a dynamically generated name that links to an image, but it is currently linking to: 

```
.top-left {
    background-image: url(30898abe6ff41c413083cf5b7ef3a556.png);
}

```
right click to open in new tab and this is the url: 

`chrome-devtools://devtools/bundled/30898abe6ff41c413083cf5b7ef3a556.png`

Which does not work. But if I go to: 
`http://localhost:3000/30898abe6ff41c413083cf5b7ef3a556.png`

It works... so I am not sure what I am missing here.

**Comment by waltercolindres** [comment]
Follow up, I was able to get around this by removing source maps from dev, which is a bummer. Any recommendations on how I can use sourcemaps with images in scss?

**Comment by coryhouse** [comment]
I can't imagine why the sourcemap would conflict. What gave you the idea that removing them would help?

**Comment by waltercolindres** [comment]
I did a lot of googling and found some issues with image urls and libsass not playing nicely with sourcemaps. Another thing I found was an issue if the images are not relative to the sourcemap it can't find them, but I am not 100% sure on that being the cause. I'll see if I can find the issues I found again (got excited and closed all my windows). All I changed was this line:

```
old >> loaders.push({test: /(\.css|\.scss)$/, loaders: ['style', 'css?sourceMap', 'sass?sourceMap']});

new >>  loaders.push({test: /(\.css|\.scss)$/, loaders: ['style', 'css', 'sass']});

```
Love the project, my fav react starter so far!

**Comment by waltercolindres** [comment]
I am wondering if I need to add anything to the build tools to copy over the images. They seem to be broken now. I reverted to using sourcemaps.

**Comment by coryhouse** [comment]
@waltercolindres Can you get latest and try again? The webpack config now handles images, so I suspect this will resolve your issue.

**Comment by waltercolindres** [comment]
Ok, so interestingly, that fixed it if I do a npm run build. However, npm start still has it as a missing background image. So in prod it works, in dev the image is missing.

Is still produces an image link for dev: 
```
.top-left {
    background-image: url(30898abe6ff41c413083cf5b7ef3a556.png);
}

```
When I right click the image goes here which is un-viewable: 
`chrome-devtools://devtools/bundled/30898abe6ff41c413083cf5b7ef3a556.png`

<img width="933" alt="screenshot 2016-03-16 10 20 22" src="https://cloud.githubusercontent.com/assets/961369/13817578/c94562b0-eb60-11e5-9f9d-2edcc636ba6b.png">

But is viewable here:
`http://localhost:3000/30898abe6ff41c413083cf5b7ef3a556.png`

<img width="900" alt="screenshot 2016-03-16 10 20 17" src="https://cloud.githubusercontent.com/assets/961369/13817585/d00d2088-eb60-11e5-843f-4a0d0a38d0f4.png">


Another issue I've run into is that the images directory is not copying over during npm run build. Where can I place that command? They work fine during npm start/dev but once I do a build, they fall out. I can see that the images folder is not being copied over. So my inline images work in dev, but they don't get copied over for production. Which is ironic considering the first issue. :smile: 

Screen of my directory setup:
<img width="453" alt="screenshot 2016-03-16 10 12 49" src="https://cloud.githubusercontent.com/assets/961369/13817401/0bc2c7be-eb60-11e5-8eba-aca8f0d6423e.png">

Screen of my dist:
<img width="418" alt="screenshot 2016-03-16 10 12 44" src="https://cloud.githubusercontent.com/assets/961369/13817400/0bc04e26-eb60-11e5-8c36-237d4291301d.png">

**Comment by coryhouse** [comment]
It looks like you're two steps away from success:

1. Try using an absolute path for your image. I assume you're currently not providing a leading slash.
2. Add a build step to copy the images folder. Check /tools/buildHtml.js for an example of how I'm migrating the HTML file. Same idea.

**Comment by waltercolindres** [comment]
Thanks for you help Cory, definitely getting close.. This looks to be an issue with the style loader: https://github.com/vuejs/vue-loader-example/issues/43

I will close this!
