### ISSUE TITLE
integration with bootstrap

### ISSUE THREAD

**Issue by igorizr1** [coryhouse/react-slingshot#70]
How you suggest integration with Bootstrap?
Do you suggest including css into html directly or use npm for bootstrap or bootsrap-sass or something?

**Comment by coryhouse** [comment]
@igorizr1 This looks useful, but haven't tried. https://github.com/gowravshekar/bootstrap-webpack. That said, closing since not specific to this project.

**Comment by nickytonline** [comment]
@igorizr1, it's very easy to integrate bootstrap. From the root of the project, run `npm i bootstrap-sass --save`

In the `src/styles/styles.scss` simply add the following import at the top of the SASS file, `@import "node_modules/bootstrap-sass/assets/stylesheets/_bootstrap";`.

You now have bootstrap.

**Comment by corzzo** [comment]
@igorizr1 I'm getting problems with the fonts/svg:

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.eot ... @ ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.woff2 ... @ ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.woff ... @ ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.ttf ... @ ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss

ERROR in ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/bootstrap/glyphicons-halflings-regular.svg ... @ ./~/css-loader?sourceMap!./~/sass-loader?sourceMap!./src/styles/styles.scss

**Comment by coryhouse** [comment]
Here's an example of how I integrated bootstrap. This is a separate project that uses a slightly modified version of Slingshot, but close enough you can get the idea: https://github.com/coryhouse/ps-redux

**Comment by fulvio-m** [comment]
@corzzo it works fine if you import in the root index.js like this:
```
import '../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss';
```

**Comment by raythree** [comment]
I have no issue loading bootstrap via an npm install and a require of the css. However there seems to be issues if you use any of bootstrap.js, like tooltips. You can require it, but it requires JQuery, and I think I recall it wanting JQuery to be globally available, e.g. not a local "import $ from 'jquery'"... I need to re-investigate this. I was using [react-bootstrap-theme-switcher](https://github.com/raythree/react-bootstrap-theme-switcher) on my last app and that loads both bootstrap and jquery via dynamic links so I didn't have to worry about it.

**Comment by kwelch** [comment]
Another option that I used was [bootstrap-loader]https://github.com/shakacode/bootstrap-loader). This allows for themeing, scripts, and style selection.

**Comment by raythree** [comment]
Ah, I see [this](https://github.com/webpack/imports-loader) can be used to inject jQuery $ into the bootstrap module.

**Comment by kwelch** [comment]
Yes, that being said I switched from bootstrap to react-toolbox because it
modeled what I was looking for in a UI framework better.

**Comment by harshayburadkar** [comment]
@kwelch react-toolbox looks cool too. How did you go about integrating it in slingshot? Did you run into any issues? I think the css isn't getting applied for me. The react toolbox button I tried to put in my page shows up like a plain HTML button.

**Comment by kwelch** [comment]
@harshayburadkar I put the changes into [this PR](https://github.com/coryhouse/react-slingshot/pull/236). I hope this helps.
