### ISSUE TITLE
Error when add url into css styles

### ISSUE THREAD

**Issue by iLeonelPerea** [coryhouse/react-slingshot#73]
When I added a png file to a class:

`background: url('../img/automation_icons.png')`

 in the css occur that error:

`ERROR in ./src/img/automation_icons.png
Module parse failed: /Volumes/External Drive/Repos/provisioner/src/img/image.png Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/sass-loader!./src/styles/styles.scss 6:376-414 6:469-507 6:556-594`

I found a solution check the pullrequest #74 

tnks.

**Comment by coryhouse** [comment]
PR accepted. Thanks again!
