### ISSUE TITLE
404 on hot-update.json when using subroutes

### ISSUE THREAD

**Issue by jonahlau** [coryhouse/react-slingshot#75]
Hi there, I might be missing something really obvious here, but I've found that hot reload isn't working ( I get  
```
404 GET http://localhost:3004/orders/c344e97ed1fbc2923017.hot-update.json 404 (Not Found) 
```
on the `CreateOrder` component when I have the following routes configuration:
```
  <Route path="/" component={App}>
    <Route path="login" component={Login} />
    <Route path="orders" component={OrderPanel} />
    <Route path="orders/create" component={CreateOrder} />
    <Route path="*" component={NotFoundPage} />
  </Route>
```
But when I  change the path from `orders/create` to just `create`, it doesn't returns a 404.

It seems like the hot update middleware is trying to fetch the hot-update.json from the `/orders` subroute?

**Comment by coryhouse** [comment]
Sorry, since this isn't specific to the out of the box code, I need to close this. Suggest posting on StackOverflow.

**Comment by juanpasolano** [comment]
I was having the same issue. 
Changing the `output.publicPath` from empty string to `"/"` on `webpack.config.js` worked for me. [Line](https://github.com/coryhouse/react-slingshot/blob/master/webpack.config.js#L74)

**Comment by jonahlau** [comment]
Thanks @juanpasolano! @coryhouse I think this could be included in the docs. What do you think?

**Comment by coryhouse** [comment]
Nice catch! I

**Comment by coryhouse** [comment]
Change committed. Closing. Thanks for reporting!
