### ISSUE TITLE
.eslintrc contains jQuery and $ as globals

### ISSUE THREAD

**Issue by phereford** [coryhouse/react-slingshot#8]
Hi there!

A quick grep of the codebase reveals that jQuery is not being utilized by the codebase. Is there any reason as to why its set as a global in the .eslintrc?

Thanks for setting this project up!

**Comment by coryhouse** [comment]
Ah, good catch. I've removed them. Thanks!

**Comment by RaulTsc** [comment]
This repo is a boilerplate, so if you decide to import jQuery in index.html and use it in some Component then you know it's there and it'll work, but the linter will complain and those two options tell it it's fine. 

Might be wrong though.

**Comment by phereford** [comment]
Not a problem!
