### ISSUE TITLE
Images don't show as background-image when using css-loader sourceMap option

### ISSUE THREAD

**Issue by firstdoit** [coryhouse/react-slingshot#81]
Reported here: https://github.com/webpack/css-loader/issues/216
Discussed here: https://github.com/webpack/style-loader/issues/55

I simply removed sourceMap from my build. I think it's worth it at least documenting this big caveat, but I'd vote to remove CSS sourceMap completely.

**Comment by coryhouse** [comment]
I see multiple options:

1. Disable css sourcemap
2. Disable css minification so we don't need the sourcemap
3. Advise using absolute paths for images
4. Leave as is and wait for a fix - though appears unclear if one is in the works

I lean toward option 2. Option 1 means debugging CSS would be difficult. Thoughts?

**Comment by firstdoit** [comment]
Minifying only in production build sounds good. (Without sourcemaps)

**Comment by coryhouse** [comment]
Just occurred to me - the reason sourcemaps are so useful is we're compiling from SASS. So without them, you're lost during dev. Now I'm torn. We basically have a choice between:

1. Disable sourcemaps, which provides a bad CSS debugging experience for all
2. Keep sourcemaps, and let those with this issue use absolute paths or wait for a fix.

After thinking about this more, I think keeping sourcemaps on is the best approach. We'd certainly want them if it weren't for this (hopefully short-term) bug.

**Comment by firstdoit** [comment]
I'd just like to add that "those with this issue" should be 100% of people
working on a real world app. How can you *not* use background-image? :)

At least we should have a FAQ in the README, I guess.

**Comment by lovio** [comment]
Just disable css sourceMaps and it works

**Comment by zsherman** [comment]
I'd also vote for option #2 fwiw.

**Comment by Strate** [comment]
This is a fix #96

**Comment by coryhouse** [comment]
@Strate Great to hear! Hopefully they accept that PR soon.

**Comment by kwelch** [comment]
PR #205 uses the fix quick fix discussed in webpack/style-loader#96, so this item should be resolved. I can re-test to verify.

**Comment by kwelch** [comment]
Validated with the update to set webpack path dynamically, relative background images work.

Closing.

**Comment by coryhouse** [comment]
Awesome! Thanks Kyle!
