### ISSUE TITLE
Eliminate babel-eslint and disable stage-1 support?

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#87]
[We do not need babel-eslint](https://twitter.com/geteslint/status/714642903482564608) if we disable support for experimental features. How do people feel? Do we want to keep stage-1 support?

**Comment by coryhouse** [comment]
Only issue: ESLint doesn't support stage 1-3 proposals like Babel does. So our options are:

1. Keep supporting bleeding edge Stage 1 features via babel-eslint
2. Remove Babel stage 1-3 support and run ESLint directly. Eliminate babel-eslint

**Comment by kwelch** [comment]
In the event you are looking for an opinoin, here is mine. 

I have already removed `babel-eslint` with the knowledge I only planned on supporting es2015.

**Comment by darcnite3000** [comment]
Since babel dropped decorator support i have moved down to stage-2 mainly for the object spread functionality, which to me simplifies object combination and immutable updating.

**Comment by kwelch** [comment]
This is one thing that I tend to use frequently but I have not had any
issues linting with eslint and the babelrc included in my PR. It may be a
good idea to update my PR to show that it can be used/how to use it.

**Comment by kwelch** [comment]
@coryhouse Shouldn't this be closed based on the changes from es-watch

**Comment by coryhouse** [comment]
Yep, good catch. Closing.
