### ISSUE TITLE
Symbol is not defined

### ISSUE THREAD

**Issue by jwkellyiii** [coryhouse/react-slingshot#9]
Running npm start -s is failing with: "Module build failed: ReferenceError: /react-slingshot/node_modules/eslint-loader/index.js!/react-slingshot/src/index.js: Symbol is not defined"

babel-plugin-react-transform needs to be updated to version 1.1.1 in package.json

**Comment by coryhouse** [comment]
I've just upgraded the package.json to 1.1.1. Can you please get latest and see if you're fixed?

**Comment by jwkellyiii** [comment]
Yes, the upgrade to 1.1.1 fixes the issue. This was more of an FYI.

**Comment by coryhouse** [comment]
Excellent. Thanks!
