### ISSUE TITLE
Production build did not work in Android native browser

### ISSUE THREAD

**Issue by gm3000** [coryhouse/react-slingshot#90]
hi there,
it`s been killing me for days to find out any possible clue for the build to work in the android(>5.0) native browser.
seems the bundle.js is not executed, the index.html is still the index.html, without app section getting mounted.
is it possible something was wrongly configured in webpack?
safari, chrome on pc/mobile all works fine, don`t know what`s wrong with the android native browser.
any clue?

**Comment by coryhouse** [comment]
Can you please try with the new [3.0 release](https://github.com/coryhouse/react-slingshot/releases/tag/v3.0.0)

**Comment by coryhouse** [comment]
Closing since no response. Please reopen if issue persists.
