### ISSUE TITLE
npm run build error, can't build the files

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#92]
A lot of error is showing when building the files for production. Can you check it out?

**Comment by coryhouse** [comment]
You deleted all the .spec files, so Mocha is bombing. Disable running tests or create at least one .spec file.

**Comment by gitlovenotwar** [comment]
Hmmm... I think I have deleted some, not sure. How should I disable the running test? or at least create one spec?

**Comment by coryhouse** [comment]
Remove the call to test:watch from the start script in package.json.

**Comment by gitlovenotwar** [comment]
Hi, thanks a lot for the help. It solved the problem. I am able to build now. :)
