### ISSUE TITLE
How to hide a lot of console output? Also for page reload doesn't properly work?

### ISSUE THREAD

**Issue by gitlovenotwar** [coryhouse/react-slingshot#94]
Hi, Is there a way to hide a lot of console output on dev tools? It's showing a lot of things, that I think not much needed? Is there an option to hide it? And also for the page reload, it doesn't properly work. I have updated some code i.e. put a console.log("test"); on some file, and it does not show directly on the dev tools after watching/bundling the files. I have to manually refresh the browser to see it.

**Comment by coryhouse** [comment]
npm start -s

That will hide output.

Regarding 2nd question, hot reloading has some known quirks so it's not 100% reliable. Sometimes you have to reload depending on context.

**Comment by gitlovenotwar** [comment]
I see, why not add the livereload also?

**Comment by coryhouse** [comment]
The way slingshot is configured, it will typically livereload if hot reloading fails, but there are some known issues with hot reloading. It's not bullet proof but I find the current benefits outweigh the costs.

**Comment by gitlovenotwar** [comment]
ah yes, I noticed that. Thanks for the time to discuss the issue, overall on the kit it's awesome. :+1:
