### ISSUE TITLE
Using react-redux-form and redux-thunk

### ISSUE THREAD

**Issue by rijvirajib** [coryhouse/react-slingshot#95]
Hello, I am attempting to add in react-redux-form into my boilerplate app and having a difficult time understanding how the dispatches work.

I have a 3 tier compotenent, `FuelingPage`,` FuelingForm`, and `FuelingFormFirstPage`.

How would I access `dispatch` from `FuelingFormFirstPage` or even `FuelingForm` as instructed here: https://davidkpiano.gitbooks.io/react-redux-form/content/validation.html ? I am trying to validate the form input before changing the page state to the next page.

My current setup is exactly like the existing example with the addition of a `changePage` action which changes the `appState's` page.

**Comment by coryhouse** [comment]
To dispatch an action in a child component, pass a function down from your container component. So in your case, I assume FuelingPage is your container component. I suggesting passing the bound action down via props to your child components. Check the Redux docs for bindActionCreators for a handy helper method.
