### ISSUE TITLE
add ajax structure support 

### ISSUE THREAD

**Issue by danywheeler** [coryhouse/react-slingshot#96]
this boilerpate doesn't have ajax build in , it would be nice to add this .

**Comment by coryhouse** [comment]
Can you be more specific? Are you suggesting adding Redux thunk?

**Comment by danywheeler** [comment]
yeah, I think every project needs ajax to get data.

**Comment by kwelch** [comment]
Are wanting to see a promise library included?

**Comment by danywheeler** [comment]
ah, I was thinking Redux thunk +  normalizr .

**Comment by coryhouse** [comment]
I have considered adding Redux thunk, but there are other popular alternatives like Sagas and redux-promise. All three are easy to wire up, so I'm not sold it's worth having an opinion on this.

**Comment by darcnite3000** [comment]
I'd recommend adding the fetch polyfill though this assumes promises exist on the browser you use thus also recommend the es6-promise polyfill
This is added to the plugins in webpack and gets it running quite nicely which i pulled from https://gist.github.com/Couto/b29676dd1ab8714a818f and http://mts.io/2015/04/08/webpack-shims-polyfills/

```
new webpack.ProvidePlugin({
      'Promise': 'es6-promise',
      'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
    })
```

**Comment by j5v** [comment]
I've had good results from `isomorphic-fetch`, using a technique similar to the redux 'reddit' example, with action creators like this (noting that this could be abstracted into a wrapper for multiple API methods):

```JavaScript
function fetchProducts(locationID) { // private
	return dispatch => {
		dispatch(requestProducts());
		return fetch(
			api.rootPath + api.catalogue + locationID,
			{
				method: 'GET',
				headers: {
					'Accept': 'application/json'
				}
			}
		)
		.then(response => response.json())
		.then(json => dispatch(receiveProducts(json)));
	};
}
```

**Comment by kwelch** [comment]
Redux-thunk has been added and taking on any other async support at this point. Closing.
