### ISSUE TITLE
Add code coverage reporting

### ISSUE THREAD

**Issue by coryhouse** [coryhouse/react-slingshot#97]
I'm interested in including code coverage reporting within Slingshot. [Isparta](https://github.com/douglasduteil/isparta) and [nyc](https://github.com/bcoe/nyc) are two top candidates to consider.

**Comment by jeremyadavis** [comment]
I'll try to look into this. I'm about 85% done with my unit tests for my app build on slingshot, then I was gonna create a PR with my recommendations.

In my research, I've also seen a few mentions of [Istanbul](https://gotwarlost.github.io/istanbul/) for coverage so I'll add that as a candidate to consider as well.

**Comment by coryhouse** [comment]
Excellent! Istanbul is expected to add ES6 support in its next major release, but until it does, it's not an option.

**Comment by nickytonline** [comment]
There is also remap-istanbul.

**Comment by dwmkerr** [comment]
Created PR #142 for this if you are interested guys :smile:
